apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata: { name: orders, namespace: database }
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:18.4-system-trixie
  primaryUpdateStrategy: unsupervised
  primaryUpdateMethod: switchover
  enableSuperuserAccess: false
  minSyncReplicas: 1
  maxSyncReplicas: 1
  postgresql:
    parameters:
      max_connections: "300"
      shared_buffers: 512MB
      log_min_duration_statement: "500"
      idle_in_transaction_session_timeout: 60s
  storage: { size: 50Gi, storageClass: replace-encrypted-rwo }
  walStorage: { size: 20Gi, storageClass: replace-encrypted-rwo }
  resources: { requests: { cpu: "1", memory: 2Gi }, limits: { cpu: "4", memory: 8Gi } }
  affinity:
    enablePodAntiAffinity: true
    topologyKey: topology.kubernetes.io/zone
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters: { barmanObjectName: orders-store }
