apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: saas
  namespace: saas-typescript
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 1m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "15"
spec:
  ingressClassName: nginx
  rules:
    - host: saas.local.example
      http:
        paths:
          - path: /
            pathType: Prefix
            backend: { service: { name: saas-api, port: { number: 80 } } }
