apiVersion: v1
kind: Namespace
metadata:
  name: shortener-go
  labels:
    app.kubernetes.io/part-of: shortener
    pod-security.kubernetes.io/enforce: restricted
---
apiVersion: v1
kind: ServiceAccount
metadata: { name: shortener, namespace: shortener-go }
automountServiceAccountToken: false
