{
  "apiVersion": "kustomize.config.k8s.io/v1beta1",
  "kind": "Kustomization",
  "namespace": "standard-dev",
  "namePrefix": "go-",
  "resources": [
    "../../../base"
  ],
  "labels": [
    {
      "pairs": {
        "app.kubernetes.io/instance": "go"
      },
      "includeSelectors": true,
      "includeTemplates": true
    }
  ],
  "configMapGenerator": [
    {
      "name": "deployment-config",
      "literals": [
        "APP_ENV=dev",
        "APP_VERSION=unreleased"
      ]
    }
  ],
  "images": [
    {
      "name": "deployment-demo",
      "newName": "ghcr.io/REPLACE_OWNER/standard-go",
      "newTag": "unreleased"
    }
  ],
  "replicas": [
    {
      "name": "deployment-demo",
      "count": 1
    }
  ]
}
