apiVersion: v1
kind: ConfigMap
metadata: { name: collaboration-config, namespace: collaboration-mern }
data:
  APP_ENV: "kubernetes"
  LOG_LEVEL: "info"
  API_URL: "http://collaboration-api"
  FRONTEND_URL: "http://collaboration-frontend"
