apiVersion: v1
kind: ServiceAccount
metadata: { name: environment-operator, namespace: environment-system }
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata: { name: environment-operator }
rules:
  - apiGroups: [platform.masterclass.io]
    resources: [environments, environments/status, environments/finalizers]
    verbs: [get, list, watch, create, update, patch]
  - apiGroups: [""]
    resources: [namespaces, resourcequotas, limitranges]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [networking.k8s.io]
    resources: [networkpolicies]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [coordination.k8s.io]
    resources: [leases]
    verbs: [get, list, watch, create, update, patch, delete]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata: { name: environment-operator }
roleRef: { apiGroup: rbac.authorization.k8s.io, kind: ClusterRole, name: environment-operator }
subjects: [{ kind: ServiceAccount, name: environment-operator, namespace: environment-system }]
