version: 2
sources:
  - name: platform
    schema: public
    tables:
      - name: raw_orders
        columns:
          - name: event_id
            tests: [unique, not_null]
          - name: event_time
            tests: [not_null]
models:
  - name: stg_orders
    columns:
      - name: event_id
        tests: [unique, not_null]
  - name: fct_daily_orders
    columns:
      - name: event_date
        tests: [not_null]
