apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [../../base, secret.local.yaml]
labels:
  - pairs: { app.kubernetes.io/environment: dev }
patches:
  - target: { kind: Deployment }
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target: { kind: HorizontalPodAutoscaler }
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 3
