package com.example.banking.ledger;
import java.math.BigDecimal;import java.time.Instant;import java.util.*;import java.util.concurrent.ConcurrentHashMap;import org.springframework.beans.factory.annotation.Value;import org.springframework.boot.*;import org.springframework.boot.autoconfigure.*;import org.springframework.context.annotation.Bean;import org.springframework.http.*;import org.springframework.web.bind.annotation.*;import org.springframework.web.client.RestClient;import org.springframework.web.server.ResponseStatusException;
@SpringBootApplication public class LedgerApplication{public static void main(String[]a){SpringApplication.run(LedgerApplication.class,a);}@Bean RestClient accounts(@Value("${ACCOUNTS_URL:http://accounts:8081}")String url){return RestClient.create(url);}}
record TransferCommand(String sourceAccountId,String destinationAccountId,BigDecimal amount,String currency){}record Transfer(String id,String sourceAccountId,String destinationAccountId,BigDecimal amount,String currency,String status,Instant createdAt){}
@RestController @RequestMapping("/transfers") class LedgerController{
 private final RestClient accounts;private final Map<String,Transfer> data=new ConcurrentHashMap<>();private final Map<String,String> keys=new ConcurrentHashMap<>();LedgerController(RestClient accounts){this.accounts=accounts;}
 @GetMapping Collection<Transfer> list(){return data.values();}
 @PostMapping @ResponseStatus(HttpStatus.CREATED) synchronized Transfer create(@RequestBody TransferCommand c,@RequestHeader("Idempotency-Key")String key){if(keys.containsKey(key))return data.get(keys.get(key));if(c.amount()==null||c.amount().signum()<=0||c.sourceAccountId().equals(c.destinationAccountId()))throw new ResponseStatusException(HttpStatus.UNPROCESSABLE_ENTITY,"invalid transfer");accounts.get().uri("/accounts/{id}",c.sourceAccountId()).retrieve().toBodilessEntity();accounts.get().uri("/accounts/{id}",c.destinationAccountId()).retrieve().toBodilessEntity();var t=new Transfer(UUID.randomUUID().toString(),c.sourceAccountId(),c.destinationAccountId(),c.amount(),c.currency(),"posted",Instant.now());data.put(t.id(),t);keys.put(key,t.id());return t;}
}
