{
  "apiVersion": "policy/v1",
  "kind": "PodDisruptionBudget",
  "metadata": {
    "name": "deployment-demo"
  },
  "spec": {
    "maxUnavailable": 1,
    "selector": {
      "matchLabels": {
        "app.kubernetes.io/name": "deployment-demo"
      }
    }
  }
}
