apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata: { name: checkout-health, namespace: progressive }
spec:
  args: [{ name: service-name }]
  metrics:
    - name: success-rate
      interval: 1m
      count: 5
      successCondition: result[0] >= 0.995
      failureLimit: 2
      provider:
        prometheus:
          address: http://prometheus.monitoring.svc:9090
          query: sum(rate(http_requests_total{service="{{args.service-name}}",status!~"5.."}[2m])) / sum(rate(http_requests_total{service="{{args.service-name}}"}[2m]))
    - name: p95-latency
      interval: 1m
      count: 5
      successCondition: result[0] < 0.4
      failureLimit: 2
      provider:
        prometheus:
          address: http://prometheus.monitoring.svc:9090
          query: histogram_quantile(0.95,sum by (le) (rate(http_request_duration_seconds_bucket{service="{{args.service-name}}"}[2m])))
