apiVersion: v1
kind: Namespace
metadata:
  name: inventory-php
  labels:
    app.kubernetes.io/part-of: inventory
    pod-security.kubernetes.io/enforce: restricted
---
apiVersion: v1
kind: ServiceAccount
metadata: { name: inventory, namespace: inventory-php }
automountServiceAccountToken: false
