{
  "apiVersion": "v1",
  "kind": "Namespace",
  "metadata": {
    "name": "standard-staging",
    "labels": {
      "pod-security.kubernetes.io/enforce": "restricted",
      "pod-security.kubernetes.io/enforce-version": "v1.34"
    }
  }
}
