apiVersion: v1
kind: Namespace
metadata:
  name: telemetry-cpp
  labels:
    app.kubernetes.io/part-of: telemetry
    pod-security.kubernetes.io/enforce: restricted
---
apiVersion: v1
kind: ServiceAccount
metadata: { name: telemetry, namespace: telemetry-cpp }
automountServiceAccountToken: false
