package main

import("context";"embed";"encoding/json";"errors";"fmt";"io/fs";"log/slog";"net/http";"os";"os/signal";"strings";"sync/atomic";"syscall";"time";"github.com/jackc/pgx/v5";"github.com/jackc/pgx/v5/pgxpool")

//go:embed web/*
var assets embed.FS
type application struct{db *pgxpool.Pool;requests atomic.Uint64;redirects atomic.Uint64}
type link struct{Code string `json:"code"`;URL string `json:"url"`;Hits int64 `json:"hits"`;CreatedAt time.Time `json:"createdAt"`}
type createLink struct{URL string `json:"url"`}

func main(){ctx:=context.Background();pool,err:=pgxpool.New(ctx,required("DATABASE_URL"));if err!=nil{panic(err)};defer pool.Close();if err=migrate(ctx,pool);err!=nil{panic(err)};a:=&application{db:pool};mux:=http.NewServeMux();mux.HandleFunc("GET /health",a.health);mux.HandleFunc("GET /metrics",a.metrics);mux.HandleFunc("GET /api/links",a.list);mux.HandleFunc("POST /api/links",a.create);mux.HandleFunc("GET /r/{code}",a.redirect);content,_:=fs.Sub(assets,"web");mux.Handle("/",http.FileServer(http.FS(content)));server:=&http.Server{Addr:":"+env("PORT","8080"),Handler:a.telemetry(mux),ReadHeaderTimeout:5*time.Second,ReadTimeout:10*time.Second,WriteTimeout:10*time.Second,IdleTimeout:60*time.Second,MaxHeaderBytes:1<<20};go func(){slog.Info("shortener started","address",server.Addr);if err:=server.ListenAndServe();err!=nil&&!errors.Is(err,http.ErrServerClosed){panic(err)}}();stop:=make(chan os.Signal,1);signal.Notify(stop,syscall.SIGINT,syscall.SIGTERM);<-stop;shutdown,cancel:=context.WithTimeout(context.Background(),25*time.Second);defer cancel();_ = server.Shutdown(shutdown)}
func migrate(ctx context.Context,db *pgxpool.Pool)error{_,err:=db.Exec(ctx,`CREATE TABLE IF NOT EXISTS links(code varchar(16) PRIMARY KEY,url varchar(2048) NOT NULL,hits bigint NOT NULL DEFAULT 0,created_at timestamptz NOT NULL DEFAULT now(),idempotency_key varchar(128) UNIQUE NOT NULL)`);return err}
func(a *application)telemetry(next http.Handler)http.Handler{return http.HandlerFunc(func(w http.ResponseWriter,r *http.Request){a.requests.Add(1);requestID:=r.Header.Get("X-Request-ID");if requestID==""{requestID=fmt.Sprintf("req-%d",time.Now().UnixNano())};w.Header().Set("X-Request-ID",requestID);started:=time.Now();next.ServeHTTP(w,r);slog.Info("request","requestId",requestID,"method",r.Method,"path",r.URL.Path,"durationMs",time.Since(started).Milliseconds())})}
func(a *application)health(w http.ResponseWriter,r *http.Request){ctx,cancel:=context.WithTimeout(r.Context(),2*time.Second);defer cancel();if err:=a.db.Ping(ctx);err!=nil{write(w,503,map[string]string{"status":"not_ready"});return};write(w,200,map[string]string{"status":"ok","service":"shortener-app"})}
func(a *application)metrics(w http.ResponseWriter,_ *http.Request){w.Header().Set("Content-Type","text/plain; version=0.0.4");fmt.Fprintf(w,"# HELP shortener_http_requests_total HTTP requests\n# TYPE shortener_http_requests_total counter\nshortener_http_requests_total %d\n# HELP shortener_redirects_total Successful redirects\n# TYPE shortener_redirects_total counter\nshortener_redirects_total %d\n",a.requests.Load(),a.redirects.Load())}
func(a *application)list(w http.ResponseWriter,r *http.Request){rows,err:=a.db.Query(r.Context(),`SELECT code,url,hits,created_at FROM links ORDER BY created_at DESC LIMIT 200`);if err!=nil{problem(w,500,"INTERNAL_ERROR");return};defer rows.Close();values:=[]link{};for rows.Next(){var value link;if rows.Scan(&value.Code,&value.URL,&value.Hits,&value.CreatedAt)==nil{values=append(values,value)}};write(w,200,values)}
func(a *application)create(w http.ResponseWriter,r *http.Request){key:=r.Header.Get("Idempotency-Key");if key==""||len(key)>128{problem(w,400,"IDEMPOTENCY_KEY_REQUIRED");return};var input createLink;if json.NewDecoder(http.MaxBytesReader(w,r.Body,64<<10)).Decode(&input)!=nil{problem(w,400,"INVALID_JSON");return};target,err:=normalizeURL(input.URL);if err!=nil{problem(w,422,err.Error());return};var value link;err=a.db.QueryRow(r.Context(),`SELECT code,url,hits,created_at FROM links WHERE idempotency_key=$1`,key).Scan(&value.Code,&value.URL,&value.Hits,&value.CreatedAt);if err==nil{write(w,200,value);return};if !errors.Is(err,pgx.ErrNoRows){problem(w,500,"INTERNAL_ERROR");return};code:=codeFor(key);err=a.db.QueryRow(r.Context(),`INSERT INTO links(code,url,idempotency_key) VALUES($1,$2,$3) ON CONFLICT(idempotency_key) DO UPDATE SET idempotency_key=excluded.idempotency_key RETURNING code,url,hits,created_at`,code,target,key).Scan(&value.Code,&value.URL,&value.Hits,&value.CreatedAt);if err!=nil{problem(w,500,"INTERNAL_ERROR");return};write(w,201,value)}
func(a *application)redirect(w http.ResponseWriter,r *http.Request){code:=strings.TrimSpace(r.PathValue("code"));if len(code)<4||len(code)>16{problem(w,404,"LINK_NOT_FOUND");return};var target string;err:=a.db.QueryRow(r.Context(),`UPDATE links SET hits=hits+1 WHERE code=$1 RETURNING url`,code).Scan(&target);if errors.Is(err,pgx.ErrNoRows){problem(w,404,"LINK_NOT_FOUND");return};if err!=nil{problem(w,500,"INTERNAL_ERROR");return};a.redirects.Add(1);http.Redirect(w,r,target,http.StatusTemporaryRedirect)}
func write(w http.ResponseWriter,status int,value any){w.Header().Set("Content-Type","application/json");w.WriteHeader(status);_ = json.NewEncoder(w).Encode(value)}
func problem(w http.ResponseWriter,status int,code string){write(w,status,map[string]string{"code":code})}
func env(key,fallback string)string{if value:=os.Getenv(key);value!=""{return value};return fallback}
func required(key string)string{value:=os.Getenv(key);if value==""{panic(key+" is required")};return value}
