apiVersion: v1
kind: Namespace
metadata:
  name: learning-python
  labels:
    app.kubernetes.io/part-of: learning
    pod-security.kubernetes.io/enforce: restricted
---
apiVersion: v1
kind: ServiceAccount
metadata: { name: learning, namespace: learning-python }
automountServiceAccountToken: false
