apiVersion: audit.k8s.io/v1
kind: Policy
omitStages: [RequestReceived]
rules:
  - level: RequestResponse
    resources: [{ group: "", resources: [secrets, serviceaccounts/token] }]
  - level: Request
    resources: [{ group: rbac.authorization.k8s.io, resources: [roles, rolebindings, clusterroles, clusterrolebindings] }]
  - level: Metadata
    verbs: [create, update, patch, delete]
  - level: None
