source "https://rubygems.org"
ruby "~> 3.4.0"
gem "rails", "8.1.3.1"
gem "pg", "1.6.2"
gem "puma", "7.0.4"
gem "propshaft", "1.3.1"
gem "importmap-rails", "2.2.2"
gem "turbo-rails", "2.0.20"
gem "bootsnap", "1.18.6", require: false
