mod domain;
use std::{env,sync::Arc,time::Duration};
use async_nats::Client as NatsClient;
use axum::{extract::State,http::{header,HeaderMap,StatusCode},response::{IntoResponse,Response},routing::get,Json,Router};
use domain::{assess,PaymentDraft};
use serde_json::{json,Value};
use tokio::sync::Mutex;
use tokio_postgres::{Client,NoTls};
use tracing::{error,info};
use uuid::Uuid;

#[derive(Clone)]struct AppState{db:Arc<Mutex<Client>>,nats:NatsClient}
struct ApiError(StatusCode,&'static str);impl IntoResponse for ApiError{fn into_response(self)->Response{(self.0,Json(json!({"code":self.1}))).into_response()}}

#[tokio::main]
async fn main(){
 tracing_subscriber::fmt().json().with_env_filter(tracing_subscriber::EnvFilter::from_default_env()).init();
 let database_url=env::var("DATABASE_URL").unwrap_or_else(|_|"postgres://app:local-development-only@localhost/app".into());
 let (client,connection)=tokio_postgres::connect(&database_url,NoTls).await.expect("database connection");tokio::spawn(async move{if let Err(error)=connection.await{error!(%error,"database connection ended")}});
 client.batch_execute("CREATE TABLE IF NOT EXISTS payments(id uuid PRIMARY KEY,merchant_id varchar(64) NOT NULL,amount double precision NOT NULL,country char(2) NOT NULL,risk_score integer NOT NULL,decision varchar(16) NOT NULL,idempotency_key varchar(128) UNIQUE NOT NULL,created_at timestamptz NOT NULL DEFAULT now());CREATE TABLE IF NOT EXISTS payment_outbox(id uuid PRIMARY KEY,payload jsonb NOT NULL,published_at timestamptz NULL,created_at timestamptz NOT NULL DEFAULT now());").await.expect("schema");
 let nats_url=env::var("NATS_URL").unwrap_or_else(|_|"nats://localhost:4222".into());let nats=connect_nats(&nats_url).await;
 let state=AppState{db:Arc::new(Mutex::new(client)),nats};tokio::spawn(publish_outbox(state.clone()));
 let app=Router::new().route("/health",get(health)).route("/metrics",get(metrics)).route("/api/payments",get(list).post(create)).with_state(state);
 let address=env::var("LISTEN_ADDRESS").unwrap_or_else(|_|"0.0.0.0:8080".into());let listener=tokio::net::TcpListener::bind(&address).await.expect("listen");info!(%address,"payment risk service started");axum::serve(listener,app).with_graceful_shutdown(shutdown()).await.expect("server");
}
async fn connect_nats(url:&str)->NatsClient{loop{match async_nats::connect(url).await{Ok(client)=>return client,Err(error)=>{error!(%error,"nats unavailable");tokio::time::sleep(Duration::from_secs(2)).await}}}}
async fn health(State(state):State<AppState>)->Result<Json<Value>,ApiError>{state.db.lock().await.simple_query("SELECT 1").await.map_err(|_|ApiError(StatusCode::SERVICE_UNAVAILABLE,"NOT_READY"))?;Ok(Json(json!({"status":"ok","service":"payment-risk"})))}
async fn metrics()->impl IntoResponse{([(header::CONTENT_TYPE,"text/plain; version=0.0.4")],"# HELP payment_risk_up Service readiness\n# TYPE payment_risk_up gauge\npayment_risk_up 1\n")}
async fn list(State(state):State<AppState>)->Result<Json<Value>,ApiError>{let rows=state.db.lock().await.query("SELECT id::text,merchant_id,amount,country,risk_score,decision,created_at::text FROM payments ORDER BY created_at DESC LIMIT 200",&[]).await.map_err(|_|ApiError(StatusCode::INTERNAL_SERVER_ERROR,"DATABASE_ERROR"))?;Ok(Json(Value::Array(rows.iter().map(|r|json!({"id":r.get::<_,String>(0),"merchantId":r.get::<_,String>(1),"amount":r.get::<_,f64>(2),"country":r.get::<_,String>(3),"riskScore":r.get::<_,i32>(4),"decision":r.get::<_,String>(5),"createdAt":r.get::<_,String>(6)})).collect())))}
async fn create(State(state):State<AppState>,headers:HeaderMap,Json(draft):Json<PaymentDraft>)->Result<(StatusCode,Json<Value>),ApiError>{let key=headers.get("idempotency-key").and_then(|v|v.to_str().ok()).unwrap_or("");if key.is_empty()||key.len()>128{return Err(ApiError(StatusCode::BAD_REQUEST,"IDEMPOTENCY_KEY_REQUIRED"))}let value=assess(draft).map_err(|error|match error{domain::ValidationError::Merchant=>ApiError(StatusCode::UNPROCESSABLE_ENTITY,"INVALID_MERCHANT"),domain::ValidationError::Amount=>ApiError(StatusCode::UNPROCESSABLE_ENTITY,"INVALID_AMOUNT"),domain::ValidationError::Country=>ApiError(StatusCode::UNPROCESSABLE_ENTITY,"INVALID_COUNTRY")})?;let id=Uuid::new_v4();let event_id=Uuid::new_v4();let payload=json!({"eventId":event_id,"paymentId":id,"merchantId":value.merchant_id,"amount":value.amount,"country":value.country,"riskScore":value.risk_score,"decision":value.decision});let mut db=state.db.lock().await;let tx=db.transaction().await.map_err(|_|ApiError(StatusCode::INTERNAL_SERVER_ERROR,"DATABASE_ERROR"))?;let row=tx.query_one("WITH inserted AS (INSERT INTO payments(id,merchant_id,amount,country,risk_score,decision,idempotency_key) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(idempotency_key) DO NOTHING RETURNING id,merchant_id,amount,country,risk_score,decision,created_at) SELECT true,id::text,merchant_id,amount,country,risk_score,decision,created_at::text FROM inserted UNION ALL SELECT false,id::text,merchant_id,amount,country,risk_score,decision,created_at::text FROM payments WHERE idempotency_key=$7 LIMIT 1",&[&id,&value.merchant_id,&value.amount,&value.country,&value.risk_score,&value.decision,&key]).await.map_err(|_|ApiError(StatusCode::INTERNAL_SERVER_ERROR,"DATABASE_ERROR"))?;let created:bool=row.get(0);if created{tx.execute("INSERT INTO payment_outbox(id,payload) VALUES($1,$2::jsonb)",&[&event_id,&payload.to_string()]).await.map_err(|_|ApiError(StatusCode::INTERNAL_SERVER_ERROR,"DATABASE_ERROR"))?;}tx.commit().await.map_err(|_|ApiError(StatusCode::INTERNAL_SERVER_ERROR,"DATABASE_ERROR"))?;let status=if created{StatusCode::CREATED}else{StatusCode::OK};Ok((status,Json(json!({"id":row.get::<_,String>(1),"merchantId":row.get::<_,String>(2),"amount":row.get::<_,f64>(3),"country":row.get::<_,String>(4),"riskScore":row.get::<_,i32>(5),"decision":row.get::<_,String>(6),"createdAt":row.get::<_,String>(7)}))))}
async fn publish_outbox(state:AppState){loop{tokio::time::sleep(Duration::from_millis(500)).await;let rows=match state.db.lock().await.query("SELECT id,payload::text FROM payment_outbox WHERE published_at IS NULL ORDER BY created_at LIMIT 50",&[]).await{Ok(rows)=>rows,Err(error)=>{error!(%error,"outbox query failed");continue}};for row in rows{let id:Uuid=row.get(0);let payload:String=row.get(1);if state.nats.publish("payment.risk.assessed",payload.into()).await.is_ok(){let _=state.db.lock().await.execute("UPDATE payment_outbox SET published_at=now() WHERE id=$1",&[&id]).await;}}}}
async fn shutdown(){let ctrl_c=async{tokio::signal::ctrl_c().await.expect("signal")};#[cfg(unix)]let terminate=async{tokio::signal::unix::signal(tokio::signal::unix::SignalKind::terminate()).expect("signal").recv().await;};#[cfg(not(unix))]let terminate=std::future::pending::<()>();tokio::select!{_=ctrl_c=>{},_=terminate=>{}}}
