param([switch]$WhatIfMode)
. (Join-Path $PSScriptRoot 'Common.ps1')
$root=Join-Path $script:ProjectsRoot '11-aws-serverless-media-pipeline'

Write-TemplateFile $root '.template-owned' 'Generated by tools/module20-projects. Additional user files are never deleted.' -WhatIfMode:$WhatIfMode
Write-TemplateFile $root '.gitignore' @'
.aws-sam/
.terraform/
*.tfstate*
*.tfplan
__pycache__/
*.pyc
.env
build/
*.zip
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root '.env.example' @'
AWS_REGION=us-east-1
ENVIRONMENT=dev
LOG_LEVEL=INFO
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'README.md' @'
# AWS Serverless Media Processing Pipeline

Event-driven capstone for learning API Gateway, Lambda, SQS, dead-letter queues, DynamoDB idempotency, S3 events, least-privilege IAM, alarms, and infrastructure as code.

```mermaid
flowchart LR
    Client --> HTTP["API Gateway HTTP API"] --> Intake["Intake Lambda"]
    Intake --> Jobs[("DynamoDB job ledger")]
    Intake --> Queue["SQS work queue"]
    Queue --> Worker["Worker Lambda"]
    Worker --> Media[("S3 media bucket")]
    Worker --> Jobs
    Queue --> DLQ["SQS dead-letter queue"]
    Alarms["CloudWatch alarms"] --> Operator
```

## What this project teaches

- At-least-once delivery, idempotent consumers, duplicate messages, visibility timeouts, partial batch failure, and poison-message isolation.
- Lambda time/memory/concurrency controls, structured logs, correlation IDs, and cost-aware serverless operations.
- Terraform as the deployment authority and AWS SAM for local validation/invocation.
- IAM scoped by action and resource; encrypted S3, SQS, DynamoDB, and log retention.

## Validate locally

```bash
python -m unittest discover -s tests -v
sam validate --lint
sam build
sam local invoke IntakeFunction -e events/intake-api.json
terraform -chdir=terraform init -backend=false
terraform -chdir=terraform validate
```

The local SAM invoke needs Docker and AWS-compatible test credentials only if the function reaches AWS services. Unit tests use fakes and do not need an AWS account.

## Deploy safely

```bash
terraform -chdir=terraform init
terraform -chdir=terraform plan -out=reviewed.tfplan
terraform -chdir=terraform apply reviewed.tfplan
```

Configure encrypted, versioned, locked remote state before team use. Review account, region, IAM, quotas, public API exposure, log/data retention, KMS strategy, cost alarms, and the exact plan. Destroying the stack can remove queues and job records; production data lifecycles require explicit retention and recovery decisions.

See `docs/HLD.md`, `docs/LLD.md`, `docs/RUNBOOK.md`, and `docs/THREAT-MODEL.md`.
'@ -WhatIfMode:$WhatIfMode

Write-TemplateFile $root 'functions/intake/app.py' @'
import hashlib,json,os,time,uuid

def validate(payload):
    if not isinstance(payload,dict):raise ValueError("INVALID_BODY")
    bucket=str(payload.get("bucket","")).strip();key=str(payload.get("key","")).strip()
    if not 3<=len(bucket)<=63:raise ValueError("INVALID_BUCKET")
    if not key or len(key)>1024 or key.startswith("/") or ".." in key.split("/"):raise ValueError("INVALID_KEY")
    return {"bucket":bucket,"key":key}

def job_id(idempotency_key):return hashlib.sha256(idempotency_key.encode()).hexdigest()[:32]

def accept(payload,idempotency_key,ledger,queue,now=None):
    if not idempotency_key or len(idempotency_key)>128:raise ValueError("IDEMPOTENCY_KEY_REQUIRED")
    media=validate(payload);identifier=job_id(idempotency_key);created=int(now or time.time());job={"jobId":identifier,"status":"queued","bucket":media["bucket"],"key":media["key"],"createdAt":created,"updatedAt":created}
    ledger.put_if_absent(job);queue.send({"jobId":identifier,"bucket":media["bucket"],"key":media["key"],"correlationId":str(uuid.uuid4())})
    return ledger.get(identifier)

class AwsLedger:
    def __init__(self,table):self.table=table
    def put_if_absent(self,item):
        try:self.table.put_item(Item=item,ConditionExpression="attribute_not_exists(jobId)");return True
        except self.table.meta.client.exceptions.ConditionalCheckFailedException:return False
    def get(self,identifier):return self.table.get_item(Key={"jobId":identifier},ConsistentRead=True)["Item"]
class AwsQueue:
    def __init__(self,queue):self.queue=queue
    def send(self,item):
        request={"MessageBody":json.dumps(item)}
        if self.queue.url.endswith(".fifo"):request["MessageGroupId"]="media"
        self.queue.send_message(**request)

def handler(event,context):
    import boto3
    request_id=(event.get("requestContext")or{}).get("requestId") or getattr(context,"aws_request_id",str(uuid.uuid4()))
    try:
        body=json.loads(event.get("body")or"{}") if isinstance(event.get("body"),str) else event.get("body",{});key=(event.get("headers")or{}).get("idempotency-key") or (event.get("headers")or{}).get("Idempotency-Key")
        dynamo=boto3.resource("dynamodb").Table(os.environ["JOBS_TABLE"]);queue=boto3.resource("sqs").Queue(os.environ["QUEUE_URL"]);result=accept(body,key,AwsLedger(dynamo),AwsQueue(queue));return response(202,result,request_id)
    except (ValueError,json.JSONDecodeError) as error:return response(422,{"code":str(error)},request_id)
    except Exception as error:
        print(json.dumps({"level":"error","requestId":request_id,"message":str(error)}));return response(500,{"code":"INTERNAL_ERROR"},request_id)
def response(status,body,request_id):return{"statusCode":status,"headers":{"content-type":"application/json","x-request-id":request_id},"body":json.dumps(body)}
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'functions/worker/app.py' @'
import json,os,time

def process(message,media,ledger,now=None):
    required={"jobId","bucket","key"}
    if not required.issubset(message):raise ValueError("INVALID_MESSAGE")
    updated=int(now or time.time())
    if not ledger.claim(message["jobId"],updated):return
    try:
        metadata=media.inspect(message["bucket"],message["key"]);ledger.complete(message["jobId"],{"contentType":metadata.get("ContentType","application/octet-stream"),"size":int(metadata.get("ContentLength",0)),"etag":str(metadata.get("ETag","")).strip('"'),"updatedAt":int(now or time.time())})
    except Exception:
        ledger.fail(message["jobId"],int(time.time()));raise

class AwsMedia:
    def __init__(self,client):self.client=client
    def inspect(self,bucket,key):return self.client.head_object(Bucket=bucket,Key=key)
class AwsLedger:
    def __init__(self,table):self.table=table
    def claim(self,identifier,updated):
        try:self.table.update_item(Key={"jobId":identifier},UpdateExpression="SET #s=:processing,updatedAt=:updated",ConditionExpression="#s IN (:queued,:failed)",ExpressionAttributeNames={"#s":"status"},ExpressionAttributeValues={":processing":"processing",":queued":"queued",":failed":"failed",":updated":updated});return True
        except self.table.meta.client.exceptions.ConditionalCheckFailedException:return False
    def fail(self,identifier,updated):self.table.update_item(Key={"jobId":identifier},UpdateExpression="SET #s=:failed,updatedAt=:updated",ExpressionAttributeNames={"#s":"status"},ExpressionAttributeValues={":failed":"failed",":updated":updated})
    def complete(self,identifier,metadata):self.table.update_item(Key={"jobId":identifier},UpdateExpression="SET #s=:status,metadata=:metadata,updatedAt=:updated",ExpressionAttributeNames={"#s":"status"},ExpressionAttributeValues={":status":"completed",":metadata":metadata,":updated":metadata["updatedAt"]})

def handler(event,context):
    import boto3
    media=AwsMedia(boto3.client("s3"));ledger=AwsLedger(boto3.resource("dynamodb").Table(os.environ["JOBS_TABLE"]));failures=[]
    for record in event.get("Records",[]):
        try:process(json.loads(record["body"]),media,ledger)
        except Exception as error:
            print(json.dumps({"level":"error","messageId":record.get("messageId"),"message":str(error)}));failures.append({"itemIdentifier":record.get("messageId","")})
    return{"batchItemFailures":failures}
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'tests/test_pipeline.py' @'
import os,sys,unittest
sys.path.insert(0,os.path.join(os.path.dirname(__file__),"..","functions","intake"));import app as intake
sys.path.pop(0);sys.modules.pop("app",None);sys.path.insert(0,os.path.join(os.path.dirname(__file__),"..","functions","worker"));import app as worker
class Ledger:
    def __init__(self):self.data={}
    def put_if_absent(self,item):
        if item["jobId"] in self.data:return False
        self.data[item["jobId"]]=item;return True
    def get(self,key):return self.data[key]
    def claim(self,key,updated):
        if self.data[key]["status"] not in {"queued","failed"}:return False
        self.data[key].update(status="processing",updatedAt=updated);return True
    def fail(self,key,updated):self.data[key].update(status="failed",updatedAt=updated)
    def complete(self,key,metadata):self.data[key].update(status="completed",metadata=metadata)
class Queue:
    def __init__(self):self.messages=[]
    def send(self,item):self.messages.append(item)
class Media:
    def inspect(self,bucket,key):return{"ContentType":"image/png","ContentLength":42,"ETag":"abc"}
class PipelineTests(unittest.TestCase):
    def test_duplicate_intake_is_stable_and_retry_safe(self):
        ledger,queue=Ledger(),Queue();first=intake.accept({"bucket":"media-dev","key":"uploads/a.png"},"same",ledger,queue,1);second=intake.accept({"bucket":"media-dev","key":"uploads/a.png"},"same",ledger,queue,2);self.assertEqual(first["jobId"],second["jobId"]);self.assertEqual(2,len(queue.messages))
    def test_worker_completes_job(self):
        ledger,queue=Ledger(),Queue();job=intake.accept({"bucket":"media-dev","key":"uploads/a.png"},"key",ledger,queue,1);worker.process(queue.messages[0],Media(),ledger,2);self.assertEqual("completed",ledger.data[job["jobId"]]["status"])
    def test_path_traversal_is_rejected(self):
        with self.assertRaisesRegex(ValueError,"INVALID_KEY"):intake.validate({"bucket":"media-dev","key":"../secret"})
if __name__=="__main__":unittest.main()
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'events/intake-api.json' @'
{"version":"2.0","routeKey":"POST /jobs","headers":{"content-type":"application/json","idempotency-key":"demo-job-001"},"requestContext":{"requestId":"local-request"},"body":"{\"bucket\":\"replace-media-dev\",\"key\":\"uploads/demo.png\"}"}
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'events/worker-sqs.json' @'
{"Records":[{"messageId":"demo-message","body":"{\"jobId\":\"demo-job\",\"bucket\":\"replace-media-dev\",\"key\":\"uploads/demo.png\",\"correlationId\":\"local\"}"}]}
'@ -WhatIfMode:$WhatIfMode

Write-TemplateFile $root 'template.yaml' @'
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Local-development SAM model; Terraform is the deployment authority.
Globals:
  Function: { Runtime: python3.12, Architectures: [arm64], Timeout: 15, MemorySize: 256, Tracing: Active, Environment: { Variables: { JOBS_TABLE: !Ref JobsTable, QUEUE_URL: !Ref WorkQueue } } }
Resources:
  Api: { Type: AWS::Serverless::HttpApi, Properties: { StageName: dev } }
  IntakeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/intake
      Handler: app.handler
      Policies: [{ DynamoDBCrudPolicy: { TableName: !Ref JobsTable } }, { SQSSendMessagePolicy: { QueueName: !GetAtt WorkQueue.QueueName } }]
      Events: { Submit: { Type: HttpApi, Properties: { ApiId: !Ref Api, Path: /jobs, Method: POST } } }
  WorkerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/worker
      Handler: app.handler
      Timeout: 30
      Policies: [{ DynamoDBCrudPolicy: { TableName: !Ref JobsTable } }, { S3ReadPolicy: { BucketName: !Ref MediaBucket } }]
      Events: { Work: { Type: SQS, Properties: { Queue: !GetAtt WorkQueue.Arn, BatchSize: 10, FunctionResponseTypes: [ReportBatchItemFailures] } } }
  JobsTable: { Type: AWS::Serverless::SimpleTable, Properties: { PrimaryKey: { Name: jobId, Type: String }, SSESpecification: { SSEEnabled: true } } }
  DeadLetterQueue: { Type: AWS::SQS::Queue, Properties: { SqsManagedSseEnabled: true, MessageRetentionPeriod: 1209600 } }
  WorkQueue: { Type: AWS::SQS::Queue, Properties: { SqsManagedSseEnabled: true, VisibilityTimeout: 180, RedrivePolicy: { deadLetterTargetArn: !GetAtt DeadLetterQueue.Arn, maxReceiveCount: 5 } } }
  MediaBucket: { Type: AWS::S3::Bucket, Properties: { PublicAccessBlockConfiguration: { BlockPublicAcls: true, BlockPublicPolicy: true, IgnorePublicAcls: true, RestrictPublicBuckets: true }, BucketEncryption: { ServerSideEncryptionConfiguration: [{ ServerSideEncryptionByDefault: { SSEAlgorithm: AES256 } }] } } }
'@ -WhatIfMode:$WhatIfMode

Write-TemplateFile $root 'terraform/versions.tf' @'
terraform {
  required_version = ">= 1.7.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 6.0"
    }
    archive = {
      source  = "hashicorp/archive"
      version = "~> 2.7"
    }
  }
  # Configure an encrypted, versioned, locked S3 backend before team use.
}

provider "aws" {
  region = var.aws_region
  default_tags { tags = local.tags }
}
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'terraform/variables.tf' @'
variable "project_name" {
  type    = string
  default = "media-pipeline"
}

variable "environment" {
  type    = string
  default = "dev"
  validation {
    condition     = contains(["dev", "qa", "prod"], var.environment)
    error_message = "Use dev, qa, or prod."
  }
}

variable "aws_region" {
  type    = string
  default = "us-east-1"
}

variable "log_retention_days" {
  type    = number
  default = 30
}

variable "tags" {
  type    = map(string)
  default = { Owner = "replace-with-owner", CostCenter = "replace-with-cost-center" }
}
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'terraform/main.tf' @'
locals {
  name = "${var.project_name}-${var.environment}"
  tags = merge(var.tags, {
    Project     = var.project_name
    Environment = var.environment
    ManagedBy   = "terraform"
  })
}

data "archive_file" "intake" {
  type        = "zip"
  source_dir  = "${path.module}/../functions/intake"
  output_path = "${path.module}/intake.zip"
}

data "archive_file" "worker" {
  type        = "zip"
  source_dir  = "${path.module}/../functions/worker"
  output_path = "${path.module}/worker.zip"
}

resource "aws_s3_bucket" "media" {
  bucket_prefix = "${local.name}-media-"
  force_destroy = var.environment != "prod"
}

resource "aws_s3_bucket_public_access_block" "media" {
  bucket                  = aws_s3_bucket.media.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_server_side_encryption_configuration" "media" {
  bucket = aws_s3_bucket.media.id
  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

resource "aws_s3_bucket_versioning" "media" {
  bucket = aws_s3_bucket.media.id
  versioning_configuration { status = "Enabled" }
}

resource "aws_dynamodb_table" "jobs" {
  name         = "${local.name}-jobs"
  billing_mode = "PAY_PER_REQUEST"
  hash_key     = "jobId"
  attribute {
    name = "jobId"
    type = "S"
  }
  point_in_time_recovery { enabled = true }
  server_side_encryption { enabled = true }
}

resource "aws_sqs_queue" "dlq" {
  name                      = "${local.name}-dlq"
  sqs_managed_sse_enabled   = true
  message_retention_seconds = 1209600
}

resource "aws_sqs_queue" "work" {
  name                       = "${local.name}-work"
  sqs_managed_sse_enabled    = true
  visibility_timeout_seconds = 180
  redrive_policy = jsonencode({
    deadLetterTargetArn = aws_sqs_queue.dlq.arn
    maxReceiveCount     = 5
  })
}

resource "aws_iam_role" "lambda" {
  name = "${local.name}-lambda"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect    = "Allow"
      Principal = { Service = "lambda.amazonaws.com" }
      Action    = "sts:AssumeRole"
    }]
  })
}

resource "aws_iam_role_policy" "lambda" {
  role = aws_iam_role.lambda.id
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect   = "Allow"
        Action   = ["logs:CreateLogStream", "logs:PutLogEvents"]
        Resource = ["${aws_cloudwatch_log_group.intake.arn}:*", "${aws_cloudwatch_log_group.worker.arn}:*"]
      },
      {
        Effect   = "Allow"
        Action   = ["dynamodb:GetItem", "dynamodb:PutItem", "dynamodb:UpdateItem"]
        Resource = aws_dynamodb_table.jobs.arn
      },
      {
        Effect   = "Allow"
        Action   = ["sqs:SendMessage", "sqs:ReceiveMessage", "sqs:DeleteMessage", "sqs:GetQueueAttributes", "sqs:ChangeMessageVisibility"]
        Resource = aws_sqs_queue.work.arn
      },
      {
        Effect   = "Allow"
        Action   = "s3:GetObject"
        Resource = "${aws_s3_bucket.media.arn}/*"
      },
      {
        Effect   = "Allow"
        Action   = ["xray:PutTraceSegments", "xray:PutTelemetryRecords"]
        Resource = "*"
      }
    ]
  })
}

resource "aws_cloudwatch_log_group" "intake" {
  name              = "/aws/lambda/${local.name}-intake"
  retention_in_days = var.log_retention_days
}

resource "aws_cloudwatch_log_group" "worker" {
  name              = "/aws/lambda/${local.name}-worker"
  retention_in_days = var.log_retention_days
}

resource "aws_lambda_function" "intake" {
  function_name    = "${local.name}-intake"
  role             = aws_iam_role.lambda.arn
  runtime          = "python3.12"
  architectures    = ["arm64"]
  handler          = "app.handler"
  filename         = data.archive_file.intake.output_path
  source_code_hash = data.archive_file.intake.output_base64sha256
  timeout          = 15
  memory_size      = 256
  tracing_config { mode = "Active" }
  environment {
    variables = {
      JOBS_TABLE = aws_dynamodb_table.jobs.name
      QUEUE_URL  = aws_sqs_queue.work.url
    }
  }
  depends_on = [aws_iam_role_policy.lambda, aws_cloudwatch_log_group.intake]
}

resource "aws_lambda_function" "worker" {
  function_name                  = "${local.name}-worker"
  role                           = aws_iam_role.lambda.arn
  runtime                        = "python3.12"
  architectures                  = ["arm64"]
  handler                        = "app.handler"
  filename                       = data.archive_file.worker.output_path
  source_code_hash               = data.archive_file.worker.output_base64sha256
  timeout                        = 30
  memory_size                    = 256
  reserved_concurrent_executions = 20
  tracing_config { mode = "Active" }
  environment { variables = { JOBS_TABLE = aws_dynamodb_table.jobs.name } }
  depends_on = [aws_iam_role_policy.lambda, aws_cloudwatch_log_group.worker]
}

resource "aws_lambda_event_source_mapping" "worker" {
  event_source_arn        = aws_sqs_queue.work.arn
  function_name           = aws_lambda_function.worker.arn
  batch_size              = 10
  function_response_types = ["ReportBatchItemFailures"]
  scaling_config { maximum_concurrency = 20 }
}

resource "aws_apigatewayv2_api" "api" {
  name          = local.name
  protocol_type = "HTTP"
}

resource "aws_apigatewayv2_integration" "intake" {
  api_id                 = aws_apigatewayv2_api.api.id
  integration_type       = "AWS_PROXY"
  integration_uri        = aws_lambda_function.intake.invoke_arn
  payload_format_version = "2.0"
}

resource "aws_apigatewayv2_route" "jobs" {
  api_id    = aws_apigatewayv2_api.api.id
  route_key = "POST /jobs"
  target    = "integrations/${aws_apigatewayv2_integration.intake.id}"
}

resource "aws_apigatewayv2_stage" "default" {
  api_id      = aws_apigatewayv2_api.api.id
  name        = "$default"
  auto_deploy = true
  default_route_settings {
    throttling_burst_limit = 100
    throttling_rate_limit  = 50
  }
}

resource "aws_lambda_permission" "api" {
  statement_id  = "AllowApiGateway"
  action        = "lambda:InvokeFunction"
  function_name = aws_lambda_function.intake.function_name
  principal     = "apigateway.amazonaws.com"
  source_arn    = "${aws_apigatewayv2_api.api.execution_arn}/*/*"
}

resource "aws_cloudwatch_metric_alarm" "dlq" {
  alarm_name          = "${local.name}-dlq-not-empty"
  comparison_operator = "GreaterThanThreshold"
  evaluation_periods  = 1
  metric_name         = "ApproximateNumberOfMessagesVisible"
  namespace           = "AWS/SQS"
  period              = 300
  statistic           = "Maximum"
  threshold           = 0
  treat_missing_data  = "notBreaching"
  dimensions          = { QueueName = aws_sqs_queue.dlq.name }
}
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'terraform/outputs.tf' @'
output "api_endpoint" {
  value = aws_apigatewayv2_api.api.api_endpoint
}
output "media_bucket" {
  value = aws_s3_bucket.media.id
}
output "jobs_table" {
  value = aws_dynamodb_table.jobs.name
}
output "work_queue_url" {
  value = aws_sqs_queue.work.url
}
output "dead_letter_queue_url" {
  value = aws_sqs_queue.dlq.url
}
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'terraform/terraform.tfvars.example' @'
project_name = "media-pipeline"
environment  = "dev"
aws_region   = "us-east-1"
log_retention_days = 30
tags = { Owner = "replace-with-owner", CostCenter = "replace-with-cost-center", DataClass = "internal" }
'@ -WhatIfMode:$WhatIfMode

Write-TemplateFile $root 'docs/HLD.md' @'
# Serverless Media Pipeline - HLD

The public journey accepts a bounded media reference and an idempotency key. The intake Lambda conditionally creates one DynamoDB job and emits a retry-safe SQS message. Client retries can produce duplicate messages; a conditional worker claim makes completed or in-flight jobs no-ops. Failed records become retryable again and move to the DLQ after five receives.

Initial objectives are 99.9% successful intake, p95 intake below 500 ms, no duplicate job per idempotency key, RTO 60 minutes, RPO 15 minutes, and bounded cost through API throttling, Lambda reserved concurrency, SQS buffering, payload limits, log retention, and billing alarms. Validate these hypotheses with load, duplicate, retry, poison-message, restore, regional dependency, and quota tests.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/LLD.md' @'
# Serverless Media Pipeline - LLD

- `POST /jobs` requires `Idempotency-Key`, `bucket`, and a relative object `key`.
- A SHA-256-derived job ID plus DynamoDB conditional write makes duplicate intake stable; intake may enqueue duplicates so a queue-send failure can be safely retried.
- The worker conditionally claims only `queued` or `failed` jobs, marks failures retryable, and ignores completed/in-flight duplicates.
- SQS visibility timeout is six times the worker timeout; the event source reports partial batch failures.
- Worker concurrency is bounded at the Lambda and event-source mapping.
- Every state transition updates `updatedAt`; reconciliation can compare queued/processing age with SQS and object state.
- Never log object contents, signed URLs, credentials, or unbounded customer identifiers.

Before production, add authenticated resource authorization, input ownership proof, a job-status read route, schema versioning, TTL/retention policy, KMS keys where required, alarms wired to an owned destination, dashboards, canary deployment, and end-to-end tracing propagation.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/RUNBOOK.md' @'
# Serverless Media Pipeline - Runbook

1. Capture region, UTC start, API symptom, request ID, job ID, object reference, and recent deployment.
2. Check API 4xx/5xx/latency, intake errors/throttles, queue age/depth, worker errors/throttles/duration, DLQ depth, DynamoDB throttles, and S3 access failures.
3. Stop or throttle intake if backlog growth threatens the recovery window. Do not blindly redrive poison messages.
4. Inspect one failed message without exposing sensitive object data; fix code, IAM, schema, quota, or object state.
5. Deploy a reversible function version, test one quarantined message, then redrive a bounded batch while watching age/error/concurrency.

Rollback cannot undo external side effects or incompatible job schemas. Keep old consumers compatible during message retention and reconcile jobs stuck in queued or processing states.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/THREAT-MODEL.md' @'
# Serverless Media Pipeline - Threat Model

Protect API identity, object references and contents, job records, queue messages, logs, IAM roles, artifacts, and Terraform state. Test broken object authorization, forged bucket/key, injection, oversized bodies, replay, duplicate delivery, queue poisoning, SSRF-like downstream processing, archive bombs, malicious media parsers, secret leakage, excessive concurrency/cost, public bucket policy, and audit tampering. Require authentication and resource authorization before exposing the template beyond an isolated lab.
'@ -WhatIfMode:$WhatIfMode

Write-TemplateFile $root 'scripts/test.sh' @'
#!/usr/bin/env sh
set -eu
python -m unittest discover -s tests -v
python -m py_compile functions/intake/app.py functions/worker/app.py
if command -v sam >/dev/null 2>&1;then sam validate --lint;fi
if command -v terraform >/dev/null 2>&1;then terraform -chdir=terraform fmt -check -recursive;fi
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'scripts/validate.ps1' @'
$ErrorActionPreference='Stop'
$required=@('README.md','template.yaml','functions/intake/app.py','functions/worker/app.py','tests/test_pipeline.py','terraform/main.tf','docs/HLD.md','docs/LLD.md','docs/RUNBOOK.md','docs/THREAT-MODEL.md')
foreach($file in $required){if(-not(Test-Path -LiteralPath $file)){throw "Missing $file"}}
python -m unittest discover -s tests -v
python -m py_compile functions/intake/app.py functions/worker/app.py
if(Get-Command sam -ErrorAction SilentlyContinue){sam validate --lint}
if(Get-Command terraform -ErrorAction SilentlyContinue){terraform -chdir=terraform fmt -check -recursive}
Write-Host 'Serverless project validation passed.'
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root '.github/workflows/ci.yml' @'
name: ci
on: { pull_request: {}, push: { branches: [main] }, workflow_dispatch: {} }
permissions: { contents: read, id-token: write }
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.12' }
      - run: python -m unittest discover -s tests -v
      - run: python -m py_compile functions/intake/app.py functions/worker/app.py
      - uses: hashicorp/setup-terraform@v3
      - run: terraform -chdir=terraform fmt -check -recursive
      - run: terraform -chdir=terraform init -backend=false && terraform -chdir=terraform validate
      - uses: aquasecurity/trivy-action@0.28.0
        with: { scan-type: fs, scan-ref: ., severity: "HIGH,CRITICAL", ignore-unfixed: true, exit-code: '1' }
'@ -WhatIfMode:$WhatIfMode

[pscustomobject]@{Project='11-aws-serverless-media-pipeline';Root=$root;Files=$script:Generated.Count}
