param([switch]$WhatIfMode)
. (Join-Path $PSScriptRoot 'Common.ps1')
$root=Join-Path $script:ProjectsRoot '16-modern-data-platform'

Write-TemplateFile $root '.template-owned' 'Generated by tools/module20-projects. Additional user files are never deleted.' -WhatIfMode:$WhatIfMode
Write-TemplateFile $root '.gitignore' @'
.env
__pycache__/
*.pyc
.pytest_cache/
.terraform/
*.tfstate*
target/
dbt_packages/
logs/
data/curated/*
!data/curated/.gitkeep
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root '.env.example' @'
AIRFLOW_UID=50000
AIRFLOW_FERNET_KEY=bG9jYWwtZGV2ZWxvcG1lbnQtZmVybmV0LWtleS0wMDA=
AIRFLOW_JWT_SECRET=local-development-jwt-secret-change-me
AIRFLOW_API_SECRET_KEY=local-development-api-secret-change-me
POSTGRES_USER=platform
POSTGRES_PASSWORD=local-development-only
POSTGRES_DB=platform
KAFKA_BOOTSTRAP_SERVERS=kafka:9092
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'README.md' @'
# Modern Batch and Streaming Data Platform

An industry-shaped data engineering capstone combining Apache Airflow 3, Apache Spark 4, dbt, Apache Kafka 4, PostgreSQL, data contracts, quality checks, lineage-friendly transformations, CI, Kubernetes batch workloads, and Terraform.

```mermaid
flowchart LR
    Apps["Source applications"] --> Kafka["Kafka order events"]
    Kafka --> Raw["Raw landing zone"]
    Airflow["Airflow orchestration"] --> Validate["Contract validation"]
    Airflow --> Load["PostgreSQL raw tables"]
    Airflow --> dbt["dbt transformations and tests"]
    Raw --> Spark["Spark batch aggregation"]
    Spark --> Curated["Curated Parquet zone"]
    dbt --> Mart["Analytics marts"]
    Mart --> BI["BI and downstream consumers"]
    Curated --> BI
```

## What this project teaches

- Batch versus streaming boundaries, event schemas, replay, idempotent ingestion, Kafka consumer groups, and back-pressure.
- Airflow 3 TaskFlow DAG authoring through the public `airflow.sdk` interface, retries, scheduling, quality gates, and operational ownership.
- Spark transformations, partitioned Parquet outputs, dbt staging/mart layers, source tests, and repeatable backfills.
- Separate local and production concerns: Compose for learning; managed orchestration, object storage, encrypted networks, and catalog services for production.

## Fast start

```bash
cp .env.example .env
docker compose config
docker compose up --build airflow-init
docker compose up --build -d postgres kafka airflow-api airflow-scheduler airflow-dag-processor
# Airflow UI: http://localhost:8095 (admin / local-development-only)
docker compose --profile demo run --rm producer
docker compose --profile batch run --rm spark-batch
docker compose --profile transform run --rm dbt run
docker compose --profile transform run --rm dbt test
```

Run `bash scripts/test.sh` for offline contract/unit checks and configuration validation. Generated Parquet is written below `data/curated/` and is intentionally ignored.

## Production adoption gate

Do not lift the local Compose topology directly into production. Decide the managed Airflow/Kafka/Spark services, schema registry, checkpoint and replay policy, object-store format, catalog, data classification, retention, lineage, encryption, private networking, workload identity, cost model, RPO/RTO, and ownership first. See `docs/HLD.md`, `docs/LLD.md`, `docs/RUNBOOK.md`, and `docs/THREAT-MODEL.md`.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'requirements-airflow.txt' @'
dbt-postgres==1.10.0
jsonschema==4.25.1
psycopg[binary]==3.2.10
confluent-kafka==2.11.1
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'requirements-dev.txt' @'
jsonschema==4.25.1
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'Dockerfile.airflow' @'
FROM apache/airflow:3.3.0-python3.12
COPY requirements-airflow.txt /tmp/requirements-airflow.txt
RUN pip install --no-cache-dir "apache-airflow==3.3.0" -r /tmp/requirements-airflow.txt
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'Dockerfile.spark' @'
FROM eclipse-temurin:17-jre-jammy
RUN apt-get update && apt-get install -y --no-install-recommends python3 python3-pip && rm -rf /var/lib/apt/lists/* && groupadd -g 10001 platform && useradd -u 10001 -g platform --no-create-home platform
RUN pip3 install --no-cache-dir pyspark==4.0.3
WORKDIR /opt/platform
COPY --chown=platform:platform jobs/ jobs/
COPY --chown=platform:platform data/ data/
USER 10001:10001
CMD ["python3","jobs/order_metrics.py"]
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'Dockerfile.producer' @'
FROM python:3.12-slim
RUN groupadd -g 10001 platform && useradd -u 10001 -g platform --no-create-home platform
WORKDIR /opt/platform
RUN pip install --no-cache-dir confluent-kafka==2.11.1 jsonschema==4.25.1
COPY --chown=platform:platform platform_lib/ platform_lib/
COPY --chown=platform:platform producers/ producers/
COPY --chown=platform:platform contracts/ contracts/
COPY --chown=platform:platform data/raw/ data/raw/
USER 10001:10001
CMD ["python","producers/order_producer.py"]
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docker-compose.yml' @'
x-airflow-common: &airflow-common
  build: { context: ., dockerfile: Dockerfile.airflow }
  environment: &airflow-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER:-platform}:${POSTGRES_PASSWORD:-local-development-only}@postgres:5432/${POSTGRES_DB:-platform}
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW_FERNET_KEY:-bG9jYWwtZGV2ZWxvcG1lbnQtZmVybmV0LWtleS0wMDA=}
    AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_USERS: admin:admin
    AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_PASSWORDS_FILE: /opt/airflow/config/simple_auth_manager_passwords.json
    AIRFLOW__API_AUTH__JWT_SECRET: ${AIRFLOW_JWT_SECRET:-local-development-jwt-secret-change-me}
    AIRFLOW__API__SECRET_KEY: ${AIRFLOW_API_SECRET_KEY:-local-development-api-secret-change-me}
    PLATFORM_DATABASE_URL: postgresql://${POSTGRES_USER:-platform}:${POSTGRES_PASSWORD:-local-development-only}@postgres:5432/${POSTGRES_DB:-platform}
    KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS:-kafka:9092}
    DBT_PROFILES_DIR: /opt/platform/dbt
  user: "${AIRFLOW_UID:-50000}:0"
  volumes:
    - ./dags:/opt/airflow/dags:ro
    - ./platform_lib:/opt/platform/platform_lib:ro
    - ./contracts:/opt/platform/contracts:ro
    - ./data:/opt/platform/data
    - ./dbt:/opt/platform/dbt:ro
    - ./config:/opt/airflow/config:ro
    - airflow-logs:/opt/airflow/logs
  depends_on:
    postgres: { condition: service_healthy }
  networks: [control,data]
services:
  postgres:
    image: postgres:16-alpine
    environment: { POSTGRES_USER: "${POSTGRES_USER:-platform}", POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-local-development-only}", POSTGRES_DB: "${POSTGRES_DB:-platform}" }
    volumes: [postgres-data:/var/lib/postgresql/data]
    healthcheck: { test: ["CMD-SHELL","pg_isready -U ${POSTGRES_USER:-platform} -d ${POSTGRES_DB:-platform}"], interval: 5s, timeout: 3s, retries: 30 }
    networks: [data]
  kafka:
    image: apache/kafka:4.0.0
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
    healthcheck: { test: ["CMD-SHELL","/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list >/dev/null"], interval: 10s, timeout: 5s, retries: 30 }
    networks: [data]
  kafka-init:
    image: apache/kafka:4.0.0
    command: ["sh","-c","/opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic order-events.v1 --partitions 3 --replication-factor 1"]
    depends_on: { kafka: { condition: service_healthy } }
    networks: [data]
  airflow-init:
    <<: *airflow-common
    command: ["bash","-c","airflow db migrate"]
    restart: "no"
  airflow-api:
    <<: *airflow-common
    command: api-server
    ports: ["${AIRFLOW_PORT:-8095}:8080"]
    depends_on: { postgres: { condition: service_healthy }, airflow-init: { condition: service_completed_successfully } }
    healthcheck: { test: ["CMD","curl","--fail","http://localhost:8080/api/v2/monitor/health"], interval: 15s, timeout: 5s, retries: 20 }
  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    depends_on: { postgres: { condition: service_healthy }, airflow-init: { condition: service_completed_successfully } }
  airflow-dag-processor:
    <<: *airflow-common
    command: dag-processor
    depends_on: { postgres: { condition: service_healthy }, airflow-init: { condition: service_completed_successfully } }
  producer:
    profiles: [demo]
    build: { context: ., dockerfile: Dockerfile.producer }
    environment: { KAFKA_BOOTSTRAP_SERVERS: "${KAFKA_BOOTSTRAP_SERVERS:-kafka:9092}" }
    depends_on: { kafka-init: { condition: service_completed_successfully } }
    networks: [data]
  spark-batch:
    profiles: [batch]
    build: { context: ., dockerfile: Dockerfile.spark }
    volumes: [./data:/opt/platform/data]
    read_only: true
    tmpfs: [/tmp]
    networks: [data]
  dbt:
    profiles: [transform]
    build: { context: ., dockerfile: Dockerfile.airflow }
    entrypoint: ["dbt"]
    command: ["build","--project-dir","/opt/platform/dbt","--profiles-dir","/opt/platform/dbt","--target-path","/tmp/dbt-target","--log-path","/tmp/dbt-logs"]
    environment: { PLATFORM_DATABASE_HOST: postgres, POSTGRES_USER: "${POSTGRES_USER:-platform}", POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-local-development-only}", POSTGRES_DB: "${POSTGRES_DB:-platform}" }
    volumes: [./dbt:/opt/platform/dbt:ro]
    depends_on: { postgres: { condition: service_healthy } }
    networks: [data]
networks: { control: {}, data: { internal: true } }
volumes: { postgres-data: {}, airflow-logs: {} }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'config/simple_auth_manager_passwords.json' '{"admin":"local-development-only"}' -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'contracts/order-event.schema.json' @'
{"$schema":"https://json-schema.org/draft/2020-12/schema","$id":"https://example.invalid/contracts/order-event.v1.json","title":"OrderEventV1","type":"object","additionalProperties":false,"required":["event_id","event_time","customer_id","country","amount","currency"],"properties":{"event_id":{"type":"string","format":"uuid"},"event_time":{"type":"string","format":"date-time"},"customer_id":{"type":"string","minLength":1,"maxLength":64},"country":{"type":"string","pattern":"^[A-Z]{2}$"},"amount":{"type":"number","exclusiveMinimum":0,"maximum":1000000},"currency":{"type":"string","pattern":"^[A-Z]{3}$"}}}
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'data/raw/orders.jsonl' @'
{"event_id":"8ea0485f-d48a-4f62-85e1-83cd49ccb2e3","event_time":"2026-08-16T08:00:00Z","customer_id":"C-1001","country":"IN","amount":1250.50,"currency":"INR"}
{"event_id":"6d9db4f1-e6a8-42a2-b625-983f4fa53e61","event_time":"2026-08-16T09:15:00Z","customer_id":"C-1002","country":"US","amount":79.99,"currency":"USD"}
{"event_id":"b3de2f67-97c1-452d-b4e7-83323bf22323","event_time":"2026-08-16T10:30:00Z","customer_id":"C-1001","country":"IN","amount":450.00,"currency":"INR"}
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'data/curated/.gitkeep' '' -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'platform_lib/__init__.py' '' -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'platform_lib/contracts.py' @'
import json
from pathlib import Path
from jsonschema import Draft202012Validator, FormatChecker

def load_schema(path):
    return json.loads(Path(path).read_text(encoding="utf-8"))

def iter_events(path):
    with Path(path).open(encoding="utf-8") as stream:
        for line_number, line in enumerate(stream, 1):
            if line.strip():
                yield line_number, json.loads(line)

def validate_file(schema_path, events_path):
    validator = Draft202012Validator(load_schema(schema_path), format_checker=FormatChecker())
    events = []
    for line_number, event in iter_events(events_path):
        errors = sorted(validator.iter_errors(event), key=lambda value: list(value.path))
        if errors:
            raise ValueError(f"line {line_number}: {errors[0].message}")
        events.append(event)
    if not events:
        raise ValueError("event file is empty")
    return events
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'producers/order_producer.py' @'
import json, os
from confluent_kafka import Producer
from platform_lib.contracts import validate_file

schema = "/opt/platform/contracts/order-event.schema.json"
source = "/opt/platform/data/raw/orders.jsonl"
events = validate_file(schema, source)
producer = Producer({"bootstrap.servers": os.getenv("KAFKA_BOOTSTRAP_SERVERS", "kafka:9092"), "enable.idempotence": True, "acks": "all"})
for event in events:
    producer.produce("order-events.v1", key=event["customer_id"], value=json.dumps(event).encode())
remaining = producer.flush(15)
if remaining:
    raise RuntimeError(f"{remaining} messages were not delivered")
print(json.dumps({"published": len(events), "topic": "order-events.v1"}))
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'jobs/order_metrics.py' @'
from pyspark.sql import SparkSession, functions as F, types as T

spark = SparkSession.builder.appName("daily-order-metrics").master("local[*]").getOrCreate()
schema = T.StructType([
    T.StructField("event_id", T.StringType(), False),
    T.StructField("event_time", T.TimestampType(), False),
    T.StructField("customer_id", T.StringType(), False),
    T.StructField("country", T.StringType(), False),
    T.StructField("amount", T.DecimalType(18, 2), False),
    T.StructField("currency", T.StringType(), False),
])
orders = spark.read.schema(schema).json("/opt/platform/data/raw/orders.jsonl")
valid = orders.filter(F.col("event_id").isNotNull() & (F.col("amount") > 0)).dropDuplicates(["event_id"])
metrics = valid.withColumn("event_date", F.to_date("event_time")).groupBy("event_date", "country", "currency").agg(F.count("*").alias("order_count"), F.sum("amount").alias("gross_amount"))
if metrics.count() == 0:
    raise RuntimeError("quality gate failed: no valid order metrics")
metrics.write.mode("overwrite").partitionBy("event_date").parquet("/opt/platform/data/curated/daily-order-metrics")
spark.stop()
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'dags/order_analytics.py' @'
from datetime import datetime, timezone
import json, os, subprocess
from airflow.sdk import dag, task

@dag(dag_id="order_analytics_v1", schedule="@daily", start_date=datetime(2026, 1, 1, tzinfo=timezone.utc), catchup=False, max_active_runs=1, tags=["orders", "data-product"])
def order_analytics():
    @task(retries=2)
    def validate_contract():
        import sys
        sys.path.insert(0, "/opt/platform")
        from platform_lib.contracts import validate_file
        events = validate_file("/opt/platform/contracts/order-event.schema.json", "/opt/platform/data/raw/orders.jsonl")
        return len(events)

    @task(retries=3)
    def load_raw(expected_count):
        import psycopg
        sys_path = "/opt/platform"
        import sys
        sys.path.insert(0, sys_path)
        from platform_lib.contracts import validate_file
        events = validate_file(f"{sys_path}/contracts/order-event.schema.json", f"{sys_path}/data/raw/orders.jsonl")
        with psycopg.connect(os.environ["PLATFORM_DATABASE_URL"]) as connection:
            connection.execute("CREATE TABLE IF NOT EXISTS raw_orders(event_id uuid PRIMARY KEY,event_time timestamptz NOT NULL,customer_id varchar(64) NOT NULL,country char(2) NOT NULL,amount numeric(18,2) NOT NULL,currency char(3) NOT NULL,ingested_at timestamptz NOT NULL DEFAULT now())")
            for value in events:
                connection.execute("INSERT INTO raw_orders(event_id,event_time,customer_id,country,amount,currency) VALUES(%s,%s,%s,%s,%s,%s) ON CONFLICT(event_id) DO NOTHING", (value["event_id"], value["event_time"], value["customer_id"], value["country"], value["amount"], value["currency"]))
            count = connection.execute("SELECT count(*) FROM raw_orders").fetchone()[0]
        if count < expected_count:
            raise ValueError(f"quality gate failed: expected at least {expected_count}, found {count}")
        return count

    @task(retries=1)
    def transform(raw_count):
        subprocess.run(["dbt", "build", "--project-dir", "/opt/platform/dbt", "--profiles-dir", "/opt/platform/dbt", "--target-path", "/tmp/dbt-target", "--log-path", "/tmp/dbt-logs"], check=True)
        return {"raw_rows": raw_count, "dbt_status": "passed"}

    @task
    def publish_manifest(result):
        print(json.dumps({"data_product": "order_analytics_v1", **result}, sort_keys=True))

    publish_manifest(transform(load_raw(validate_contract())))

order_analytics()
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'dbt/dbt_project.yml' @'
name: order_analytics
version: 1.0.0
config-version: 2
profile: order_analytics
model-paths: [models]
models:
  order_analytics:
    staging: { materialized: view }
    marts: { materialized: table }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'dbt/profiles.yml' @'
order_analytics:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('PLATFORM_DATABASE_HOST', 'postgres') }}"
      user: "{{ env_var('POSTGRES_USER', 'platform') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'local-development-only') }}"
      port: 5432
      dbname: "{{ env_var('POSTGRES_DB', 'platform') }}"
      schema: analytics
      threads: 4
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'dbt/models/sources.yml' @'
version: 2
sources:
  - name: platform
    schema: public
    tables:
      - name: raw_orders
        columns:
          - name: event_id
            tests: [unique, not_null]
          - name: event_time
            tests: [not_null]
models:
  - name: stg_orders
    columns:
      - name: event_id
        tests: [unique, not_null]
  - name: fct_daily_orders
    columns:
      - name: event_date
        tests: [not_null]
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'dbt/models/staging/stg_orders.sql' @'
select event_id,event_time,customer_id,upper(country) as country,amount,upper(currency) as currency,ingested_at
from {{ source('platform','raw_orders') }}
where amount > 0
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'dbt/models/marts/fct_daily_orders.sql' @'
select cast(event_time as date) as event_date,country,currency,count(*) as order_count,sum(amount) as gross_amount
from {{ ref('stg_orders') }}
group by 1,2,3
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'tests/test_contracts.py' @'
import json, tempfile, unittest
from pathlib import Path
from platform_lib.contracts import validate_file

ROOT = Path(__file__).parents[1]
class ContractTests(unittest.TestCase):
    def test_sample_events_satisfy_contract(self):
        values = validate_file(ROOT / "contracts/order-event.schema.json", ROOT / "data/raw/orders.jsonl")
        self.assertEqual(3, len(values))
    def test_negative_amount_is_rejected(self):
        event = {"event_id":"8ea0485f-d48a-4f62-85e1-83cd49ccb2e3","event_time":"2026-08-16T08:00:00Z","customer_id":"C-1","country":"IN","amount":-1,"currency":"INR"}
        with tempfile.TemporaryDirectory() as folder:
            target = Path(folder) / "bad.jsonl"
            target.write_text(json.dumps(event), encoding="utf-8")
            with self.assertRaises(ValueError):
                validate_file(ROOT / "contracts/order-event.schema.json", target)
if __name__ == "__main__": unittest.main()
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'scripts/test.sh' @'
#!/usr/bin/env sh
set -eu
python -m unittest discover -s tests -v
python -m py_compile platform_lib/*.py producers/*.py jobs/*.py dags/*.py
docker compose config --quiet
if command -v terraform >/dev/null 2>&1;then terraform -chdir=terraform fmt -check -recursive;fi
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'scripts/validate.ps1' @'
$ErrorActionPreference='Stop'
$required=@('README.md','docker-compose.yml','dags/order_analytics.py','jobs/order_metrics.py','dbt/dbt_project.yml','contracts/order-event.schema.json','terraform/main.tf','k8s/base/kustomization.yaml')
foreach($file in $required){if(-not(Test-Path -LiteralPath $file)){throw "Missing $file"}}
python -m unittest discover -s tests -v
python -m py_compile platform_lib/*.py producers/*.py jobs/*.py dags/*.py
docker compose config --quiet
Write-Host 'Data platform validation passed.'
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/HLD.md' @'
# High-level design

The platform exposes two ingestion paths: Kafka for continuously arriving `order-events.v1` records and a replayable raw object/file zone for deterministic batch recovery. Airflow owns orchestration and quality gates, Spark owns larger batch computation, dbt owns SQL transformation and tests, PostgreSQL represents the local warehouse, and the contract is the boundary between producers and consumers.

Production should replace local components with approved managed equivalents, private endpoints, workload identity, centralized secrets, TLS, multi-AZ storage, a schema registry, an object catalog, lineage, and immutable observability. Raw data is append-only; curated tables and Parquet partitions are reproducible from raw events.

## SLO examples

- 99% of daily order marts complete by 06:00 in the business timezone.
- 99.9% of accepted events land in the raw zone within 10 minutes.
- Zero silently discarded contract violations; rejected records enter a quarantined, owned workflow.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/LLD.md' @'
# Low-level design

`contracts/order-event.schema.json` is versioned and rejects unknown fields. The producer enables Kafka idempotence and keys records by customer. The Airflow DAG validates the input, upserts by `event_id`, checks row counts, executes `dbt build`, and emits a data-product manifest. Spark supplies a separate partitioned Parquet path to practice distributed backfills. dbt separates source declarations, staging normalization, mart aggregation, and tests.

Retries are bounded. Database writes are idempotent. A backfill must use an isolated Airflow run, immutable source interval, bounded Spark resources, and comparison queries before promoting output. Never edit a published contract incompatibly; add a new topic/schema version and migrate consumers.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/RUNBOOK.md' @'
# Operations runbook

## DAG failure

1. Identify the failed task and data interval; pause downstream publishing if correctness is uncertain.
2. Check scheduler and DAG processor health, task logs, database saturation, Kafka lag, and source availability.
3. Quarantine invalid records. Do not weaken a contract to make a retry pass.
4. Retry only idempotent tasks. For a backfill, record the source interval, code version, output location, and validation queries.

## Kafka lag or poison events

Throttle producers or scale consumers after confirming partition balance. Preserve the offending offset and payload in a restricted quarantine store, redact it from tickets/logs, then replay through a new consumer group after the fix.

## Recovery

Restore metadata and warehouse databases into isolation, verify checksums and row counts, replay raw events into a new output prefix/schema, compare quality metrics, then switch consumers. Record actual RPO/RTO and follow-up actions.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/THREAT-MODEL.md' @'
# Threat model

Protected assets include customer identifiers, order values, Kafka credentials, orchestration metadata, warehouse data, object-store history, logs, and infrastructure state.

Primary threats are schema abuse, oversized events, sensitive-data leakage, topic or bucket over-permission, DAG code execution, dependency compromise, cross-tenant data access, replay storms, poisoned records, public dashboards, and destructive backfills.

Controls include strict versioned contracts, payload and rate limits, TLS/SASL in production, private networking, least-privilege workload identities, encrypted storage, secrets managers, signed/scanned images, protected DAG delivery, immutable raw retention, audit logs, isolated quarantine, bounded retries, egress restrictions, and restore drills. The local credentials and plaintext Kafka listener are development-only.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'k8s/base/namespace.yaml' @'
apiVersion: v1
kind: Namespace
metadata: { name: data-platform }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'k8s/base/pvc.yaml' @'
apiVersion: v1
kind: PersistentVolumeClaim
metadata: { name: data-lake, namespace: data-platform }
spec:
  accessModes: [ReadWriteOnce]
  resources: { requests: { storage: 20Gi } }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'k8s/base/spark-cronjob.yaml' @'
apiVersion: batch/v1
kind: CronJob
metadata: { name: daily-order-metrics, namespace: data-platform }
spec:
  schedule: "30 1 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 2
      ttlSecondsAfterFinished: 86400
      template:
        metadata: { labels: { app.kubernetes.io/name: daily-order-metrics } }
        spec:
          automountServiceAccountToken: false
          restartPolicy: Never
          securityContext: { runAsNonRoot: true, runAsUser: 10001, fsGroup: 10001, seccompProfile: { type: RuntimeDefault } }
          containers:
            - name: spark
              image: ghcr.io/replace-me/modern-data-platform-spark:replace-with-digest
              imagePullPolicy: IfNotPresent
              securityContext: { allowPrivilegeEscalation: false, readOnlyRootFilesystem: true, capabilities: { drop: [ALL] } }
              resources: { requests: { cpu: 500m, memory: 1Gi }, limits: { cpu: "2", memory: 4Gi } }
              volumeMounts:
                - { name: lake, mountPath: /opt/platform/data }
                - { name: tmp, mountPath: /tmp }
          volumes:
            - { name: lake, persistentVolumeClaim: { claimName: data-lake } }
            - { name: tmp, emptyDir: {} }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'k8s/base/network-policy.yaml' @'
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata: { name: default-deny, namespace: data-platform }
spec: { podSelector: {}, policyTypes: [Ingress, Egress] }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'k8s/base/kustomization.yaml' @'
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [namespace.yaml,pvc.yaml,spark-cronjob.yaml,network-policy.yaml]
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'terraform/versions.tf' @'
terraform {
  required_version = ">= 1.8.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 5.80, < 7.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.7"
    }
  }
}
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'terraform/variables.tf' @'
variable "project_name" {
  type    = string
  default = "modern-data-platform"
}
variable "environment" {
  type    = string
  default = "dev"
}
variable "aws_region" {
  type    = string
  default = "us-east-1"
}
variable "force_destroy" {
  type    = bool
  default = false
}
variable "tags" {
  type    = map(string)
  default = {}
}
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'terraform/main.tf' @'
provider "aws" {
  region = var.aws_region
  default_tags {
    tags = merge(var.tags, { Project = var.project_name, Environment = var.environment, ManagedBy = "Terraform" })
  }
}
resource "random_id" "suffix" {
  byte_length = 4
}
locals {
  bucket_name = lower("${var.project_name}-${var.environment}-${random_id.suffix.hex}")
}
resource "aws_kms_key" "data" {
  description             = "Data lake encryption key"
  enable_key_rotation     = true
  deletion_window_in_days = 30
}
resource "aws_s3_bucket" "lake" {
  bucket        = local.bucket_name
  force_destroy = var.force_destroy
}
resource "aws_s3_bucket_public_access_block" "lake" {
  bucket                  = aws_s3_bucket.lake.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}
resource "aws_s3_bucket_versioning" "lake" {
  bucket = aws_s3_bucket.lake.id
  versioning_configuration {
    status = "Enabled"
  }
}
resource "aws_s3_bucket_server_side_encryption_configuration" "lake" {
  bucket = aws_s3_bucket.lake.id
  rule {
    apply_server_side_encryption_by_default {
      kms_master_key_id = aws_kms_key.data.arn
      sse_algorithm     = "aws:kms"
    }
    bucket_key_enabled = true
  }
}
resource "aws_s3_bucket_lifecycle_configuration" "lake" {
  bucket = aws_s3_bucket.lake.id
  rule {
    id     = "noncurrent-retention"
    status = "Enabled"
    filter {}
    noncurrent_version_expiration {
      noncurrent_days = 90
    }
  }
}
resource "aws_glue_catalog_database" "analytics" {
  name = replace("${var.project_name}_${var.environment}", "-", "_")
}
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'terraform/outputs.tf' @'
output "data_lake_bucket" {
  value = aws_s3_bucket.lake.id
}
output "catalog_database" {
  value = aws_glue_catalog_database.analytics.name
}
output "kms_key_arn" {
  value = aws_kms_key.data.arn
}
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'terraform/terraform.tfvars.example' @'
project_name = "modern-data-platform"
environment  = "dev"
aws_region   = "us-east-1"
force_destroy = false
tags = { Owner = "replace-with-owner", CostCenter = "replace-with-cost-center", DataClass = "confidential" }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root '.github/workflows/ci.yml' @'
name: data-platform-ci
on: { pull_request: {}, push: { branches: [main] }, workflow_dispatch: {} }
permissions: { contents: read }
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12", cache: pip }
      - run: pip install -r requirements-dev.txt
      - run: python -m unittest discover -s tests -v
      - run: python -m py_compile platform_lib/*.py producers/*.py jobs/*.py dags/*.py
      - run: docker compose config --quiet
      - uses: hashicorp/setup-terraform@v3
      - run: terraform -chdir=terraform fmt -check -recursive
      - run: terraform -chdir=terraform init -backend=false && terraform -chdir=terraform validate
      - uses: aquasecurity/trivy-action@0.28.0
        with: { scan-type: fs, scan-ref: ., severity: "HIGH,CRITICAL", ignore-unfixed: true, exit-code: "1" }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'Jenkinsfile' @'
pipeline { agent any; options { timestamps(); disableConcurrentBuilds() }; stages { stage('Validate') { steps { sh 'python -m pip install -r requirements-dev.txt'; sh 'python -m unittest discover -s tests -v'; sh 'python -m py_compile platform_lib/*.py producers/*.py jobs/*.py dags/*.py'; sh 'docker compose config --quiet'; sh 'terraform -chdir=terraform fmt -check -recursive' } } stage('Security') { steps { sh 'trivy fs --exit-code 1 --severity HIGH,CRITICAL --ignore-unfixed .' } } } }
'@ -WhatIfMode:$WhatIfMode

[pscustomobject]@{Project='16-modern-data-platform';Root=$root;Files=$script:Generated.Count}
