param([switch]$WhatIfMode)
. (Join-Path $PSScriptRoot 'Common.ps1')
$root=Join-Path $script:ProjectsRoot '19-internal-developer-platform'
Write-TemplateFile $root '.template-owned' 'Generated by tools/module20-projects. Additional user files are never deleted.' -WhatIfMode:$WhatIfMode
Write-TemplateFile $root '.gitignore' @'
.env
.terraform/
*.tfstate*
*.tfplan
dist/
node_modules/
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'README.md' @'
# Internal Developer Platform and Golden Path

A platform-engineering capstone built around Backstage 1.49, Crossplane v2, Argo CD, Kyverno, Kubernetes, GitHub Actions, and Terraform. The project is intentionally a control-plane reference implementation rather than another business API.

```mermaid
flowchart LR
    Developer --> Backstage["Backstage catalog and template"]
    Backstage --> Repo["New service repository"]
    Repo --> CI["Build, test, sign, publish"]
    Repo --> Argo["Argo CD ApplicationSet"]
    Argo --> Cluster["Kubernetes runtime"]
    Developer --> XR["Crossplane App resource"]
    XR --> Composition["Function pipeline composition"]
    Composition --> Cluster
    Kyverno["Admission policy"] --> Cluster
```

## What to build and demonstrate

1. Register the sample domain, system, component, owner, and API in Backstage.
2. Run the `production-service` template and create a repository containing source, CI, catalog metadata, Kubernetes resources, and an Argo CD application.
3. Install Crossplane v2 and apply the `App` XRD/composition. Create an `App` and inspect composed Deployment and Service resources.
4. Prove the Kyverno policy rejects privileged, unbounded, mutable-tag workloads.
5. Measure lead time, deployment frequency, change-failure rate, developer wait time, and golden-path adoption.

This repository stores overlays and platform contracts; bootstrap an actual Backstage application with the official create-app tool, then merge `backstage/app-config.yaml` and mount `catalog/` plus `templates/`. Never enable guest authentication outside local development.

## Validate

```bash
kubectl kustomize .
kubectl apply --dry-run=client -f crossplane/
kubectl apply --dry-run=client -f argocd/
terraform -chdir=terraform init -backend=false
terraform -chdir=terraform validate
```

See `docs/HLD.md`, `docs/LLD.md`, `docs/RUNBOOK.md`, `docs/THREAT-MODEL.md`, and `docs/PLATFORM-SCORECARD.md` before treating this as a production platform.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'backstage/app-config.yaml' @'
app:
  title: Masterclass Developer Platform
  baseUrl: http://localhost:3000
organization: { name: Masterclass Engineering }
backend:
  baseUrl: http://localhost:7007
  listen: { port: 7007, host: 0.0.0.0 }
  auth: { dangerouslyDisableDefaultAuthPolicy: false }
  database:
    client: pg
    connection:
      host: "${POSTGRES_HOST}"
      port: 5432
      user: "${POSTGRES_USER}"
      password: "${POSTGRES_PASSWORD}"
      database: backstage
integrations:
  github:
    - host: github.com
      token: "${GITHUB_TOKEN}"
auth:
  environment: development
  providers:
    guest: { dangerouslyAllowOutsideDevelopment: false }
catalog:
  rules: [{ allow: [Component, System, Domain, Group, User, Resource, API, Template, Location] }]
  locations:
    - { type: file, target: ../../catalog/location.yaml }
    - { type: file, target: ../../templates/service/template.yaml }
scaffolder: { defaultAuthor: { name: Platform Engineering, email: platform@example.invalid }, defaultCommitMessage: "chore: bootstrap from golden path" }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'catalog/location.yaml' @'
apiVersion: backstage.io/v1alpha1
kind: Location
metadata: { name: masterclass-platform-catalog }
spec:
  type: file
  targets: [./organization.yaml,./domain.yaml,./system.yaml,./component.yaml,./api.yaml]
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'catalog/organization.yaml' @'
apiVersion: backstage.io/v1alpha1
kind: Group
metadata: { name: platform-engineering, description: Owners of the internal developer platform }
spec: { type: team, profile: { displayName: Platform Engineering }, children: [] }
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata: { name: platform-admin }
spec: { profile: { displayName: Platform Admin, email: platform@example.invalid }, memberOf: [platform-engineering] }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'catalog/domain.yaml' @'
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata: { name: digital-commerce, description: Customer-facing commerce capabilities }
spec: { owner: platform-engineering }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'catalog/system.yaml' @'
apiVersion: backstage.io/v1alpha1
kind: System
metadata: { name: checkout, description: Checkout and payment orchestration }
spec: { owner: platform-engineering, domain: digital-commerce }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'catalog/component.yaml' @'
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: payment-risk
  annotations: { github.com/project-slug: replace-me/payment-risk, argocd/app-name: payment-risk-prod }
  tags: [rust, kubernetes, tier-1]
  links: [{ url: https://grafana.example.invalid, title: Service dashboard }]
spec: { type: service, lifecycle: production, owner: platform-engineering, system: checkout, providesApis: [payment-risk-api] }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'catalog/api.yaml' @'
apiVersion: backstage.io/v1alpha1
kind: API
metadata: { name: payment-risk-api }
spec:
  type: openapi
  lifecycle: production
  owner: platform-engineering
  system: checkout
  definition: |
    openapi: 3.1.0
    info: { title: Payment Risk API, version: 1.0.0 }
    paths: { /health: { get: { responses: { "200": { description: Ready } } } } }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'templates/service/template.yaml' @'
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata: { name: production-service, title: Production Service Golden Path, description: Secure service repository with GitOps delivery }
spec:
  owner: platform-engineering
  type: service
  parameters:
    - title: Service identity
      required: [name, owner, system, repository]
      properties:
        name: { title: Service name, type: string, pattern: "^[a-z][a-z0-9-]{2,40}$" }
        owner: { title: Owner, type: string, ui:field: OwnerPicker, ui:options: { catalogFilter: { kind: [Group] } } }
        system: { title: System, type: string, ui:field: EntityPicker, ui:options: { catalogFilter: { kind: [System] } } }
        repository: { title: Repository, type: string, ui:field: RepoUrlPicker, ui:options: { allowedHosts: [github.com] } }
        tier: { title: Service tier, type: string, enum: [tier-1,tier-2,tier-3], default: tier-2 }
  steps:
    - id: fetch
      name: Render repository
      action: fetch:template
      input: { url: ./skeleton, values: { name: "${{ parameters.name }}", owner: "${{ parameters.owner }}", system: "${{ parameters.system }}", tier: "${{ parameters.tier }}" } }
    - id: publish
      name: Publish repository
      action: publish:github
      input: { repoUrl: "${{ parameters.repository }}", defaultBranch: main, protectDefaultBranch: true, requireCodeOwnerReviews: true, description: "${{ parameters.name }} generated by the production golden path" }
    - id: register
      name: Register component
      action: catalog:register
      input: { repoContentsUrl: "${{ steps.publish.output.repoContentsUrl }}", catalogInfoPath: /catalog-info.yaml }
  output:
    links:
      - { title: Repository, url: "${{ steps.publish.output.remoteUrl }}" }
      - { title: Catalog entity, icon: catalog, entityRef: "${{ steps.register.output.entityRef }}" }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'templates/service/skeleton/catalog-info.yaml' @'
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  annotations: { github.com/project-slug: "${{ values.name }}", argocd/app-name: "${{ values.name }}-prod" }
  tags: [golden-path, "${{ values.tier }}"]
spec: { type: service, lifecycle: experimental, owner: "${{ values.owner }}", system: "${{ values.system }}" }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'templates/service/skeleton/README.md' @'
# ${{ values.name }}

Generated by the production service golden path. Replace the sample endpoint, define an SLO, complete the threat model, configure workload identity and secrets, then prove rollback and restore before production approval.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'templates/service/skeleton/app/main.py' @'
from fastapi import FastAPI
app=FastAPI(title="${{ values.name }}")
@app.get("/health")
def health():return {"status":"ok","service":"${{ values.name }}"}
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'templates/service/skeleton/app/requirements.txt' @'
fastapi==0.141.1
uvicorn==0.52.3
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'templates/service/skeleton/Dockerfile' @'
FROM python:3.12-slim
RUN groupadd -g 10001 app && useradd -u 10001 -g app --no-create-home app
WORKDIR /app
COPY app/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY --chown=app:app app/ .
USER 10001:10001
EXPOSE 8080
CMD ["uvicorn","main:app","--host","0.0.0.0","--port","8080"]
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'templates/service/skeleton/k8s/deployment.yaml' @'
apiVersion: apps/v1
kind: Deployment
metadata: { name: "${{ values.name }}", labels: { app.kubernetes.io/name: "${{ values.name }}", platform.example.io/tier: "${{ values.tier }}" } }
spec:
  replicas: 2
  selector: { matchLabels: { app.kubernetes.io/name: "${{ values.name }}" } }
  template:
    metadata: { labels: { app.kubernetes.io/name: "${{ values.name }}" } }
    spec:
      serviceAccountName: "${{ values.name }}"
      automountServiceAccountToken: false
      securityContext: { runAsNonRoot: true, runAsUser: 10001, seccompProfile: { type: RuntimeDefault } }
      containers:
        - name: app
          image: ghcr.io/replace-me/${{ values.name }}:replace-with-digest
          ports: [{ name: http, containerPort: 8080 }]
          readinessProbe: { httpGet: { path: /health, port: http }, periodSeconds: 5 }
          livenessProbe: { httpGet: { path: /health, port: http }, initialDelaySeconds: 15 }
          resources: { requests: { cpu: 100m, memory: 128Mi }, limits: { cpu: 500m, memory: 512Mi } }
          securityContext: { allowPrivilegeEscalation: false, readOnlyRootFilesystem: true, capabilities: { drop: [ALL] } }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'templates/service/skeleton/k8s/service.yaml' @'
apiVersion: v1
kind: ServiceAccount
metadata: { name: "${{ values.name }}" }
---
apiVersion: v1
kind: Service
metadata: { name: "${{ values.name }}" }
spec: { selector: { app.kubernetes.io/name: "${{ values.name }}" }, ports: [{ name: http, port: 80, targetPort: http }] }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'templates/service/skeleton/k8s/kustomization.yaml' @'
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [deployment.yaml,service.yaml]
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'crossplane/xrd.yaml' @'
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata: { name: apps.platform.example.io }
spec:
  scope: Namespaced
  group: platform.example.io
  names: { kind: App, plural: apps }
  defaultCompositionRef: { name: app-kubernetes }
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: [image]
              properties:
                image: { type: string, pattern: "^.+@sha256:[a-f0-9]{64}$" }
                port: { type: integer, default: 8080, minimum: 1, maximum: 65535 }
                replicas: { type: integer, default: 2, minimum: 1, maximum: 20 }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'crossplane/function.yaml' @'
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata: { name: function-go-templating }
spec: { package: xpkg.crossplane.io/crossplane-contrib/function-go-templating:v0.11.0 }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'crossplane/composition.yaml' @'
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata: { name: app-kubernetes }
spec:
  compositeTypeRef: { apiVersion: platform.example.io/v1alpha1, kind: App }
  mode: Pipeline
  pipeline:
    - step: render-resources
      functionRef: { name: function-go-templating }
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            apiVersion: apps/v1
            kind: Deployment
            metadata:
              annotations: { gotemplating.fn.crossplane.io/composition-resource-name: deployment }
              name: {{ .observed.composite.resource.metadata.name }}
              namespace: {{ .observed.composite.resource.metadata.namespace }}
            spec:
              replicas: {{ .observed.composite.resource.spec.replicas }}
              selector: { matchLabels: { app: {{ .observed.composite.resource.metadata.name }} } }
              template:
                metadata: { labels: { app: {{ .observed.composite.resource.metadata.name }} } }
                spec:
                  automountServiceAccountToken: false
                  securityContext: { runAsNonRoot: true, runAsUser: 10001, seccompProfile: { type: RuntimeDefault } }
                  containers:
                    - name: app
                      image: {{ .observed.composite.resource.spec.image }}
                      ports: [{ containerPort: {{ .observed.composite.resource.spec.port }} }]
                      resources: { requests: { cpu: 100m, memory: 128Mi }, limits: { cpu: 500m, memory: 512Mi } }
                      securityContext: { allowPrivilegeEscalation: false, readOnlyRootFilesystem: true, capabilities: { drop: [ALL] } }
            ---
            apiVersion: v1
            kind: Service
            metadata:
              annotations: { gotemplating.fn.crossplane.io/composition-resource-name: service }
              name: {{ .observed.composite.resource.metadata.name }}
              namespace: {{ .observed.composite.resource.metadata.namespace }}
            spec:
              selector: { app: {{ .observed.composite.resource.metadata.name }} }
              ports: [{ port: 80, targetPort: {{ .observed.composite.resource.spec.port }} }]
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'crossplane/example-app.yaml' @'
apiVersion: platform.example.io/v1alpha1
kind: App
metadata: { name: example-service, namespace: team-example }
spec: { image: ghcr.io/replace-me/example-service@sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, port: 8080, replicas: 2 }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'argocd/project.yaml' @'
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata: { name: workloads, namespace: argocd }
spec:
  sourceRepos: [https://github.com/replace-me/platform-environments.git]
  destinations: [{ namespace: "team-*", server: https://kubernetes.default.svc }]
  clusterResourceWhitelist: []
  namespaceResourceBlacklist: [{ group: "", kind: ResourceQuota }]
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'argocd/applicationset.yaml' @'
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata: { name: workload-environments, namespace: argocd }
spec:
  goTemplate: true
  generators:
    - git: { repoURL: https://github.com/replace-me/platform-environments.git, revision: main, directories: [{ path: environments/* }] }
  template:
    metadata: { name: "{{.path.basename}}" }
    spec:
      project: workloads
      source: { repoURL: https://github.com/replace-me/platform-environments.git, targetRevision: main, path: "{{.path.path}}" }
      destination: { server: https://kubernetes.default.svc, namespace: "{{.path.basename}}" }
      syncPolicy: { automated: { prune: true, selfHeal: true }, syncOptions: [CreateNamespace=true] }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'platform/namespace.yaml' @'
apiVersion: v1
kind: Namespace
metadata: { name: platform-system, labels: { pod-security.kubernetes.io/enforce: restricted } }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'platform/policy.yaml' @'
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata: { name: golden-path-baseline }
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: require-platform-controls
      match: { any: [{ resources: { kinds: [Pod], namespaces: ["team-*"] } }] }
      validate:
        message: Workloads require non-root, resource limits, and immutable images.
        pattern:
          spec:
            securityContext: { runAsNonRoot: true }
            containers:
              - resources: { requests: { cpu: "?*", memory: "?*" }, limits: { cpu: "?*", memory: "?*" } }
                image: "*@sha256:*"
                securityContext: { allowPrivilegeEscalation: false, readOnlyRootFilesystem: true }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'kustomization.yaml' @'
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [platform/namespace.yaml,platform/policy.yaml,crossplane/xrd.yaml,crossplane/function.yaml,crossplane/composition.yaml,argocd/project.yaml,argocd/applicationset.yaml]
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'kind/cluster.yaml' @'
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes: [{ role: control-plane },{ role: worker },{ role: worker }]
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'terraform/versions.tf' @'
terraform {
  required_version = ">= 1.8.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 6.0"
    }
  }
}
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'terraform/variables.tf' @'
variable "project_name" {
  type    = string
  default = "internal-developer-platform"
}
variable "environment" {
  type    = string
  default = "dev"
}
variable "aws_region" {
  type    = string
  default = "us-east-1"
}
variable "vpc_cidr" {
  type    = string
  default = "10.70.0.0/16"
}
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'terraform/main.tf' @'
provider "aws" {
  region = var.aws_region
}
data "aws_availability_zones" "available" { state = "available" }
locals {
  name = "${var.project_name}-${var.environment}"
}
module "vpc" {
  source             = "terraform-aws-modules/vpc/aws"
  version            = "~> 6.0"
  name               = local.name
  cidr               = var.vpc_cidr
  azs                = slice(data.aws_availability_zones.available.names, 0, 3)
  private_subnets    = [for i in range(3) : cidrsubnet(var.vpc_cidr, 4, i)]
  public_subnets     = [for i in range(3) : cidrsubnet(var.vpc_cidr, 8, i + 48)]
  enable_nat_gateway = true
  single_nat_gateway = var.environment != "prod"
}
module "eks" {
  source                                   = "terraform-aws-modules/eks/aws"
  version                                  = "~> 21.0"
  name                                     = local.name
  kubernetes_version                       = "1.36"
  endpoint_public_access                   = false
  enable_cluster_creator_admin_permissions = true
  deletion_protection                      = var.environment == "prod"
  vpc_id                                   = module.vpc.vpc_id
  subnet_ids                               = module.vpc.private_subnets
  eks_managed_node_groups = {
    platform = {
      instance_types = ["m7i.large"]
      min_size       = 2
      max_size       = 6
      desired_size   = 3
    }
  }
}
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'terraform/outputs.tf' @'
output "cluster_name" {
  value = module.eks.cluster_name
}
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/HLD.md' @'
# High-level design

The platform separates developer experience, control planes, and workload runtime. Backstage owns discovery and golden-path intent; source control owns desired state and review history; CI owns artifact evidence; Argo CD owns reconciliation; Crossplane owns higher-level platform APIs; Kyverno enforces admission controls. No portal action bypasses Git review or workload identity.

The production design requires HA control planes, private clusters, SSO, managed PostgreSQL, encrypted state, signed artifacts, policy exceptions with expiry, tenant quotas, audit export, backup/restore, and an explicit platform SLO.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/LLD.md' @'
# Low-level design

The Backstage template validates ownership, system, repository, and tier, then renders a minimal service repository. Crossplane exposes a namespaced `App` API and uses a function pipeline to create Kubernetes resources. Argo CD discovers environment directories and reconciles them with prune and self-heal. Kyverno checks immutable image references, non-root execution, read-only filesystems, and resource requests/limits.

Platform APIs are versioned products. Breaking schema changes require a new served version, conversion/migration plan, compatibility tests, and consumer communication.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/RUNBOOK.md' @'
# Platform runbook

For failed scaffolding, preserve the task ID, redact secrets, determine the failed action, and retry only idempotent steps. For Argo drift, inspect desired Git revision, sync waves, health, admission events, and controller logs before forcing synchronization. For Crossplane failures, inspect XR conditions, function pipeline results, composed-resource events, and provider rate limits.

Disable only the affected template or composition during an incident. Never disable global admission controls to unblock one team. Restore control-plane metadata into isolation, validate catalog ownership and desired-state checksums, then reconnect reconcilers gradually.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/THREAT-MODEL.md' @'
# Threat model

Threats include malicious templates, source URL injection, repository-token theft, confused-deputy access, over-privileged Crossplane providers, GitOps repository compromise, unsafe policy exceptions, secret exposure in catalog annotations, and untrusted TechDocs content.

Controls include SSO, short-lived workload identity, allowlisted template actions and source hosts, protected branches, CODEOWNERS, signed commits/images, isolated runners, least-privilege AppProjects/providers, admission policies, network policy, audit logs, secret scanning, dependency review, and time-bounded exception records.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/PLATFORM-SCORECARD.md' @'
# Platform scorecard

Measure golden-path adoption, time to first production deployment, developer wait time, successful scaffold rate, deployment frequency, change-failure rate, restore-test age, ownership completeness, SLO coverage, immutable-image adoption, policy exception count/age, and platform availability. Review usability with product teams; a platform with no voluntary adoption is not successful.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'scripts/validate.ps1' @'
$ErrorActionPreference='Stop'
$required=@('backstage/app-config.yaml','catalog/location.yaml','templates/service/template.yaml','crossplane/xrd.yaml','crossplane/composition.yaml','argocd/applicationset.yaml','kustomization.yaml','terraform/main.tf')
foreach($file in $required){if(-not(Test-Path -LiteralPath $file)){throw "Missing $file"}}
kubectl kustomize . | Out-Null
if(Get-Command terraform -ErrorAction SilentlyContinue){terraform -chdir=terraform fmt -check -recursive}
Write-Host 'Internal developer platform validation passed.'
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root '.github/workflows/ci.yml' @'
name: platform-contracts
on: { pull_request: {}, push: { branches: [main] }, workflow_dispatch: {} }
permissions: { contents: read }
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: kubectl kustomize . >/tmp/platform.yaml
      - uses: hashicorp/setup-terraform@v3
      - run: terraform -chdir=terraform fmt -check -recursive
      - run: terraform -chdir=terraform init -backend=false && terraform -chdir=terraform validate
      - uses: stackrox/kube-linter-action@v1
        with: { directory: templates/service/skeleton/k8s }
'@ -WhatIfMode:$WhatIfMode
[pscustomobject]@{Project='19-internal-developer-platform';Root=$root;Files=$script:Generated.Count}
