param([switch]$WhatIfMode)
. (Join-Path $PSScriptRoot 'Common.ps1')
$root=Join-Path $script:ProjectsRoot '20-opentelemetry-observability-platform'
Write-TemplateFile $root '.template-owned' 'Generated by tools/module20-projects. Additional user files are never deleted.' -WhatIfMode:$WhatIfMode
Write-TemplateFile $root '.gitignore' @'
.env
__pycache__/
*.pyc
.terraform/
*.tfstate*
data/
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root '.env.example' @'
GRAFANA_ADMIN_PASSWORD=local-development-only
OTEL_SAMPLE_RATIO=1.0
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'README.md' @'
# OpenTelemetry Observability and SRE Platform

A runnable three-pillar observability capstone using OpenTelemetry Collector 0.157, Prometheus 3.12, Loki 3.7, Tempo 2.10, Grafana 13.1, and an instrumented FastAPI checkout service.

```mermaid
flowchart LR
    User --> App["Instrumented checkout service"]
    App -->|OTLP traces metrics logs| Collector["OpenTelemetry Collector"]
    Collector --> Prometheus["Prometheus metrics"]
    Collector --> Tempo["Tempo traces"]
    Collector --> Loki["Loki logs"]
    Prometheus --> Grafana["Grafana"]
    Tempo --> Grafana
    Loki --> Grafana
    Prometheus --> Alerts["SLO burn-rate alerts"]
```

## Run the lab

```bash
cp .env.example .env
docker compose config
docker compose up --build -d
curl http://localhost:8099/health
curl -X POST http://localhost:8099/api/checkout -H 'content-type: application/json' -d '{"cartId":"CART-1001","items":3,"total":149.90}'
```

- Checkout API: `http://localhost:8099`
- Prometheus: `http://localhost:8100`
- Grafana: `http://localhost:8101` (`admin` and the configured password)

Generate both successful and failed requests with `python scripts/load.py`. In Grafana, move from RED metrics to an exemplar/trace and then to correlated logs. Trigger the burn-rate alert, write an incident timeline, and calculate error-budget consumption.

The Compose topology is a learning environment. Production requires HA collectors, authenticated OTLP, tenant isolation, object storage, retention controls, cardinality budgets, sampling policy, PII filtering, query limits, backups, and cost ownership. See the HLD, LLD, runbook, threat model, and telemetry-governance document.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'app/requirements.txt' @'
fastapi==0.141.1
uvicorn==0.52.3
opentelemetry-api==1.44.0
opentelemetry-sdk==1.44.0
opentelemetry-exporter-otlp-proto-http==1.44.0
opentelemetry-instrumentation-fastapi==0.65b0
opentelemetry-instrumentation-logging==0.65b0
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'app/domain.py' @'
from dataclasses import dataclass
@dataclass(frozen=True)
class Checkout: cart_id:str;items:int;total:float
def parse_checkout(value):
    cart_id=str(value.get("cartId","")).strip().upper();items=value.get("items");total=value.get("total")
    if not 4<=len(cart_id)<=64:raise ValueError("INVALID_CART")
    if not isinstance(items,int) or not 1<=items<=100:raise ValueError("INVALID_ITEMS")
    if not isinstance(total,(int,float)) or not 0<float(total)<=1_000_000:raise ValueError("INVALID_TOTAL")
    return Checkout(cart_id,items,float(total))
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'app/main.py' @'
import logging,os,time
from fastapi import FastAPI,HTTPException,Request
from opentelemetry import metrics,trace
from opentelemetry.exporter.otlp.proto.http._log_exporter import OTLPLogExporter
from opentelemetry.exporter.otlp.proto.http.metric_exporter import OTLPMetricExporter
from opentelemetry.exporter.otlp.proto.http.trace_exporter import OTLPSpanExporter
from opentelemetry.instrumentation.fastapi import FastAPIInstrumentor
from opentelemetry.instrumentation.logging import LoggingInstrumentor
from opentelemetry.sdk._logs import LoggerProvider,LoggingHandler
from opentelemetry.sdk._logs.export import BatchLogRecordProcessor
from opentelemetry.sdk.metrics import MeterProvider
from opentelemetry.sdk.metrics.export import PeriodicExportingMetricReader
from opentelemetry.sdk.resources import Resource
from opentelemetry.sdk.trace import TracerProvider
from opentelemetry.sdk.trace.export import BatchSpanProcessor
from opentelemetry.sdk.trace.sampling import ParentBased,TraceIdRatioBased
from domain import parse_checkout

endpoint=os.getenv("OTEL_EXPORTER_OTLP_ENDPOINT","http://otel-collector:4318");resource=Resource.create({"service.name":"checkout-observability","service.version":"0.1.0","deployment.environment":os.getenv("ENVIRONMENT","dev")})
tracer_provider=TracerProvider(resource=resource,sampler=ParentBased(TraceIdRatioBased(float(os.getenv("OTEL_SAMPLE_RATIO","1.0")))));tracer_provider.add_span_processor(BatchSpanProcessor(OTLPSpanExporter(endpoint=f"{endpoint}/v1/traces")));trace.set_tracer_provider(tracer_provider)
meter_provider=MeterProvider(resource=resource,metric_readers=[PeriodicExportingMetricReader(OTLPMetricExporter(endpoint=f"{endpoint}/v1/metrics"),export_interval_millis=5000)]);metrics.set_meter_provider(meter_provider)
logger_provider=LoggerProvider(resource=resource);logger_provider.add_log_record_processor(BatchLogRecordProcessor(OTLPLogExporter(endpoint=f"{endpoint}/v1/logs")));logging.getLogger().addHandler(LoggingHandler(level=logging.INFO,logger_provider=logger_provider));logging.getLogger().setLevel(logging.INFO);LoggingInstrumentor().instrument(set_logging_format=True)
meter=metrics.get_meter("checkout");requests=meter.create_counter("checkout.requests",unit="1");latency=meter.create_histogram("checkout.duration",unit="ms");logger=logging.getLogger("checkout");app=FastAPI(title="Observable Checkout")
@app.middleware("http")
async def measure(request:Request,call_next):
    started=time.perf_counter();status=500
    try:response=await call_next(request);status=response.status_code;return response
    finally:requests.add(1,{"http.route":request.url.path,"http.status_code":status});latency.record((time.perf_counter()-started)*1000,{"http.route":request.url.path})
@app.get("/health")
def health():return {"status":"ok","service":"checkout-observability"}
@app.post("/api/checkout")
def checkout(payload:dict,simulateFailure:bool=False):
    try:value=parse_checkout(payload)
    except ValueError as error:raise HTTPException(422,detail={"code":str(error)})
    span=trace.get_current_span();span.set_attribute("checkout.cart_id",value.cart_id);span.set_attribute("checkout.items",value.items)
    if simulateFailure:logger.error("checkout dependency failed",extra={"cart_id":value.cart_id});raise HTTPException(503,detail={"code":"PAYMENT_UNAVAILABLE"})
    logger.info("checkout accepted",extra={"cart_id":value.cart_id,"items":value.items});return {"cartId":value.cart_id,"status":"accepted","total":value.total}
FastAPIInstrumentor.instrument_app(app)
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'app/test_domain.py' @'
import unittest
from domain import parse_checkout
class CheckoutTests(unittest.TestCase):
 def test_normalizes(self):self.assertEqual("CART-1",parse_checkout({"cartId":" cart-1 ","items":2,"total":10}).cart_id)
 def test_rejects_empty_cart(self):
  with self.assertRaisesRegex(ValueError,"INVALID_CART"):parse_checkout({"cartId":"","items":2,"total":10})
if __name__=="__main__":unittest.main()
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'app/Dockerfile' @'
FROM python:3.12-slim
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1
RUN groupadd -g 10001 app && useradd -u 10001 -g app --no-create-home app
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY --chown=app:app . .
USER 10001:10001
EXPOSE 8080
CMD ["uvicorn","main:app","--host","0.0.0.0","--port","8080","--workers","2"]
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'otel/collector.yaml' @'
extensions:
  health_check: { endpoint: 0.0.0.0:13133 }
receivers:
  otlp:
    protocols:
      grpc: { endpoint: 0.0.0.0:4317 }
      http: { endpoint: 0.0.0.0:4318 }
processors:
  memory_limiter: { check_interval: 1s, limit_mib: 256, spike_limit_mib: 64 }
  batch: { send_batch_size: 1024, timeout: 5s }
  attributes/redact:
    actions:
      - { key: enduser.email, action: delete }
      - { key: http.request.header.authorization, action: delete }
exporters:
  prometheus: { endpoint: 0.0.0.0:8889, enable_open_metrics: true }
  otlp/tempo: { endpoint: tempo:4317, tls: { insecure: true } }
  otlphttp/loki: { endpoint: http://loki:3100/otlp }
service:
  extensions: [health_check]
  pipelines:
    traces: { receivers: [otlp], processors: [memory_limiter,attributes/redact,batch], exporters: [otlp/tempo] }
    metrics: { receivers: [otlp], processors: [memory_limiter,batch], exporters: [prometheus] }
    logs: { receivers: [otlp], processors: [memory_limiter,attributes/redact,batch], exporters: [otlphttp/loki] }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'prometheus/prometheus.yml' @'
global: { scrape_interval: 5s, evaluation_interval: 15s }
rule_files: [/etc/prometheus/rules.yml]
scrape_configs:
  - job_name: prometheus
    static_configs: [{ targets: [localhost:9090] }]
  - job_name: otel-collector
    static_configs: [{ targets: [otel-collector:8889] }]
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'prometheus/rules.yml' @'
groups:
  - name: checkout-slo
    rules:
      - record: checkout:requests:rate5m
        expr: sum(rate(checkout_requests_total[5m]))
      - record: checkout:errors:ratio5m
        expr: sum(rate(checkout_requests_total{http_status_code=~"5.."}[5m])) / clamp_min(sum(rate(checkout_requests_total[5m])), 0.001)
      - alert: CheckoutErrorBudgetFastBurn
        expr: checkout:errors:ratio5m > (14.4 * 0.01)
        for: 5m
        labels: { severity: page, service: checkout-observability }
        annotations: { summary: Checkout is rapidly consuming its 99% availability error budget, runbook_url: https://example.invalid/runbooks/checkout }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'loki/loki.yaml' @'
auth_enabled: false
server: { http_listen_port: 3100 }
common:
  path_prefix: /loki
  storage: { filesystem: { chunks_directory: /loki/chunks, rules_directory: /loki/rules } }
  replication_factor: 1
  ring: { kvstore: { store: inmemory } }
schema_config:
  configs:
    - { from: "2024-01-01", store: tsdb, object_store: filesystem, schema: v13, index: { prefix: index_, period: 24h } }
limits_config: { allow_structured_metadata: true, retention_period: 168h }
compactor: { working_directory: /loki/compactor, retention_enabled: true, delete_request_store: filesystem }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'tempo/tempo.yaml' @'
server: { http_listen_port: 3200 }
distributor:
  receivers:
    otlp:
      protocols:
        grpc: { endpoint: 0.0.0.0:4317 }
        http: { endpoint: 0.0.0.0:4318 }
storage:
  trace: { backend: local, wal: { path: /var/tempo/wal }, local: { path: /var/tempo/blocks } }
metrics_generator: { registry: { external_labels: { source: tempo } }, storage: { path: /var/tempo/generator/wal } }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'grafana/provisioning/datasources/datasources.yaml' @'
apiVersion: 1
datasources:
  - { name: Prometheus, uid: prometheus, type: prometheus, access: proxy, url: http://prometheus:9090, isDefault: true }
  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    jsonData: { tracesToLogsV2: { datasourceUid: loki, spanStartTimeShift: -5m, spanEndTimeShift: 5m }, serviceMap: { datasourceUid: prometheus } }
  - { name: Loki, uid: loki, type: loki, access: proxy, url: http://loki:3100 }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'grafana/provisioning/dashboards/provider.yaml' @'
apiVersion: 1
providers: [{ name: sre, folder: SRE, type: file, disableDeletion: true, updateIntervalSeconds: 30, options: { path: /var/lib/grafana/dashboards } }]
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'grafana/dashboards/checkout.json' @'
{"annotations":{"list":[]},"editable":true,"panels":[{"type":"stat","title":"Request rate","datasource":{"type":"prometheus","uid":"prometheus"},"targets":[{"expr":"sum(rate(checkout_requests_total[5m]))"}],"gridPos":{"h":8,"w":8,"x":0,"y":0}},{"type":"timeseries","title":"Error ratio","datasource":{"type":"prometheus","uid":"prometheus"},"targets":[{"expr":"checkout:errors:ratio5m"}],"gridPos":{"h":8,"w":8,"x":8,"y":0}},{"type":"logs","title":"Checkout logs","datasource":{"type":"loki","uid":"loki"},"targets":[{"expr":"{service_name=\"checkout-observability\"}"}],"gridPos":{"h":8,"w":8,"x":16,"y":0}}],"refresh":"10s","schemaVersion":41,"tags":["sre","otel"],"templating":{"list":[]},"time":{"from":"now-1h","to":"now"},"title":"Checkout RED and Correlation","uid":"checkout-sre","version":1}
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docker-compose.yml' @'
services:
  app:
    build: app
    image: ${REGISTRY:-local}/20-opentelemetry-observability-platform-app:${IMAGE_TAG:-dev}
    environment: { OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318, OTEL_SAMPLE_RATIO: "${OTEL_SAMPLE_RATIO:-1.0}", ENVIRONMENT: local }
    ports: ["${APP_PORT:-8099}:8080"]
    depends_on: [otel-collector]
    read_only: true
    tmpfs: [/tmp]
    security_opt: [no-new-privileges:true]
    networks: [telemetry]
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.157.0
    command: ["--config=/etc/otelcol/config.yaml"]
    volumes: [./otel/collector.yaml:/etc/otelcol/config.yaml:ro]
    networks: [telemetry]
  prometheus:
    image: prom/prometheus:v3.12.0
    command: ["--config.file=/etc/prometheus/prometheus.yml","--storage.tsdb.retention.time=7d"]
    volumes: [./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro,./prometheus/rules.yml:/etc/prometheus/rules.yml:ro,prometheus-data:/prometheus]
    ports: ["${PROMETHEUS_PORT:-8100}:9090"]
    networks: [telemetry]
  tempo:
    image: grafana/tempo:2.10.0
    command: ["-config.file=/etc/tempo.yaml"]
    volumes: [./tempo/tempo.yaml:/etc/tempo.yaml:ro,tempo-data:/var/tempo]
    networks: [telemetry]
  loki:
    image: grafana/loki:3.7.3
    command: ["-config.file=/etc/loki/local-config.yaml"]
    volumes: [./loki/loki.yaml:/etc/loki/local-config.yaml:ro,loki-data:/loki]
    networks: [telemetry]
  grafana:
    image: grafana/grafana:13.1.0
    environment: { GF_SECURITY_ADMIN_PASSWORD: "${GRAFANA_ADMIN_PASSWORD:-local-development-only}", GF_USERS_ALLOW_SIGN_UP: "false" }
    volumes: [./grafana/provisioning:/etc/grafana/provisioning:ro,./grafana/dashboards:/var/lib/grafana/dashboards:ro,grafana-data:/var/lib/grafana]
    ports: ["${GRAFANA_PORT:-8101}:3000"]
    depends_on: [prometheus,tempo,loki]
    networks: [telemetry]
networks: { telemetry: {} }
volumes: { prometheus-data: {}, tempo-data: {}, loki-data: {}, grafana-data: {} }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'scripts/load.py' @'
import json,random,time,urllib.error,urllib.request
url="http://localhost:8099/api/checkout"
for index in range(200):
 payload=json.dumps({"cartId":f"CART-{index:04d}","items":random.randint(1,8),"total":round(random.uniform(5,500),2)}).encode();target=url+("?simulateFailure=true" if random.random()<0.08 else "")
 request=urllib.request.Request(target,data=payload,headers={"content-type":"application/json"},method="POST")
 try:urllib.request.urlopen(request,timeout=3).read()
 except urllib.error.HTTPError:pass
 time.sleep(.05)
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'scripts/test.sh' @'
#!/usr/bin/env sh
set -eu
cd app
python -m unittest test_domain.py -v
python -m py_compile main.py domain.py
cd ..
docker compose config --quiet
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'k8s/base/namespace.yaml' @'
apiVersion: v1
kind: Namespace
metadata: { name: observability, labels: { pod-security.kubernetes.io/enforce: restricted } }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'k8s/base/collector.yaml' @'
apiVersion: v1
kind: ConfigMap
metadata: { name: otel-collector, namespace: observability }
data:
  collector.yaml: |
    receivers: { otlp: { protocols: { grpc: { endpoint: 0.0.0.0:4317 }, http: { endpoint: 0.0.0.0:4318 } } } }
    processors: { memory_limiter: { check_interval: 1s, limit_mib: 384 }, batch: {} }
    exporters: { debug: { verbosity: basic } }
    service: { pipelines: { traces: { receivers: [otlp], processors: [memory_limiter,batch], exporters: [debug] }, metrics: { receivers: [otlp], processors: [memory_limiter,batch], exporters: [debug] }, logs: { receivers: [otlp], processors: [memory_limiter,batch], exporters: [debug] } } }
---
apiVersion: apps/v1
kind: Deployment
metadata: { name: otel-collector, namespace: observability }
spec:
  replicas: 2
  selector: { matchLabels: { app: otel-collector } }
  template:
    metadata: { labels: { app: otel-collector } }
    spec:
      automountServiceAccountToken: false
      securityContext: { runAsNonRoot: true, runAsUser: 10001, seccompProfile: { type: RuntimeDefault } }
      containers:
        - name: collector
          image: otel/opentelemetry-collector-contrib:0.157.0
          args: ["--config=/conf/collector.yaml"]
          ports: [{ name: otlp-grpc, containerPort: 4317 },{ name: otlp-http, containerPort: 4318 }]
          resources: { requests: { cpu: 200m, memory: 256Mi }, limits: { cpu: "1", memory: 512Mi } }
          securityContext: { allowPrivilegeEscalation: false, readOnlyRootFilesystem: true, capabilities: { drop: [ALL] } }
          volumeMounts: [{ name: config, mountPath: /conf, readOnly: true }]
      volumes: [{ name: config, configMap: { name: otel-collector } }]
---
apiVersion: v1
kind: Service
metadata: { name: otel-collector, namespace: observability }
spec: { selector: { app: otel-collector }, ports: [{ name: otlp-grpc, port: 4317 },{ name: otlp-http, port: 4318 }] }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'k8s/base/kustomization.yaml' @'
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [namespace.yaml,collector.yaml]
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'helm/kube-prometheus-stack-values.yaml' @'
grafana: { enabled: false }
prometheus: { prometheusSpec: { retention: 15d, replicas: 2, resources: { requests: { cpu: 500m, memory: 2Gi }, limits: { cpu: "2", memory: 4Gi } } } }
alertmanager: { alertmanagerSpec: { replicas: 3 } }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'helm/otel-collector-values.yaml' @'
mode: deployment
replicaCount: 3
image: { repository: otel/opentelemetry-collector-contrib, tag: 0.157.0 }
resources: { requests: { cpu: 300m, memory: 512Mi }, limits: { cpu: "2", memory: 1Gi } }
autoscaling: { enabled: true, minReplicas: 3, maxReplicas: 12, targetCPUUtilizationPercentage: 70 }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'terraform/versions.tf' @'
terraform {
  required_version = ">= 1.8.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 6.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.7"
    }
  }
}
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'terraform/main.tf' @'
provider "aws" {
  region = var.aws_region
}
resource "random_id" "suffix" {
  byte_length = 4
}
resource "aws_kms_key" "telemetry" {
  description             = "Telemetry object encryption"
  enable_key_rotation     = true
  deletion_window_in_days = 30
}
resource "aws_s3_bucket" "telemetry" {
  bucket        = "${var.project_name}-${var.environment}-${random_id.suffix.hex}"
  force_destroy = false
}
resource "aws_s3_bucket_public_access_block" "telemetry" {
  bucket                  = aws_s3_bucket.telemetry.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}
resource "aws_s3_bucket_server_side_encryption_configuration" "telemetry" {
  bucket = aws_s3_bucket.telemetry.id
  rule {
    apply_server_side_encryption_by_default {
      kms_master_key_id = aws_kms_key.telemetry.arn
      sse_algorithm     = "aws:kms"
    }
    bucket_key_enabled = true
  }
}
resource "aws_s3_bucket_versioning" "telemetry" {
  bucket = aws_s3_bucket.telemetry.id
  versioning_configuration {
    status = "Enabled"
  }
}
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'terraform/variables.tf' @'
variable "project_name" {
  type    = string
  default = "otel-platform"
}
variable "environment" {
  type    = string
  default = "dev"
}
variable "aws_region" {
  type    = string
  default = "us-east-1"
}
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'terraform/outputs.tf' @'
output "telemetry_bucket" {
  value = aws_s3_bucket.telemetry.id
}
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/HLD.md' @'
# High-level design

Applications emit vendor-neutral OTLP to a collector tier. Collectors enforce memory limits, batch traffic, redact sensitive attributes, and route metrics, traces, and logs to specialized backends. Grafana is the investigation surface; Prometheus evaluates SLO rules. Production separates agent/gateway collectors, uses object storage, authenticates every hop, and scales read/write paths independently.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/LLD.md' @'
# Low-level design

The checkout app creates server spans plus bounded route/status metrics and structured logs. The collector removes known sensitive attributes before export. Prometheus records request/error rates and evaluates a fast burn-rate alert. Grafana provisions Prometheus, Tempo, and Loki as code. Resource attributes provide service/environment identity; unbounded cart IDs are trace attributes, never metric labels.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/RUNBOOK.md' @'
# Observability platform runbook

When telemetry is missing, verify application export failures, collector receiver/exporter metrics, queue pressure, backend ingestion, and time synchronization in that order. When cardinality spikes, identify the metric and label source, apply an emergency collector filter, preserve evidence, and fix instrumentation. During backend overload, prioritize paging/SLO signals, reduce debug traffic and trace sampling, and protect ingestion from query workloads.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/THREAT-MODEL.md' @'
# Threat model

Telemetry can contain credentials, customer data, topology, source code fragments, and incident evidence. Threats include unauthenticated ingestion, tenant spoofing, query abuse, cardinality denial of service, malicious dashboard links, log injection, trace baggage leakage, and retention-policy bypass. Use mTLS, workload identity, tenant authorization, attribute allowlists/redaction, quotas, query limits, private networks, immutable dashboards, audit logs, encrypted stores, and deletion workflows.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/TELEMETRY-GOVERNANCE.md' @'
# Telemetry governance

Every signal needs an owner, purpose, classification, retention period, cardinality budget, sampling policy, and deletion path. Prohibit secrets and direct identifiers by default. Prefer stable semantic conventions and low-cardinality dimensions. Review new metrics and high-volume logs like production APIs because they create compatibility and cost commitments.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root '.github/workflows/ci.yml' @'
name: observability-ci
on: { pull_request: {}, push: { branches: [main] }, workflow_dispatch: {} }
permissions: { contents: read }
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - run: cd app && python -m unittest test_domain.py -v && python -m py_compile main.py domain.py
      - run: docker compose config --quiet
      - run: docker run --rm -v "$PWD/prometheus:/etc/prometheus" prom/prometheus:v3.12.0 promtool check config /etc/prometheus/prometheus.yml
      - run: kubectl kustomize k8s/base >/tmp/rendered.yaml
      - uses: hashicorp/setup-terraform@v3
      - run: terraform -chdir=terraform fmt -check -recursive
'@ -WhatIfMode:$WhatIfMode
[pscustomobject]@{Project='20-opentelemetry-observability-platform';Root=$root;Files=$script:Generated.Count}
