param([switch]$WhatIfMode)
. (Join-Path $PSScriptRoot 'Common.ps1')
$root=Join-Path $script:ProjectsRoot '21-mlops-model-delivery-platform'
Write-TemplateFile $root '.template-owned' 'Generated by tools/module20-projects. Additional user files are never deleted.' -WhatIfMode:$WhatIfMode
Write-TemplateFile $root '.gitignore' @'
.env
__pycache__/
*.pyc
.terraform/
*.tfstate*
mlruns/
artifacts/
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root '.env.example' @'
POSTGRES_USER=mlflow
POSTGRES_PASSWORD=local-development-only
POSTGRES_DB=mlflow
MINIO_ROOT_USER=minio
MINIO_ROOT_PASSWORD=local-development-only
MODEL_NAME=fraud-risk
MODEL_ALIAS=champion
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'README.md' @'
# MLOps Model Delivery Platform

A production-shaped model lifecycle capstone using MLflow 3.15, scikit-learn, FastAPI, PostgreSQL, S3-compatible object storage, model aliases, contract tests, observability, and Kubernetes canary analysis.

```mermaid
flowchart LR
    Data["Versioned training data"] --> Trainer["Reproducible trainer"]
    Trainer --> Tracking["MLflow tracking"]
    Trainer --> Registry["Model registry and champion alias"]
    Trainer --> Artifacts["Object storage"]
    Registry --> API["FastAPI inference"]
    Artifacts --> API
    Client --> API
    API --> Metrics["Prediction metrics"]
    Metrics --> Analysis["Argo Rollouts analysis"]
```

## Run locally

```bash
cp .env.example .env
docker compose config
docker compose up --build -d postgres minio minio-init mlflow
docker compose --profile train run --rm trainer
docker compose up --build -d api
curl http://localhost:8102/health
curl -X POST http://localhost:8102/predict -H 'content-type: application/json' -d '{"features":[0.2,-1.1,0.7,1.5]}'
```

- Inference API: `http://localhost:8102`
- MLflow: `http://localhost:8103`
- MinIO console: `http://localhost:8104`

## Required exercises

1. Add dataset version/checksum capture and a feature contract.
2. Add evaluation gates for accuracy, calibration, fairness slices, latency, and artifact vulnerability/provenance.
3. Promote a challenger with a reviewed model card and registry alias change.
4. Deploy through the Argo Rollout, force a canary regression, and prove automatic abort.
5. Simulate drift, retraining, rollback, artifact loss, and registry unavailability.

Synthetic data keeps the example self-contained; it does not make this a real fraud model. Production use requires approved data, privacy/legal review, feature lineage, reproducible environments, bias/safety evaluation, human escalation, monitoring, and a documented rollback authority.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'requirements.txt' @'
mlflow==3.15.1
scikit-learn==1.9.0
pandas==3.0.5
fastapi==0.141.1
uvicorn==0.52.3
prometheus-client==0.26.0
boto3==1.43.72
psycopg2-binary==2.9.11
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'platform_lib/__init__.py' '' -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'platform_lib/domain.py' @'
import math
FEATURE_COUNT=4
def validate_features(values):
    if not isinstance(values,list) or len(values)!=FEATURE_COUNT:raise ValueError("INVALID_FEATURE_COUNT")
    parsed=[]
    for value in values:
        if isinstance(value,bool) or not isinstance(value,(int,float)) or not math.isfinite(float(value)):raise ValueError("INVALID_FEATURE")
        parsed.append(float(value))
    return parsed
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'trainer/train.py' @'
import json,os
import mlflow,mlflow.sklearn,pandas as pd
from mlflow import MlflowClient
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,roc_auc_score
from sklearn.model_selection import train_test_split

tracking=os.getenv("MLFLOW_TRACKING_URI","http://mlflow:5000");name=os.getenv("MODEL_NAME","fraud-risk");alias=os.getenv("MODEL_ALIAS","champion");mlflow.set_tracking_uri(tracking);mlflow.set_experiment("fraud-risk-training")
features,labels=make_classification(n_samples=4000,n_features=4,n_informative=3,n_redundant=1,weights=[.92,.08],random_state=42);features=pd.DataFrame(features,columns=["velocity","amount_zscore","device_risk","account_age_risk"]);x_train,x_test,y_train,y_test=train_test_split(features,labels,test_size=.25,random_state=42,stratify=labels);model=LogisticRegression(max_iter=1000,class_weight="balanced",random_state=42).fit(x_train,y_train);probability=model.predict_proba(x_test)[:,1];prediction=(probability>=.5).astype(int);metrics={"accuracy":accuracy_score(y_test,prediction),"roc_auc":roc_auc_score(y_test,probability)}
if metrics["roc_auc"]<.80:raise RuntimeError(f"quality gate failed: {metrics}")
with mlflow.start_run() as run:
 mlflow.log_params({"algorithm":"logistic-regression","random_state":42,"training_rows":len(x_train),"feature_count":4});mlflow.log_metrics(metrics);mlflow.log_dict({"schema_version":"1","features":["velocity","amount_zscore","device_risk","account_age_risk"]},"feature_contract.json");info=mlflow.sklearn.log_model(sk_model=model,name="model",registered_model_name=name,input_example=x_test[:3])
client=MlflowClient();versions=client.search_model_versions(f"run_id='{run.info.run_id}'");version=max(versions,key=lambda value:int(value.version));client.set_registered_model_alias(name,alias,version.version);client.set_model_version_tag(name,version.version,"validation_status","passed");print(json.dumps({"runId":run.info.run_id,"model":name,"version":version.version,"alias":alias,**metrics},sort_keys=True))
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'api/main.py' @'
import logging,os,time
from contextlib import asynccontextmanager
import mlflow,pandas as pd
from fastapi import FastAPI,HTTPException
from pydantic import BaseModel
from prometheus_client import Counter,Histogram,make_asgi_app
from platform_lib.domain import validate_features

logging.basicConfig(level=os.getenv("LOG_LEVEL","INFO"),format="%(asctime)s %(levelname)s %(message)s");logger=logging.getLogger("inference");model=None;model_uri=lambda:f"models:/{os.getenv('MODEL_NAME','fraud-risk')}@{os.getenv('MODEL_ALIAS','champion')}";predictions=Counter("model_predictions_total","Predictions by result",["result"]);latency=Histogram("model_prediction_seconds","Inference latency")
def load_model():
 global model
 mlflow.set_tracking_uri(os.getenv("MLFLOW_TRACKING_URI","http://mlflow:5000"));model=mlflow.pyfunc.load_model(model_uri());logger.info("model loaded uri=%s",model_uri())
@asynccontextmanager
async def lifespan(_app):
 try:load_model()
 except Exception:logger.exception("model unavailable during startup")
 yield
app=FastAPI(title="Fraud Risk Inference",lifespan=lifespan);app.mount("/metrics",make_asgi_app())
class PredictionRequest(BaseModel):features:list[float]
@app.get("/health")
def health():
 if model is None:raise HTTPException(503,detail={"status":"not_ready","reason":"model_unavailable"})
 return {"status":"ok","service":"fraud-risk-inference","modelUri":model_uri()}
@app.post("/admin/reload")
def reload():load_model();return {"status":"reloaded","modelUri":model_uri()}
@app.post("/predict")
def predict(request:PredictionRequest):
 if model is None:raise HTTPException(503,detail={"code":"MODEL_UNAVAILABLE"})
 try:features=validate_features(request.features)
 except ValueError as error:raise HTTPException(422,detail={"code":str(error)})
 started=time.perf_counter();frame=pd.DataFrame([features],columns=["velocity","amount_zscore","device_risk","account_age_risk"])
 try:result=int(model.predict(frame)[0])
 except Exception as error:logger.exception("prediction failed");raise HTTPException(500,detail={"code":"PREDICTION_FAILED"}) from error
 finally:latency.observe(time.perf_counter()-started)
 label="review" if result else "approve";predictions.labels(result=label).inc();logger.info("prediction completed result=%s",label);return {"decision":label,"modelUri":model_uri()}
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'tests/test_domain.py' @'
import unittest
from platform_lib.domain import validate_features
class FeatureContractTests(unittest.TestCase):
 def test_accepts_four_numbers(self):self.assertEqual([1.0,2.0,3.0,4.0],validate_features([1,2,3,4]))
 def test_rejects_wrong_count(self):
  with self.assertRaisesRegex(ValueError,"INVALID_FEATURE_COUNT"):validate_features([1,2])
 def test_rejects_boolean(self):
  with self.assertRaisesRegex(ValueError,"INVALID_FEATURE"):validate_features([1,2,True,4])
if __name__=="__main__":unittest.main()
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'Dockerfile' @'
FROM python:3.12-slim
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1
RUN groupadd -g 10001 app && useradd -u 10001 -g app --no-create-home app
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY --chown=app:app api/ api/
COPY --chown=app:app trainer/ trainer/
COPY --chown=app:app platform_lib/ platform_lib/
USER 10001:10001
ENV PYTHONPATH=/app
EXPOSE 8080
CMD ["uvicorn","api.main:app","--host","0.0.0.0","--port","8080","--workers","2"]
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'Dockerfile.mlflow' @'
FROM ghcr.io/mlflow/mlflow:v3.15.1
RUN pip install --no-cache-dir psycopg2-binary==2.9.11 boto3==1.43.72
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docker-compose.yml' @'
x-ml-env: &ml-env
  MLFLOW_TRACKING_URI: http://mlflow:5000
  MLFLOW_S3_ENDPOINT_URL: http://minio:9000
  AWS_ACCESS_KEY_ID: ${MINIO_ROOT_USER:-minio}
  AWS_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD:-local-development-only}
  AWS_DEFAULT_REGION: us-east-1
  MODEL_NAME: ${MODEL_NAME:-fraud-risk}
  MODEL_ALIAS: ${MODEL_ALIAS:-champion}
services:
  postgres:
    image: postgres:16-alpine
    environment: { POSTGRES_USER: "${POSTGRES_USER:-mlflow}", POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-local-development-only}", POSTGRES_DB: "${POSTGRES_DB:-mlflow}" }
    volumes: [postgres-data:/var/lib/postgresql/data]
    healthcheck: { test: ["CMD-SHELL","pg_isready -U ${POSTGRES_USER:-mlflow} -d ${POSTGRES_DB:-mlflow}"], interval: 5s, timeout: 3s, retries: 30 }
    networks: [data]
  minio:
    image: quay.io/minio/minio:RELEASE.2025-09-07T16-13-09Z
    command: ["server","/data","--console-address",":9001"]
    environment: { MINIO_ROOT_USER: "${MINIO_ROOT_USER:-minio}", MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD:-local-development-only}" }
    volumes: [minio-data:/data]
    ports: ["${MINIO_CONSOLE_PORT:-8104}:9001"]
    healthcheck: { test: ["CMD","curl","-f","http://localhost:9000/minio/health/live"], interval: 5s, timeout: 3s, retries: 30 }
    networks: [data]
  minio-init:
    image: quay.io/minio/mc:RELEASE.2025-08-13T08-35-41Z
    entrypoint: ["sh","-c"]
    command: ["mc alias set local http://minio:9000 ${MINIO_ROOT_USER:-minio} ${MINIO_ROOT_PASSWORD:-local-development-only} && mc mb --ignore-existing local/mlflow"]
    depends_on: { minio: { condition: service_healthy } }
    networks: [data]
  mlflow:
    build: { context: ., dockerfile: Dockerfile.mlflow }
    command: ["mlflow","server","--backend-store-uri","postgresql+psycopg2://${POSTGRES_USER:-mlflow}:${POSTGRES_PASSWORD:-local-development-only}@postgres:5432/${POSTGRES_DB:-mlflow}","--artifacts-destination","s3://mlflow","--host","0.0.0.0","--port","5000"]
    environment: *ml-env
    ports: ["${MLFLOW_PORT:-8103}:5000"]
    depends_on: { postgres: { condition: service_healthy }, minio-init: { condition: service_completed_successfully } }
    healthcheck: { test: ["CMD","python","-c","import urllib.request; urllib.request.urlopen('http://localhost:5000/health')"], interval: 5s, timeout: 3s, retries: 30 }
    networks: [edge,data]
  trainer:
    profiles: [train]
    build: .
    command: ["python","trainer/train.py"]
    environment: *ml-env
    depends_on: { mlflow: { condition: service_healthy } }
    networks: [data]
  api:
    build: .
    image: ${REGISTRY:-local}/21-mlops-model-delivery-platform-api:${IMAGE_TAG:-dev}
    environment: *ml-env
    ports: ["${API_PORT:-8102}:8080"]
    depends_on: { mlflow: { condition: service_healthy } }
    read_only: true
    tmpfs: [/tmp]
    security_opt: [no-new-privileges:true]
    networks: [edge,data]
networks: { edge: {}, data: { internal: true } }
volumes: { postgres-data: {}, minio-data: {} }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'model-card/model-card.md' @'
# Fraud Risk Model Card

## Intended use and prohibited use

Document the decision supported, affected users, human-review boundary, jurisdictions, and prohibited autonomous actions.

## Data and evaluation

Record immutable dataset references/checksums, feature lineage, temporal split, leakage review, accuracy/calibration, slice metrics, fairness review, robustness, latency, and limitations.

## Approval and operations

Record training run, source commit, artifact digest/signature, approvers, registry version/alias, monitoring thresholds, drift policy, retraining trigger, rollback owner, and retirement date.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'k8s/base/namespace.yaml' @'
apiVersion: v1
kind: Namespace
metadata: { name: ml-platform, labels: { pod-security.kubernetes.io/enforce: restricted } }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'k8s/base/config.yaml' @'
apiVersion: v1
kind: ConfigMap
metadata: { name: inference-config, namespace: ml-platform }
data: { MLFLOW_TRACKING_URI: https://mlflow.example.invalid, MODEL_NAME: fraud-risk, MODEL_ALIAS: champion }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'k8s/base/rollout.yaml' @'
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata: { name: fraud-risk-inference, namespace: ml-platform }
spec:
  replicas: 4
  revisionHistoryLimit: 3
  selector: { matchLabels: { app: fraud-risk-inference } }
  strategy:
    canary:
      stableService: fraud-risk-stable
      canaryService: fraud-risk-canary
      steps:
        - { setWeight: 10 }
        - { pause: { duration: 5m } }
        - analysis: { templates: [{ templateName: inference-success-rate }], args: [{ name: service, value: fraud-risk-canary }] }
        - { setWeight: 50 }
        - { pause: { duration: 10m } }
  template:
    metadata: { labels: { app: fraud-risk-inference } }
    spec:
      serviceAccountName: fraud-risk-inference
      automountServiceAccountToken: false
      securityContext: { runAsNonRoot: true, runAsUser: 10001, seccompProfile: { type: RuntimeDefault } }
      containers:
        - name: api
          image: ghcr.io/replace-me/fraud-risk-inference:replace-with-digest
          envFrom: [{ configMapRef: { name: inference-config } }]
          ports: [{ name: http, containerPort: 8080 }]
          readinessProbe: { httpGet: { path: /health, port: http }, periodSeconds: 5 }
          livenessProbe: { httpGet: { path: /health, port: http }, initialDelaySeconds: 20 }
          resources: { requests: { cpu: 250m, memory: 512Mi }, limits: { cpu: "2", memory: 2Gi } }
          securityContext: { allowPrivilegeEscalation: false, readOnlyRootFilesystem: true, capabilities: { drop: [ALL] } }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'k8s/base/services.yaml' @'
apiVersion: v1
kind: ServiceAccount
metadata: { name: fraud-risk-inference, namespace: ml-platform }
---
apiVersion: v1
kind: Service
metadata: { name: fraud-risk-stable, namespace: ml-platform }
spec: { selector: { app: fraud-risk-inference }, ports: [{ name: http, port: 80, targetPort: http }] }
---
apiVersion: v1
kind: Service
metadata: { name: fraud-risk-canary, namespace: ml-platform }
spec: { selector: { app: fraud-risk-inference }, ports: [{ name: http, port: 80, targetPort: http }] }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'k8s/base/analysis.yaml' @'
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata: { name: inference-success-rate, namespace: ml-platform }
spec:
  args: [{ name: service }]
  metrics:
    - name: success-rate
      interval: 1m
      count: 5
      successCondition: result[0] >= 0.99
      failureLimit: 2
      provider:
        prometheus:
          address: http://prometheus-operated.monitoring.svc:9090
          query: sum(rate(http_requests_total{service="{{args.service}}",status!~"5.."}[5m])) / sum(rate(http_requests_total{service="{{args.service}}"}[5m]))
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'k8s/base/kustomization.yaml' @'
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [namespace.yaml,config.yaml,services.yaml,rollout.yaml,analysis.yaml]
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'terraform/versions.tf' @'
terraform {
  required_version = ">= 1.8.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 6.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.7"
    }
  }
}
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'terraform/main.tf' @'
provider "aws" {
  region = var.aws_region
}
resource "random_id" "suffix" {
  byte_length = 4
}
locals {
  name = "${var.project_name}-${var.environment}"
}
resource "aws_kms_key" "models" {
  description             = "ML model artifact encryption"
  enable_key_rotation     = true
  deletion_window_in_days = 30
}
resource "aws_s3_bucket" "models" {
  bucket        = "${local.name}-${random_id.suffix.hex}"
  force_destroy = false
}
resource "aws_s3_bucket_public_access_block" "models" {
  bucket                  = aws_s3_bucket.models.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}
resource "aws_s3_bucket_versioning" "models" {
  bucket = aws_s3_bucket.models.id
  versioning_configuration {
    status = "Enabled"
  }
}
resource "aws_s3_bucket_server_side_encryption_configuration" "models" {
  bucket = aws_s3_bucket.models.id
  rule {
    apply_server_side_encryption_by_default {
      kms_master_key_id = aws_kms_key.models.arn
      sse_algorithm     = "aws:kms"
    }
    bucket_key_enabled = true
  }
}
resource "aws_ecr_repository" "inference" {
  name                 = "${local.name}-inference"
  image_tag_mutability = "IMMUTABLE"
  image_scanning_configuration {
    scan_on_push = true
  }
  encryption_configuration {
    encryption_type = "KMS"
    kms_key         = aws_kms_key.models.arn
  }
}
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'terraform/variables.tf' @'
variable "project_name" {
  type    = string
  default = "mlops-model-delivery"
}
variable "environment" {
  type    = string
  default = "dev"
}
variable "aws_region" {
  type    = string
  default = "us-east-1"
}
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'terraform/outputs.tf' @'
output "model_bucket" {
  value = aws_s3_bucket.models.id
}
output "inference_repository_url" {
  value = aws_ecr_repository.inference.repository_url
}
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/HLD.md' @'
# High-level design

Training and serving are separate trust/release boundaries. Training produces an evaluated, registered, immutable model artifact. A reviewed alias identifies the approved version. The inference service loads only the approved alias and exposes bounded feature and prediction contracts. Canary analysis gates rollout with live reliability metrics; model-quality monitoring remains separate from infrastructure health.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/LLD.md' @'
# Low-level design

The trainer uses deterministic synthetic data, split seed, algorithm parameters, feature contract, metrics, and registry tags. A quality gate blocks weak ROC AUC. The serving API enforces exactly four finite numeric features and returns only a bounded decision. MLflow metadata lives in PostgreSQL and artifacts in object storage. The Rollout advances 10% then 50% only when Prometheus analysis succeeds.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/RUNBOOK.md' @'
# MLOps runbook

For prediction failures, distinguish service unavailability, model-load failure, feature-contract rejection, and model execution error. Roll back the deployment for runtime regressions; move the champion alias only through the approved promotion workflow for model regressions. Preserve request/model version correlation without logging raw sensitive features.

For drift, validate data-quality and pipeline changes before retraining. Compare slice metrics and calibration, obtain approval, canary the challenger, and retain the previous champion. Restore registry metadata and object artifacts together; verify checksums before serving.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/THREAT-MODEL.md' @'
# Threat model

Threats include poisoned training data, feature leakage, malicious pickle artifacts, registry alias takeover, unauthorized promotion, model extraction, membership inference, sensitive-feature logging, dependency compromise, and unbounded inference input. Controls include dataset checksums/lineage, reviewed training code, isolated runners, safer serialization where supported, signed artifacts/images, RBAC and separation of duties, encrypted private stores, bounded inputs/rates, audit logs, privacy testing, and human review for consequential decisions.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'scripts/test.sh' @'
#!/usr/bin/env sh
set -eu
python -m unittest discover -s tests -v
python -m py_compile api/main.py trainer/train.py platform_lib/*.py
docker compose config --quiet
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root '.github/workflows/ci.yml' @'
name: mlops-ci
on: { pull_request: {}, push: { branches: [main] }, workflow_dispatch: {} }
permissions: { contents: read }
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - run: python -m unittest discover -s tests -v
      - run: python -m py_compile api/main.py trainer/train.py platform_lib/*.py
      - run: docker compose config --quiet
      - run: kubectl kustomize k8s/base >/tmp/rendered.yaml
      - uses: hashicorp/setup-terraform@v3
      - run: terraform -chdir=terraform fmt -check -recursive
      - uses: aquasecurity/trivy-action@0.28.0
        with: { scan-type: fs, scan-ref: ., severity: "HIGH,CRITICAL", ignore-unfixed: true, exit-code: "1" }
'@ -WhatIfMode:$WhatIfMode
[pscustomobject]@{Project='21-mlops-model-delivery-platform';Root=$root;Files=$script:Generated.Count}
