param([switch]$WhatIfMode)
. (Join-Path $PSScriptRoot 'Common.ps1')
$root=Join-Path $script:ProjectsRoot '22-secure-software-factory'
Write-TemplateFile $root '.template-owned' 'Generated by tools/module20-projects. Additional user files are never deleted.' -WhatIfMode:$WhatIfMode
Write-TemplateFile $root '.gitignore' @'
.env
artifacts/
reports/
*.pem
*.key
__pycache__/
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'README.md' @'
# Secure Software Factory

An end-to-end software-supply-chain capstone implementing SLSA 1.2 evidence, CycloneDX/SPDX SBOMs, vulnerability policy, keyless Sigstore signing, provenance verification, immutable CI dependencies, and Kubernetes admission enforcement.

```mermaid
flowchart LR
    Commit --> CI[Isolated CI build]
    CI --> Test[Test and lint]
    Test --> Image[OCI image by digest]
    Image --> SBOM[Syft SBOM]
    SBOM --> Scan[Grype policy gate]
    Scan --> Provenance[SLSA provenance]
    Provenance --> Sign[Cosign keyless signature]
    Sign --> Registry[OCI registry]
    Registry --> Admission[Kyverno verifyImages]
    Admission --> Runtime[Kubernetes runtime]
```

## Required demonstration

1. Build the sample application without exposing publishing credentials to pull-request jobs.
2. Generate SPDX and CycloneDX SBOMs; scan the immutable image digest and retain SARIF plus JSON evidence.
3. Sign and attest the pushed digest through GitHub OIDC. Never sign a mutable tag.
4. Verify signer identity, issuer, digest, and SLSA predicate before promotion.
5. Prove the admission policy rejects unsigned images and the CI policy rejects tag-pinned third-party actions.
6. Produce a release evidence bundle and rehearse compromised-builder and vulnerable-package response.

## Local validation

```bash
python -m unittest discover -s tests -v
python scripts/verify_action_pins.py .github/workflows
docker compose config
kubectl kustomize k8s
```

Publishing and keyless signing run only for protected `main` pushes. Forked and pull-request workflows receive read-only permissions and no cloud credentials. Replace example repository identities and registry coordinates before use.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'app/main.py' @'
import json,os
from http.server import BaseHTTPRequestHandler,ThreadingHTTPServer
class Handler(BaseHTTPRequestHandler):
 def do_GET(self):
  if self.path not in ("/health","/api/build-info"):self.send_error(404);return
  body=json.dumps({"status":"ok","revision":os.getenv("REVISION","dev")}).encode();self.send_response(200);self.send_header("Content-Type","application/json");self.send_header("Content-Length",str(len(body)));self.end_headers();self.wfile.write(body)
 def log_message(self,fmt,*args):print(json.dumps({"event":"http","message":fmt%args}))
if __name__=="__main__":ThreadingHTTPServer(("0.0.0.0",8080),Handler).serve_forever()
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'app/Dockerfile' @'
# Replace this release tag with a verified registry digest in a production fork.
FROM python:3.14.1-slim
ARG REVISION=unknown
RUN groupadd -g 10001 app && useradd -u 10001 -g app --no-create-home app
WORKDIR /app
COPY --chown=app:app main.py .
USER 10001:10001
ENV REVISION=$REVISION PYTHONDONTWRITEBYTECODE=1
EXPOSE 8080
HEALTHCHECK --interval=10s --timeout=2s --retries=5 CMD ["python","-c","import urllib.request;urllib.request.urlopen('http://localhost:8080/health')"]
CMD ["python","main.py"]
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docker-compose.yml' @'
services:
  app:
    build: { context: app, args: { REVISION: local } }
    ports: ["${APP_PORT:-8105}:8080"]
    read_only: true
    tmpfs: [/tmp]
    cap_drop: [ALL]
    security_opt: [no-new-privileges:true]
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'scripts/verify_action_pins.py' @'
import pathlib,re,sys
SHA=re.compile(r"^[0-9a-f]{40}$")
def invalid_references(text):
 findings=[]
 for number,line in enumerate(text.splitlines(),1):
  match=re.search(r"\buses:\s*([^\s#]+)",line)
  if not match:continue
  ref=match.group(1)
  if ref.startswith("./") or ref.startswith("docker://"):continue
  if "@" not in ref or not SHA.fullmatch(ref.rsplit("@",1)[1]):findings.append((number,ref))
 return findings
def main(root):
 failures=[]
 for path in pathlib.Path(root).rglob("*.y*ml"):
  for line,ref in invalid_references(path.read_text(encoding="utf-8")):failures.append(f"{path}:{line}: mutable action {ref}")
 if failures:print("\n".join(failures));return 1
 print("All third-party actions use immutable commit SHAs.");return 0
if __name__=="__main__":raise SystemExit(main(sys.argv[1] if len(sys.argv)>1 else ".github/workflows"))
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'tests/test_policy.py' @'
import importlib.util,pathlib,tempfile,unittest
path=pathlib.Path(__file__).parents[1]/"scripts"/"verify_action_pins.py";spec=importlib.util.spec_from_file_location("pins",path);pins=importlib.util.module_from_spec(spec);spec.loader.exec_module(pins)
class PinPolicyTests(unittest.TestCase):
 def test_accepts_sha(self):self.assertEqual([],pins.invalid_references("uses: actions/checkout@"+"a"*40))
 def test_rejects_tag(self):self.assertEqual([(1,"actions/checkout@v4")],pins.invalid_references("uses: actions/checkout@v4"))
 def test_accepts_local_action(self):self.assertEqual([],pins.invalid_references("uses: ./actions/build"))
if __name__=="__main__":unittest.main()
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'scripts/verify_release.sh' @'
#!/usr/bin/env sh
set -eu
: "${IMAGE_DIGEST:?set IMAGE_DIGEST to registry/repository@sha256:...}"
: "${CERTIFICATE_IDENTITY:?set expected workflow identity}"
: "${OIDC_ISSUER:=https://token.actions.githubusercontent.com}"
cosign verify "$IMAGE_DIGEST" --certificate-identity "$CERTIFICATE_IDENTITY" --certificate-oidc-issuer "$OIDC_ISSUER"
cosign verify-attestation "$IMAGE_DIGEST" --type slsaprovenance --certificate-identity "$CERTIFICATE_IDENTITY" --certificate-oidc-issuer "$OIDC_ISSUER"
grype "$IMAGE_DIGEST" --fail-on high --only-fixed
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'policy/release.rego' @'
package release
import rego.v1
default allow := false
allow if {
 input.signature.verified == true
 input.provenance.slsa_build_level >= 2
 input.sbom.format in {"spdx-json", "cyclonedx-json"}
 input.scan.fixable_critical == 0
 input.image_ref == input.signature.subject
}
deny contains message if { not input.signature.verified; message := "signature is not verified" }
deny contains message if { input.scan.fixable_critical > 0; message := "fixable critical vulnerabilities remain" }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'evidence/example-release.json' @'
{"image_ref":"ghcr.io/replace/repository@sha256:replace","signature":{"verified":true,"subject":"ghcr.io/replace/repository@sha256:replace"},"provenance":{"slsa_build_level":2},"sbom":{"format":"spdx-json"},"scan":{"fixable_critical":0}}
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'k8s/namespace.yaml' @'
apiVersion: v1
kind: Namespace
metadata: { name: secure-runtime }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'k8s/workload.yaml' @'
apiVersion: apps/v1
kind: Deployment
metadata: { name: signed-app, namespace: secure-runtime }
spec:
  replicas: 2
  selector: { matchLabels: { app: signed-app } }
  template:
    metadata: { labels: { app: signed-app } }
    spec:
      automountServiceAccountToken: false
      securityContext: { runAsNonRoot: true, seccompProfile: { type: RuntimeDefault } }
      containers:
        - name: app
          image: ghcr.io/replace/secure-app@sha256:replace-with-promoted-digest
          ports: [{ name: http, containerPort: 8080 }]
          resources: { requests: { cpu: 50m, memory: 64Mi }, limits: { cpu: 300m, memory: 128Mi } }
          securityContext: { allowPrivilegeEscalation: false, readOnlyRootFilesystem: true, capabilities: { drop: [ALL] } }
          readinessProbe: { httpGet: { path: /health, port: http }, initialDelaySeconds: 2 }
---
apiVersion: v1
kind: Service
metadata: { name: signed-app, namespace: secure-runtime }
spec: { selector: { app: signed-app }, ports: [{ name: http, port: 80, targetPort: http }] }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'k8s/verify-images-policy.yaml' @'
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata: { name: verify-production-images }
spec:
  validationFailureAction: Enforce
  background: true
  webhookConfiguration: { failurePolicy: Fail }
  rules:
    - name: verify-keyless-signature-and-provenance
      match: { any: [{ resources: { kinds: [Pod], namespaces: [secure-runtime] } }] }
      verifyImages:
        - imageReferences: ["ghcr.io/replace/*"]
          required: true
          verifyDigest: true
          mutateDigest: false
          attestors:
            - entries:
                - keyless:
                    issuer: https://token.actions.githubusercontent.com
                    subject: https://github.com/replace/repository/.github/workflows/release.yml@refs/heads/main
                    rekor: { url: https://rekor.sigstore.dev }
          attestations:
            - predicateType: https://slsa.dev/provenance/v1
              attestors:
                - entries:
                    - keyless:
                        issuer: https://token.actions.githubusercontent.com
                        subject: https://github.com/replace/repository/.github/workflows/release.yml@refs/heads/main
                        rekor: { url: https://rekor.sigstore.dev }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'k8s/kustomization.yaml' @'
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [namespace.yaml, workload.yaml, verify-images-policy.yaml]
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root '.github/workflows/ci.yml' @'
name: untrusted-ci
on: { pull_request: {}, push: { branches-ignore: [main] } }
permissions: { contents: read }
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: python -m unittest discover -s tests -v
      - run: python scripts/verify_action_pins.py .github/workflows
      - run: docker build -t secure-app:ci app
      - uses: anchore/sbom-action@e22c389904149dbc22b58101806040fa8d37a610 # v0.24.0
        with: { image: secure-app:ci, format: spdx-json, output-file: artifacts/sbom.spdx.json, upload-artifact: false }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root '.github/workflows/release.yml' @'
name: trusted-release
on: { push: { branches: [main] }, workflow_dispatch: {} }
permissions: { contents: read, packages: write, id-token: write, attestations: write }
concurrency: { group: production-release, cancel-in-progress: false }
jobs:
  release:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: python -m unittest discover -s tests -v
      - run: python scripts/verify_action_pins.py .github/workflows
      - name: Build immutable image
        id: build
        env:
          IMAGE: "ghcr.io/${{ github.repository }}/secure-app"
          CR_PAT: "${{ github.token }}"
        run: |
          echo "$CR_PAT" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
          docker build --build-arg REVISION="${{ github.sha }}" -t "$IMAGE:${{ github.sha }}" app
          docker push "$IMAGE:${{ github.sha }}"
          digest="$(docker inspect --format='{{index .RepoDigests 0}}' "$IMAGE:${{ github.sha }}")"
          echo "digest=$digest" >> "$GITHUB_OUTPUT"
      - uses: anchore/sbom-action@e22c389904149dbc22b58101806040fa8d37a610 # v0.24.0
        with: { image: "${{ steps.build.outputs.digest }}", format: spdx-json, output-file: artifacts/sbom.spdx.json, upload-artifact: false }
      - uses: sigstore/cosign-installer@351ea76151ae2dbbf52374c9dd639f4981de944f # v4.1.2
        with: { cosign-release: v3.0.6 }
      - run: cosign sign --yes "${{ steps.build.outputs.digest }}"
      - run: cosign attest --yes --type spdxjson --predicate artifacts/sbom.spdx.json "${{ steps.build.outputs.digest }}"
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/SLSA-CONTROLS.md' @'
# SLSA controls and evidence

Target Build L2 first: hosted build, platform-generated signed provenance, immutable artifact identity, and consumer verification. Treat L3 as a build-platform assessment rather than a workflow checkbox. Retain source revision, builder identity, parameters, dependency lockfiles, SBOMs, vulnerability exceptions, signatures, attestations, promotion approval, admission result, and rollback digest. Verify evidence from a separate trust domain before production promotion.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/THREAT-MODEL.md' @'
# Threat model

Threats: malicious pull requests, poisoned actions, mutable tags, compromised scanners/builders, dependency confusion, registry overwrite, credential exfiltration, forged provenance, signing-identity misuse, policy bypass, and vulnerable exceptions. Controls: SHA-pinned actions, read-only untrusted jobs, isolated publishing, OIDC short-lived identity, digest-only signing/deployment, SBOM and provenance retention, independent verification, fail-closed admission, protected environments, two-person exceptions, and periodic trust-root rotation drills.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/RUNBOOK.md' @'
# Supply-chain incident runbook

1. Freeze promotion and revoke affected OIDC/KMS trust bindings.
2. Identify artifacts by digest, signer, builder, dependency and time window; never rely on tags.
3. Quarantine affected workloads with admission and registry policy. Preserve logs, bundles, SBOMs and provenance.
4. Rebuild from a reviewed source revision on a known-good builder with refreshed dependencies and trust roots.
5. Verify independently, deploy by digest, monitor, and document affected consumers plus notification obligations.
6. Re-enable publishing only after credential rotation, workflow review and a successful clean-room release rehearsal.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/DEPENDENCY-POLICY.md' @'
# Dependency policy

Pin every CI action to a full commit SHA and annotate its reviewed release. Pin base images by digest after verifying their signature and provenance. Automate update pull requests, but require tests, diff review and refreshed evidence. A scanner result is untrusted input: isolate it from production credentials and verify the scanner artifact before execution.
'@ -WhatIfMode:$WhatIfMode
[pscustomobject]@{Project='22-secure-software-factory';Root=$root;Files=$script:Generated.Count}
