param([switch]$WhatIfMode)
. (Join-Path $PSScriptRoot 'Common.ps1')
$root=Join-Path $script:ProjectsRoot '23-go-kubernetes-operator'
Write-TemplateFile $root '.template-owned' 'Generated by tools/module20-projects. Additional user files are never deleted.' -WhatIfMode:$WhatIfMode
Write-TemplateFile $root '.gitignore' @'
bin/
coverage.out
dist/
.envtest/
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'README.md' @'
# Go Kubernetes Environment Operator

A Kubernetes 1.36/controller-runtime 0.24 capstone that implements a real declarative API and idempotent control loop in Go 1.26. An `Environment` custom resource creates and continuously reconciles a governed tenant namespace.

```mermaid
flowchart LR
    User --> CR[Environment CR]
    CR --> Controller[Reconcile loop]
    Controller --> Namespace
    Controller --> Quota[ResourceQuota]
    Controller --> Limits[LimitRange]
    Controller --> Network[Default-deny NetworkPolicy]
    Controller --> Status[Conditions and observedGeneration]
```

## What to demonstrate

1. Install the CRD/RBAC/controller and create `config/samples/environment.yaml`.
2. Prove repeated reconciliation is idempotent and manual drift is repaired.
3. Submit invalid quota and owner values and observe schema/domain validation.
4. Delete the custom resource and trace finalizer-driven namespace cleanup.
5. Run two replicas and prove only the leader reconciles.
6. Inject API conflicts and timeouts; verify bounded requeue, events, status conditions and metrics.

## Validate

```bash
go test ./... -race -cover
go vet ./...
kubectl kustomize config
docker build -t environment-operator:dev .
```

Never point this learning operator at a shared cluster until deletion behavior, RBAC, admission rules and namespace ownership are reviewed.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'go.mod' @'
module example.com/environment-operator

go 1.26.0

require (
  k8s.io/api v0.36.2
  k8s.io/apimachinery v0.36.2
  k8s.io/client-go v0.36.2
  sigs.k8s.io/controller-runtime v0.24.1
)

require (
  github.com/beorn7/perks v1.0.1 // indirect
  github.com/cespare/xxhash/v2 v2.3.0 // indirect
  github.com/davecgh/go-spew v1.1.2-0.20180830191138-d8f796af33cc // indirect
  github.com/emicklei/go-restful/v3 v3.13.0 // indirect
  github.com/evanphx/json-patch/v5 v5.9.11 // indirect
  github.com/fsnotify/fsnotify v1.9.0 // indirect
  github.com/fxamacker/cbor/v2 v2.9.0 // indirect
  github.com/go-logr/logr v1.4.3 // indirect
  github.com/go-logr/zapr v1.3.0 // indirect
  github.com/go-openapi/jsonpointer v0.21.0 // indirect
  github.com/go-openapi/jsonreference v0.20.2 // indirect
  github.com/go-openapi/swag v0.23.0 // indirect
  github.com/google/gnostic-models v0.7.0 // indirect
  github.com/google/uuid v1.6.0 // indirect
  github.com/josharian/intern v1.0.0 // indirect
  github.com/json-iterator/go v1.1.12 // indirect
  github.com/mailru/easyjson v0.7.7 // indirect
  github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd // indirect
  github.com/modern-go/reflect2 v1.0.3-0.20250322232337-35a7c28c31ee // indirect
  github.com/munnerz/goautoneg v0.0.0-20191010083416-a7dc8b61c822 // indirect
  github.com/pmezard/go-difflib v1.0.1-0.20181226105442-5d4384ee4fb2 // indirect
  github.com/prometheus/client_golang v1.23.2 // indirect
  github.com/prometheus/client_model v0.6.2 // indirect
  github.com/prometheus/common v0.67.5 // indirect
  github.com/prometheus/procfs v0.19.2 // indirect
  github.com/spf13/pflag v1.0.9 // indirect
  github.com/x448/float16 v0.8.4 // indirect
  go.uber.org/multierr v1.11.0 // indirect
  go.uber.org/zap v1.27.1 // indirect
  go.yaml.in/yaml/v2 v2.4.3 // indirect
  go.yaml.in/yaml/v3 v3.0.4 // indirect
  golang.org/x/net v0.49.0 // indirect
  golang.org/x/oauth2 v0.34.0 // indirect
  golang.org/x/sync v0.19.0 // indirect
  golang.org/x/sys v0.40.0 // indirect
  golang.org/x/term v0.39.0 // indirect
  golang.org/x/text v0.33.0 // indirect
  golang.org/x/time v0.14.0 // indirect
  gomodules.xyz/jsonpatch/v2 v2.4.0 // indirect
  google.golang.org/protobuf v1.36.12-0.20260120151049-f2248ac996af // indirect
  gopkg.in/evanphx/json-patch.v4 v4.13.0 // indirect
  gopkg.in/inf.v0 v0.9.1 // indirect
  gopkg.in/yaml.v3 v3.0.1 // indirect
  k8s.io/apiextensions-apiserver v0.36.0 // indirect
  k8s.io/klog/v2 v2.140.0 // indirect
  k8s.io/kube-openapi v0.0.0-20260317180543-43fb72c5454a // indirect
  k8s.io/utils v0.0.0-20260210185600-b8788abfbbc2 // indirect
  sigs.k8s.io/json v0.0.0-20250730193827-2d320260d730 // indirect
  sigs.k8s.io/randfill v1.0.0 // indirect
  sigs.k8s.io/structured-merge-diff/v6 v6.3.2 // indirect
  sigs.k8s.io/yaml v1.6.0 // indirect
)
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'internal/rules/rules.go' @'
package rules

import (
 "fmt"
 "regexp"
 "strings"
 "k8s.io/apimachinery/pkg/api/resource"
)
var ownerPattern=regexp.MustCompile(`^[a-z0-9][a-z0-9-]{1,61}[a-z0-9]$`)
func Validate(owner,cpu,memory string) error{
 owner=strings.TrimSpace(owner)
 if !ownerPattern.MatchString(owner){return fmt.Errorf("owner must be a lowercase DNS label")}
 cpuValue,error:=resource.ParseQuantity(cpu);if error!=nil||cpuValue.Sign()<=0{return fmt.Errorf("cpu quota must be a positive quantity")}
 memoryValue,error:=resource.ParseQuantity(memory);if error!=nil||memoryValue.Sign()<=0{return fmt.Errorf("memory quota must be a positive quantity")}
 return nil
}
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'internal/rules/rules_test.go' @'
package rules
import "testing"
func TestValidate(t *testing.T){tests:=[]struct{name,owner,cpu,memory string;valid bool}{{"valid","payments-team","4","8Gi",true},{"owner","Payments","4","8Gi",false},{"cpu","payments-team","zero","8Gi",false},{"memory","payments-team","4","0",false}};for _,test:=range tests{t.Run(test.name,func(t *testing.T){error:=Validate(test.owner,test.cpu,test.memory);if (error==nil)!=test.valid{t.Fatalf("valid=%v error=%v",test.valid,error)}})}}
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'api/v1alpha1/groupversion_info.go' @'
package v1alpha1
import (
 "k8s.io/apimachinery/pkg/runtime/schema"
 "sigs.k8s.io/controller-runtime/pkg/scheme"
)
var GroupVersion=schema.GroupVersion{Group:"platform.masterclass.io",Version:"v1alpha1"}
var SchemeBuilder=&scheme.Builder{GroupVersion:GroupVersion}
var AddToScheme=SchemeBuilder.AddToScheme
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'api/v1alpha1/environment_types.go' @'
package v1alpha1
import metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
type EnvironmentSpec struct{Owner string `json:"owner"`;CPUQuota string `json:"cpuQuota"`;MemoryQuota string `json:"memoryQuota"`;DeleteNamespace bool `json:"deleteNamespace,omitempty"`}
type EnvironmentStatus struct{ObservedGeneration int64 `json:"observedGeneration,omitempty"`;Namespace string `json:"namespace,omitempty"`;Conditions []metav1.Condition `json:"conditions,omitempty"`}
// +kubebuilder:object:root=true
// +kubebuilder:resource:scope=Cluster,shortName=env
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Namespace",type=string,JSONPath=`.status.namespace`
// +kubebuilder:printcolumn:name="Ready",type=string,JSONPath=`.status.conditions[?(@.type=='Ready')].status`
type Environment struct{metav1.TypeMeta `json:",inline"`;metav1.ObjectMeta `json:"metadata,omitempty"`;Spec EnvironmentSpec `json:"spec,omitempty"`;Status EnvironmentStatus `json:"status,omitempty"`}
// +kubebuilder:object:root=true
type EnvironmentList struct{metav1.TypeMeta `json:",inline"`;metav1.ListMeta `json:"metadata,omitempty"`;Items []Environment `json:"items"`}
func init(){SchemeBuilder.Register(&Environment{},&EnvironmentList{})}
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'api/v1alpha1/zz_generated.deepcopy.go' @'
package v1alpha1
import (
 metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
 "k8s.io/apimachinery/pkg/runtime"
)
func(in *Environment)DeepCopyInto(out *Environment){*out=*in;in.ObjectMeta.DeepCopyInto(&out.ObjectMeta);if in.Status.Conditions!=nil{out.Status.Conditions=make([]metav1.Condition,len(in.Status.Conditions));copy(out.Status.Conditions,in.Status.Conditions)}}
func(in *Environment)DeepCopy()*Environment{if in==nil{return nil};out:=new(Environment);in.DeepCopyInto(out);return out}
func(in *Environment)DeepCopyObject()runtime.Object{return in.DeepCopy()}
func(in *EnvironmentList)DeepCopyInto(out *EnvironmentList){*out=*in;in.ListMeta.DeepCopyInto(&out.ListMeta);if in.Items!=nil{out.Items=make([]Environment,len(in.Items));for i:=range in.Items{in.Items[i].DeepCopyInto(&out.Items[i])}}}
func(in *EnvironmentList)DeepCopy()*EnvironmentList{if in==nil{return nil};out:=new(EnvironmentList);in.DeepCopyInto(out);return out}
func(in *EnvironmentList)DeepCopyObject()runtime.Object{return in.DeepCopy()}
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'internal/controller/environment_controller.go' @'
package controller
import (
 "context"
 "fmt"
 corev1 "k8s.io/api/core/v1"
 networkingv1 "k8s.io/api/networking/v1"
 apierrors "k8s.io/apimachinery/pkg/api/errors"
 "k8s.io/apimachinery/pkg/api/meta"
 "k8s.io/apimachinery/pkg/api/resource"
 metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
 "k8s.io/apimachinery/pkg/types"
 "k8s.io/apimachinery/pkg/runtime"
 ctrl "sigs.k8s.io/controller-runtime"
 "sigs.k8s.io/controller-runtime/pkg/client"
 "sigs.k8s.io/controller-runtime/pkg/controller/controllerutil"
 platformv1alpha1 "example.com/environment-operator/api/v1alpha1"
 "example.com/environment-operator/internal/rules"
)
const finalizer="platform.masterclass.io/environment-cleanup"
type EnvironmentReconciler struct{client.Client;Scheme *runtime.Scheme}
func(r *EnvironmentReconciler)Reconcile(ctx context.Context,request ctrl.Request)(ctrl.Result,error){
 environment:=&platformv1alpha1.Environment{};if error:=r.Get(ctx,request.NamespacedName,environment);error!=nil{return ctrl.Result{},client.IgnoreNotFound(error)}
 namespaceName:="tenant-"+environment.Name
 if !environment.DeletionTimestamp.IsZero(){return r.finalize(ctx,environment,namespaceName)}
 if !controllerutil.ContainsFinalizer(environment,finalizer){controllerutil.AddFinalizer(environment,finalizer);if error:=r.Update(ctx,environment);error!=nil{return ctrl.Result{},error}}
 if error:=rules.Validate(environment.Spec.Owner,environment.Spec.CPUQuota,environment.Spec.MemoryQuota);error!=nil{return ctrl.Result{},r.setCondition(ctx,environment,metav1.ConditionFalse,"InvalidSpec",error.Error())}
 labels:=map[string]string{"platform.masterclass.io/environment":environment.Name,"platform.masterclass.io/owner":environment.Spec.Owner}
 namespace:=&corev1.Namespace{ObjectMeta:metav1.ObjectMeta{Name:namespaceName}}
 if _,error:=controllerutil.CreateOrUpdate(ctx,r.Client,namespace,func()error{namespace.Labels=labels;return controllerutil.SetControllerReference(environment,namespace,r.Scheme)});error!=nil{return ctrl.Result{},error}
 quota:=&corev1.ResourceQuota{ObjectMeta:metav1.ObjectMeta{Name:"tenant-quota",Namespace:namespaceName}}
 if _,error:=controllerutil.CreateOrUpdate(ctx,r.Client,quota,func()error{quota.Spec.Hard=corev1.ResourceList{corev1.ResourceRequestsCPU:resource.MustParse(environment.Spec.CPUQuota),corev1.ResourceRequestsMemory:resource.MustParse(environment.Spec.MemoryQuota),corev1.ResourceLimitsCPU:resource.MustParse(environment.Spec.CPUQuota),corev1.ResourceLimitsMemory:resource.MustParse(environment.Spec.MemoryQuota)};return controllerutil.SetControllerReference(environment,quota,r.Scheme)});error!=nil{return ctrl.Result{},error}
 limits:=&corev1.LimitRange{ObjectMeta:metav1.ObjectMeta{Name:"tenant-defaults",Namespace:namespaceName}}
 if _,error:=controllerutil.CreateOrUpdate(ctx,r.Client,limits,func()error{limits.Spec.Limits=[]corev1.LimitRangeItem{{Type:corev1.LimitTypeContainer,DefaultRequest:corev1.ResourceList{corev1.ResourceCPU:resource.MustParse("50m"),corev1.ResourceMemory:resource.MustParse("64Mi")},Default:corev1.ResourceList{corev1.ResourceCPU:resource.MustParse("500m"),corev1.ResourceMemory:resource.MustParse("512Mi")}}};return controllerutil.SetControllerReference(environment,limits,r.Scheme)});error!=nil{return ctrl.Result{},error}
 policy:=&networkingv1.NetworkPolicy{ObjectMeta:metav1.ObjectMeta{Name:"default-deny",Namespace:namespaceName}}
 if _,error:=controllerutil.CreateOrUpdate(ctx,r.Client,policy,func()error{policy.Spec.PodSelector=metav1.LabelSelector{};policy.Spec.PolicyTypes=[]networkingv1.PolicyType{networkingv1.PolicyTypeIngress,networkingv1.PolicyTypeEgress};return controllerutil.SetControllerReference(environment,policy,r.Scheme)});error!=nil{return ctrl.Result{},error}
 environment.Status.Namespace=namespaceName;return ctrl.Result{},r.setCondition(ctx,environment,metav1.ConditionTrue,"Reconciled","tenant controls match desired state")
}
func(r *EnvironmentReconciler)finalize(ctx context.Context,environment *platformv1alpha1.Environment,namespace string)(ctrl.Result,error){if !controllerutil.ContainsFinalizer(environment,finalizer){return ctrl.Result{},nil};if environment.Spec.DeleteNamespace{target:=&corev1.Namespace{};error:=r.Get(ctx,types.NamespacedName{Name:namespace},target);if error==nil{if error=r.Delete(ctx,target);error!=nil{return ctrl.Result{},error};return ctrl.Result{RequeueAfter:2e9},nil};if !apierrors.IsNotFound(error){return ctrl.Result{},error}};controllerutil.RemoveFinalizer(environment,finalizer);return ctrl.Result{},r.Update(ctx,environment)}
func(r *EnvironmentReconciler)setCondition(ctx context.Context,environment *platformv1alpha1.Environment,status metav1.ConditionStatus,reason,message string)error{environment.Status.ObservedGeneration=environment.Generation;meta.SetStatusCondition(&environment.Status.Conditions,metav1.Condition{Type:"Ready",Status:status,Reason:reason,Message:message,ObservedGeneration:environment.Generation});if error:=r.Status().Update(ctx,environment);error!=nil{return fmt.Errorf("update status: %w",error)};return nil}
func(r *EnvironmentReconciler)SetupWithManager(manager ctrl.Manager)error{return ctrl.NewControllerManagedBy(manager).For(&platformv1alpha1.Environment{}).Owns(&corev1.Namespace{}).Complete(r)}
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'cmd/main.go' @'
package main
import (
 "flag"
 "os"
 clientgoscheme "k8s.io/client-go/kubernetes/scheme"
 "k8s.io/apimachinery/pkg/runtime"
 utilruntime "k8s.io/apimachinery/pkg/util/runtime"
 ctrl "sigs.k8s.io/controller-runtime"
 "sigs.k8s.io/controller-runtime/pkg/healthz"
 "sigs.k8s.io/controller-runtime/pkg/log/zap"
 metricsserver "sigs.k8s.io/controller-runtime/pkg/metrics/server"
 platformv1alpha1 "example.com/environment-operator/api/v1alpha1"
 "example.com/environment-operator/internal/controller"
)
var scheme=runtime.NewScheme()
func init(){utilruntime.Must(clientgoscheme.AddToScheme(scheme));utilruntime.Must(platformv1alpha1.AddToScheme(scheme))}
func main(){var metricsAddress,probeAddress string;flag.StringVar(&metricsAddress,"metrics-bind-address",":8080","metrics address");flag.StringVar(&probeAddress,"health-probe-bind-address",":8081","probe address");options:=zap.Options{Development:false};options.BindFlags(flag.CommandLine);flag.Parse();ctrl.SetLogger(zap.New(zap.UseFlagOptions(&options)));manager,error:=ctrl.NewManager(ctrl.GetConfigOrDie(),ctrl.Options{Scheme:scheme,Metrics:metricsserver.Options{BindAddress:metricsAddress},HealthProbeBindAddress:probeAddress,LeaderElection:true,LeaderElectionID:"environment-operator.platform.masterclass.io"});if error!=nil{os.Exit(1)};if error=(&controller.EnvironmentReconciler{Client:manager.GetClient(),Scheme:manager.GetScheme()}).SetupWithManager(manager);error!=nil{os.Exit(1)};_ = manager.AddHealthzCheck("healthz",healthz.Ping);_ = manager.AddReadyzCheck("readyz",healthz.Ping);if error=manager.Start(ctrl.SetupSignalHandler());error!=nil{os.Exit(1)}}
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'Dockerfile' @'
FROM golang:1.26.5-alpine AS build
WORKDIR /src
COPY go.mod go.sum* ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -trimpath -ldflags="-s -w" -o /manager ./cmd
FROM gcr.io/distroless/static-debian13:nonroot
COPY --from=build /manager /manager
USER 65532:65532
ENTRYPOINT ["/manager"]
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'config/crd/environment.yaml' @'
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata: { name: environments.platform.masterclass.io }
spec:
  group: platform.masterclass.io
  scope: Cluster
  names: { plural: environments, singular: environment, kind: Environment, shortNames: [env] }
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources: { status: {} }
      additionalPrinterColumns:
        - { name: Namespace, type: string, jsonPath: .status.namespace }
        - { name: Ready, type: string, jsonPath: ".status.conditions[?(@.type=='Ready')].status" }
      schema:
        openAPIV3Schema:
          type: object
          required: [spec]
          properties:
            apiVersion: { type: string }
            kind: { type: string }
            metadata: { type: object }
            spec:
              type: object
              required: [owner, cpuQuota, memoryQuota]
              properties:
                owner: { type: string, pattern: "^[a-z0-9][a-z0-9-]{1,61}[a-z0-9]$" }
                cpuQuota: { type: string, minLength: 1 }
                memoryQuota: { type: string, minLength: 1 }
                deleteNamespace: { type: boolean, default: false }
            status:
              type: object
              properties:
                observedGeneration: { type: integer, format: int64 }
                namespace: { type: string }
                conditions: { type: array, items: { type: object, x-kubernetes-preserve-unknown-fields: true } }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'config/rbac/rbac.yaml' @'
apiVersion: v1
kind: ServiceAccount
metadata: { name: environment-operator, namespace: environment-system }
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata: { name: environment-operator }
rules:
  - apiGroups: [platform.masterclass.io]
    resources: [environments, environments/status, environments/finalizers]
    verbs: [get, list, watch, create, update, patch]
  - apiGroups: [""]
    resources: [namespaces, resourcequotas, limitranges]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [networking.k8s.io]
    resources: [networkpolicies]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [coordination.k8s.io]
    resources: [leases]
    verbs: [get, list, watch, create, update, patch, delete]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata: { name: environment-operator }
roleRef: { apiGroup: rbac.authorization.k8s.io, kind: ClusterRole, name: environment-operator }
subjects: [{ kind: ServiceAccount, name: environment-operator, namespace: environment-system }]
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'config/manager/manager.yaml' @'
apiVersion: apps/v1
kind: Deployment
metadata: { name: environment-operator, namespace: environment-system }
spec:
  replicas: 2
  selector: { matchLabels: { app: environment-operator } }
  template:
    metadata: { labels: { app: environment-operator } }
    spec:
      serviceAccountName: environment-operator
      securityContext: { runAsNonRoot: true, seccompProfile: { type: RuntimeDefault } }
      containers:
        - name: manager
          image: ghcr.io/replace/environment-operator:v0.1.0
          args: ["--metrics-bind-address=:8080", "--health-probe-bind-address=:8081"]
          ports: [{ name: metrics, containerPort: 8080 }, { name: health, containerPort: 8081 }]
          resources: { requests: { cpu: 50m, memory: 64Mi }, limits: { cpu: 500m, memory: 256Mi } }
          securityContext: { allowPrivilegeEscalation: false, readOnlyRootFilesystem: true, capabilities: { drop: [ALL] } }
          readinessProbe: { httpGet: { path: /readyz, port: health }, initialDelaySeconds: 3 }
          livenessProbe: { httpGet: { path: /healthz, port: health }, initialDelaySeconds: 10 }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'config/default/namespace.yaml' @'
apiVersion: v1
kind: Namespace
metadata: { name: environment-system }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'config/default/kustomization.yaml' @'
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [namespace.yaml]
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'config/kustomization.yaml' @'
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [default, crd/environment.yaml, rbac/rbac.yaml, manager/manager.yaml]
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'config/samples/environment.yaml' @'
apiVersion: platform.masterclass.io/v1alpha1
kind: Environment
metadata: { name: payments-dev }
spec: { owner: payments-team, cpuQuota: "4", memoryQuota: 8Gi, deleteNamespace: true }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'Makefile' @'
.PHONY: test build manifests install run
test:
	go test ./... -race -cover
build:
	go build ./cmd
manifests:
	kubectl kustomize config >/tmp/environment-operator.yaml
install:
	kubectl apply -k config
run:
	go run ./cmd
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root '.github/workflows/ci.yml' @'
name: operator-ci
on: { pull_request: {}, push: { branches: [main] } }
permissions: { contents: read }
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with: { go-version: 1.26.5, cache: true }
      - run: go test ./... -race -coverprofile=coverage.out
      - run: go vet ./...
      - run: kubectl kustomize config >/tmp/operator.yaml
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/HLD.md' @'
# High-level design

The cluster-scoped Environment API is the contract. A leader-elected controller watches desired state and owns Namespace, ResourceQuota, LimitRange and NetworkPolicy resources. Status conditions expose readiness while Kubernetes events and controller-runtime metrics expose operations. Admission schema rejects malformed objects before reconciliation.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/LLD.md' @'
# Low-level design

Reconcile is level-driven: fetch, handle deletion, ensure finalizer, validate, CreateOrUpdate every dependent, then patch status. Never assume a single event or rely on in-memory state. Conflicts return errors for rate-limited retry. Finalization is explicit and opt-in because namespace deletion is destructive. Add envtest coverage for create, drift, deletion, conflict and upgrade before production use.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/RUNBOOK.md' @'
# Operator runbook

Check leader-election lease, work queue depth, reconcile errors and Ready conditions. For a stuck finalizer, inspect dependent namespace state and API errors before any manual removal. For hot loops, pause new CR creation, identify resource-version conflicts or a non-idempotent mutation, then roll back the controller. Back up CRs and document conversion before changing a served/storage API version.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/THREAT-MODEL.md' @'
# Threat model

Threats include privilege escalation through CR fields, namespace takeover, unsafe finalizer deletion, API-server denial of service, malicious image replacement, RBAC expansion and status spoofing. Controls include structural schemas, domain validation, least-privilege RBAC, digest-pinned images, bounded concurrency/retries, deletion opt-in, admission policies, audit logging and a separate role for status updates.
'@ -WhatIfMode:$WhatIfMode
[pscustomobject]@{Project='23-go-kubernetes-operator';Root=$root;Files=$script:Generated.Count}
