param([switch]$WhatIfMode)
. (Join-Path $PSScriptRoot 'Common.ps1')
$root=Join-Path $script:ProjectsRoot '24-azure-enterprise-platform'
Write-TemplateFile $root '.template-owned' 'Generated by tools/module20-projects. Additional user files are never deleted.' -WhatIfMode:$WhatIfMode
Write-TemplateFile $root '.gitignore' @'
.env
*.local.bicepparam
.azure/
what-if.json
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'README.md' @'
# Azure Enterprise Platform and AKS Landing Zone

A production-shaped Azure platform capstone using Bicep, AKS, Cilium, private networking, Azure Container Registry, Key Vault, Azure Monitor, Azure Policy, Entra Workload Identity and GitOps-ready Kubernetes contracts.

```mermaid
flowchart LR
    Entra[Microsoft Entra ID] --> RBAC[Azure RBAC]
    Hub[Hub connectivity] --> VNet[Spoke VNet]
    VNet --> AKS[Private AKS]
    ACR --> AKS
    KeyVault --> WI[Workload Identity]
    WI --> Pod
    AKS --> Monitor[Log Analytics and Azure Monitor]
    Policy[Azure Policy] --> AKS
    GitOps[Argo CD or Flux] --> AKS
```

## Required demonstration

1. Run a subscription-scope Bicep what-if; review every resource, role and monthly cost before deployment.
2. Deploy a private AKS baseline into an application landing-zone subscription connected to centrally owned network/DNS services.
3. Use Entra Workload Identity for Key Vault access; prove the pod has no client secret.
4. Pull through private ACR, enforce Azure Policy and Kubernetes admission controls, and publish diagnostic logs centrally.
5. Exercise node-pool upgrade, availability-zone failure, Key Vault rotation, backup/restore and regional recovery runbooks.

## Validate without provisioning

```bash
az bicep build --file infra/main.bicep
az deployment sub what-if --location centralindia --template-file infra/main.bicep --parameters infra/dev.bicepparam
kubectl kustomize k8s
```

The supplied defaults are examples, not cost authorization. Private DNS, hub peering, Defender plans, backup vaults, production node sizing and organization policy assignments must be owned by the relevant platform teams.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'infra/main.bicep' @'
targetScope = 'subscription'

@minLength(3)
param prefix string = 'masterclass'
@minLength(2)
param environment string = 'dev'
param location string = 'centralindia'
param kubernetesVersion string = '1.36'
param privateCluster bool = true
param tags object = { Environment: environment, ManagedBy: 'Bicep', Owner: 'replace-with-owner', CostCenter: 'replace-with-cost-center' }

var resourceGroupName = '${prefix}-${environment}-platform-rg'
resource platformResourceGroup 'Microsoft.Resources/resourceGroups@2025-04-01' = { name: resourceGroupName, location: location, tags: tags }

module network 'modules/network.bicep' = {
 name: 'network-${environment}'
 scope: platformResourceGroup
 params: { prefix: prefix, environment: environment, location: location, tags: tags }
}
module platform 'modules/platform.bicep' = {
 name: 'platform-${environment}'
 scope: platformResourceGroup
 params: {
  prefix: prefix
  environment: environment
  location: location
  kubernetesVersion: kubernetesVersion
  privateCluster: privateCluster
  aksSubnetId: network.outputs.aksSubnetId
  tags: tags
 }
}
output resourceGroupName string = platformResourceGroup.name
output clusterName string = platform.outputs.clusterName
output oidcIssuer string = platform.outputs.oidcIssuer
output workloadIdentityClientId string = platform.outputs.workloadIdentityClientId
output keyVaultName string = platform.outputs.keyVaultName
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'infra/modules/network.bicep' @'
@minLength(3)
param prefix string
@minLength(2)
param environment string
param location string
param tags object
resource networkSecurityGroup 'Microsoft.Network/networkSecurityGroups@2024-05-01' = { name: '${prefix}-${environment}-aks-nsg', location: location, tags: tags, properties: { securityRules: [] } }
resource virtualNetwork 'Microsoft.Network/virtualNetworks@2024-05-01' = {
 name: '${prefix}-${environment}-spoke-vnet'
 location: location
 tags: tags
 properties: {
  addressSpace: { addressPrefixes: ['10.60.0.0/16'] }
  subnets: [{
   name: 'aks'
   properties: {
    addressPrefix: '10.60.0.0/20'
    networkSecurityGroup: { id: networkSecurityGroup.id }
    privateEndpointNetworkPolicies: 'Disabled'
   }
  }]
 }
}
output aksSubnetId string = virtualNetwork.properties.subnets[0].id
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'infra/modules/platform.bicep' @'
@minLength(3)
param prefix string
@minLength(2)
param environment string
param location string
param kubernetesVersion string
param privateCluster bool
param aksSubnetId string
param tags object
resource logs 'Microsoft.OperationalInsights/workspaces@2023-09-01' = { name: '${prefix}-${environment}-logs', location: location, tags: tags, properties: { retentionInDays: 30, features: { enableLogAccessUsingOnlyResourcePermissions: true } } }
resource registry 'Microsoft.ContainerRegistry/registries@2023-07-01' = { name: 'acr${uniqueString(resourceGroup().id)}', location: location, tags: tags, sku: { name: 'Premium' }, properties: { adminUserEnabled: false, publicNetworkAccess: 'Disabled', policies: { retentionPolicy: { days: 14, status: 'enabled' }, exportPolicy: { status: 'disabled' }, quarantinePolicy: { status: 'enabled' }, trustPolicy: { type: 'Notary', status: 'disabled' } } } }
resource identity 'Microsoft.ManagedIdentity/userAssignedIdentities@2023-01-31' = { name: '${prefix}-${environment}-workload-id', location: location, tags: tags }
resource vault 'Microsoft.KeyVault/vaults@2023-07-01' = {
 name: 'kv${uniqueString(resourceGroup().id)}'
 location: location
 tags: tags
 properties: {
  tenantId: subscription().tenantId
  sku: { family: 'A', name: 'standard' }
  enableRbacAuthorization: true
  enablePurgeProtection: true
  enableSoftDelete: true
  softDeleteRetentionInDays: 90
  publicNetworkAccess: 'Disabled'
 }
}
resource aks 'Microsoft.ContainerService/managedClusters@2025-05-01' = {
 name: '${prefix}-${environment}-aks'
 location: location
 tags: tags
 identity: { type: 'SystemAssigned' }
 sku: { name: 'Base', tier: 'Standard' }
 properties: {
  kubernetesVersion: kubernetesVersion
  dnsPrefix: '${prefix}-${environment}'
  enableRBAC: true
  disableLocalAccounts: true
  oidcIssuerProfile: { enabled: true }
  securityProfile: { workloadIdentity: { enabled: true }, defender: { logAnalyticsWorkspaceResourceId: logs.id, securityMonitoring: { enabled: true } } }
  aadProfile: { managed: true, enableAzureRBAC: true, tenantID: subscription().tenantId }
  apiServerAccessProfile: { enablePrivateCluster: privateCluster, privateDNSZone: privateCluster ? 'system' : 'none' }
  networkProfile: { networkPlugin: 'azure', networkPluginMode: 'overlay', networkDataplane: 'cilium', loadBalancerSku: 'standard', outboundType: 'loadBalancer', serviceCidr: '10.70.0.0/16', dnsServiceIP: '10.70.0.10' }
  agentPoolProfiles: [{ name: 'system', mode: 'System', count: 3, vmSize: 'Standard_D4ds_v5', osType: 'Linux', type: 'VirtualMachineScaleSets', vnetSubnetID: aksSubnetId, enableAutoScaling: true, minCount: 3, maxCount: 6, availabilityZones: ['1','2','3'], osDiskType: 'Managed', osDiskSizeGB: 128, maxPods: 50 }]
  addonProfiles: { azurepolicy: { enabled: true }, omsagent: { enabled: true, config: { logAnalyticsWorkspaceResourceID: logs.id, useAADAuth: 'true' } } }
 }
}
resource federation 'Microsoft.ManagedIdentity/userAssignedIdentities/federatedIdentityCredentials@2023-01-31' = {
 parent: identity
 name: 'sample-workload'
 properties: { issuer: aks.properties.oidcIssuerProfile.issuerURL, subject: 'system:serviceaccount:sample:sample-api', audiences: ['api://AzureADTokenExchange'] }
}
resource keyVaultSecretsUser 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
 scope: vault
 name: guid(vault.id,identity.id,'Key Vault Secrets User')
 properties: { roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions','4633458b-17de-408a-b874-0445c86b69e6'), principalId: identity.properties.principalId, principalType: 'ServicePrincipal' }
}
output clusterName string = aks.name
output oidcIssuer string = aks.properties.oidcIssuerProfile.issuerURL
output workloadIdentityClientId string = identity.properties.clientId
output keyVaultName string = vault.name
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'infra/dev.bicepparam' @'
using './main.bicep'
param prefix = 'masterclass'
param environment = 'dev'
param location = 'centralindia'
param kubernetesVersion = '1.36'
param privateCluster = true
param tags = { Environment: 'dev', ManagedBy: 'Bicep', Owner: 'replace-with-owner', CostCenter: 'replace-with-cost-center', DataClass: 'internal' }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'policy/deny-public-ip.json' @'
{"properties":{"displayName":"Deny public IP addresses in application landing zones","policyType":"Custom","mode":"All","metadata":{"category":"Network"},"parameters":{},"policyRule":{"if":{"field":"type","equals":"Microsoft.Network/publicIPAddresses"},"then":{"effect":"deny"}}}}
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'k8s/namespace.yaml' @'
apiVersion: v1
kind: Namespace
metadata: { name: sample, labels: { pod-security.kubernetes.io/enforce: restricted } }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'k8s/workload.yaml' @'
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sample-api
  namespace: sample
  annotations: { azure.workload.identity/client-id: replace-with-bicep-output }
---
apiVersion: apps/v1
kind: Deployment
metadata: { name: sample-api, namespace: sample }
spec:
  replicas: 2
  selector: { matchLabels: { app: sample-api } }
  template:
    metadata: { labels: { app: sample-api, azure.workload.identity/use: "true" } }
    spec:
      serviceAccountName: sample-api
      securityContext: { runAsNonRoot: true, seccompProfile: { type: RuntimeDefault } }
      containers:
        - name: app
          image: ghcr.io/replace/sample-api@sha256:replace
          env: [{ name: KEY_VAULT_URL, value: https://replace.vault.azure.net/ }]
          ports: [{ name: http, containerPort: 8080 }]
          resources: { requests: { cpu: 50m, memory: 64Mi }, limits: { cpu: 500m, memory: 256Mi } }
          securityContext: { allowPrivilegeEscalation: false, readOnlyRootFilesystem: true, capabilities: { drop: [ALL] } }
---
apiVersion: v1
kind: Service
metadata: { name: sample-api, namespace: sample }
spec: { selector: { app: sample-api }, ports: [{ name: http, port: 80, targetPort: http }] }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'k8s/networkpolicy.yaml' @'
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata: { name: default-deny, namespace: sample }
spec: { podSelector: {}, policyTypes: [Ingress, Egress] }
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata: { name: allow-dns-and-https, namespace: sample }
spec:
  podSelector: { matchLabels: { app: sample-api } }
  policyTypes: [Egress]
  egress:
    - to: [{ namespaceSelector: { matchLabels: { kubernetes.io/metadata.name: kube-system } } }]
      ports: [{ protocol: UDP, port: 53 }, { protocol: TCP, port: 53 }]
    - ports: [{ protocol: TCP, port: 443 }]
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'k8s/kustomization.yaml' @'
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [namespace.yaml, workload.yaml, networkpolicy.yaml]
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'scripts/validate.ps1' @'
$ErrorActionPreference='Stop'
if(Get-Command az -ErrorAction SilentlyContinue){az bicep build --file infra/main.bicep --outfile ([IO.Path]::GetTempFileName())}
kubectl kustomize k8s | Out-Null
Get-Content -Raw policy/deny-public-ip.json | ConvertFrom-Json | Out-Null
Write-Host 'Azure platform contracts validated.'
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root '.github/workflows/ci.yml' @'
name: azure-platform-ci
on: { pull_request: {}, push: { branches: [main] } }
permissions: { contents: read, id-token: write }
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: az bicep install --version v0.45.15
      - run: az bicep build --file infra/main.bicep
      - run: kubectl kustomize k8s >/tmp/azure-workload.yaml
  what-if:
    if: github.event_name != 'pull_request'
    environment: azure-plan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: azure/login@532459ea530d8321f2fb9bb10d1e0bcf23869a43 # v3.0.0
        with: { client-id: "${{ secrets.AZURE_CLIENT_ID }}", tenant-id: "${{ secrets.AZURE_TENANT_ID }}", subscription-id: "${{ secrets.AZURE_SUBSCRIPTION_ID }}" }
      - run: az deployment sub what-if --location centralindia --template-file infra/main.bicep --parameters infra/dev.bicepparam --no-pretty-print
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/HLD.md' @'
# High-level design

The application landing zone inherits identity, policy, security and connectivity controls from a centrally managed Azure platform landing zone. AKS is private, zone-spread and identity-integrated. ACR, Key Vault and Log Analytics use private connectivity in production. GitOps owns Kubernetes desired state; Bicep owns Azure control-plane resources.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/LLD.md' @'
# Low-level design

Bicep deploys at subscription scope into a dedicated resource group. The spoke VNet delegates a bounded AKS subnet. OIDC and Workload Identity exchange a Kubernetes service-account token for a user-assigned managed identity. Azure RBAC grants only Key Vault Secrets User. Separate system/user node pools, private endpoints, DNS links, egress firewall and backup vaults should be added for production.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/RUNBOOK.md' @'
# Azure platform runbook

For cluster access failure, distinguish Entra/RBAC, private DNS, network and API availability. For workload identity failures, validate issuer, subject, audience, service-account label and federated credential before changing roles. Test node-image and Kubernetes upgrades in a non-production ring. Restore Kubernetes state and persistent data separately; record measured regional RTO/RPO and validate DNS/certificate dependencies.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/THREAT-MODEL.md' @'
# Threat model

Threats include subscription privilege escalation, public control-plane exposure, managed-identity federation errors, image substitution, Key Vault exfiltration, unrestricted egress, policy exemptions and diagnostic-log tampering. Controls include management-group policy, private endpoints, Azure RBAC, Workload Identity, digest-only images, Cilium policy, firewall egress, immutable logs and time-bounded approved exemptions.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/COST-AND-DR.md' @'
# Cost and disaster recovery

Tag every resource and export cost by subscription, resource group, namespace and owner. Budget for AKS control plane tier, zone-spread nodes, NAT/firewall, private endpoints, Defender, logs and backups. Define regional service tiers; not every workload needs active-active. Rehearse cluster recreation from Bicep/GitOps, Key Vault recovery, registry replication, persistent-volume restoration and DNS traffic shift.
'@ -WhatIfMode:$WhatIfMode
[pscustomobject]@{Project='24-azure-enterprise-platform';Root=$root;Files=$script:Generated.Count}
