param([switch]$WhatIfMode)
. (Join-Path $PSScriptRoot 'Common.ps1')
$root=Join-Path $script:ProjectsRoot '25-gcp-enterprise-platform'
Write-TemplateFile $root '.template-owned' 'Generated by tools/module20-projects. Additional user files are never deleted.' -WhatIfMode:$WhatIfMode
Write-TemplateFile $root '.gitignore' @'
.terraform/
*.tfstate*
*.tfplan
*.auto.tfvars
.env
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'README.md' @'
# Google Cloud Enterprise Platform and GKE Landing Zone

A Google Cloud foundation capstone using Terraform, organization/folder/project boundaries, Shared-VPC-ready networking, private regional GKE, Workload Identity Federation, Cloud KMS, Secret Manager, Artifact Registry, Pub/Sub, Binary Authorization, centralized logging and Cloud Build.

```mermaid
flowchart LR
    Org[Google Cloud organization] --> Folder[Platform folder]
    Folder --> NetworkProject[Network project]
    Folder --> SecurityProject[Security project]
    Folder --> WorkloadProject[Workload project]
    NetworkProject --> VPC[Private VPC and NAT]
    VPC --> GKE[Regional private GKE]
    Registry[Artifact Registry] --> GKE
    WIF[Workload Identity] --> Secret[Secret Manager]
    GKE --> Logs[Central audit and workload logs]
    Policy[Organization policies] --> Folder
```

## Required demonstration

1. Review and plan the organization/folder/project bootstrap separately from workload infrastructure.
2. Prove GKE nodes and control plane are private, egress is controlled, and tenant workloads use Workload Identity rather than JSON keys.
3. Build an immutable image with Cloud Build, retain provenance, enforce Binary Authorization and deploy through GitOps.
4. Validate project isolation, IAM inheritance, Shared VPC ownership, log sinks, KMS/Secret Manager access and budget alerts.
5. Recreate the cluster from Terraform/GitOps and rehearse regional workload and state recovery.

## Validate without provisioning

```bash
terraform -chdir=terraform/bootstrap init -backend=false
terraform -chdir=terraform/bootstrap validate
terraform -chdir=terraform/workload init -backend=false
terraform -chdir=terraform/workload validate
kubectl kustomize k8s
gcloud builds submit --config cloudbuild.yaml --no-source # use only after configuring a project
```

Organization creation, billing attachment, domain identity, shared networking and security-center activation require enterprise administrators. Never test them in a production organization without a reviewed plan and rollback strategy.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'terraform/bootstrap/versions.tf' @'
terraform {
  required_version = ">= 1.8.0"
  required_providers {
    google = { source = "hashicorp/google", version = "~> 7.0" }
  }
}
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'terraform/bootstrap/main.tf' @'
provider "google" {}

resource "google_folder" "platform" {
  display_name = "${var.prefix}-${var.environment}-platform"
  parent       = "organizations/${var.organization_id}"
}

locals {
  projects = {
    network  = "${var.prefix}-${var.environment}-net-${var.unique_suffix}"
    security = "${var.prefix}-${var.environment}-sec-${var.unique_suffix}"
    workload = "${var.prefix}-${var.environment}-app-${var.unique_suffix}"
  }
  common_services = ["cloudresourcemanager.googleapis.com", "serviceusage.googleapis.com", "iam.googleapis.com", "logging.googleapis.com", "monitoring.googleapis.com"]
}

resource "google_project" "platform" {
  for_each            = local.projects
  name                = each.value
  project_id          = each.value
  folder_id           = google_folder.platform.name
  billing_account     = var.billing_account
  auto_create_network = false
  labels              = merge(var.labels, { purpose = each.key })
}

resource "google_project_service" "common" {
  for_each           = { for item in setproduct(keys(local.projects), local.common_services) : "${item[0]}:${item[1]}" => { project = item[0], service = item[1] } }
  project            = google_project.platform[each.value.project].project_id
  service            = each.value.service
  disable_on_destroy = false
}

resource "google_project_iam_member" "security_viewer" {
  for_each = google_project.platform
  project  = each.value.project_id
  role     = "roles/viewer"
  member   = "group:${var.security_group}"
}
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'terraform/bootstrap/variables.tf' @'
variable "organization_id" { type = string }
variable "billing_account" { type = string }
variable "prefix" {
  type    = string
  default = "masterclass"
}
variable "environment" {
  type    = string
  default = "dev"
}
variable "unique_suffix" {
  type        = string
  description = "Globally unique lowercase suffix."
}
variable "security_group" {
  type    = string
  default = "cloud-security@example.com"
}
variable "labels" {
  type    = map(string)
  default = { managed_by = "terraform", owner = "replace-with-owner", cost_center = "replace" }
}
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'terraform/bootstrap/outputs.tf' @'
output "folder_id" { value = google_folder.platform.name }
output "project_ids" { value = { for key, project in google_project.platform : key => project.project_id } }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'terraform/bootstrap/terraform.tfvars.example' @'
organization_id = "123456789012"
billing_account  = "000000-000000-000000"
unique_suffix    = "replace"
security_group   = "cloud-security@example.com"
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'terraform/workload/versions.tf' @'
terraform {
  required_version = ">= 1.8.0"
  required_providers {
    google = { source = "hashicorp/google", version = "~> 7.0" }
  }
}
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'terraform/workload/main.tf' @'
provider "google" {
  project = var.project_id
  region  = var.region
}

locals { services = toset(["artifactregistry.googleapis.com", "binaryauthorization.googleapis.com", "container.googleapis.com", "cloudkms.googleapis.com", "pubsub.googleapis.com", "secretmanager.googleapis.com", "compute.googleapis.com"]) }
resource "google_project_service" "platform" {
  for_each           = local.services
  project            = var.project_id
  service            = each.value
  disable_on_destroy = false
}

resource "google_compute_network" "platform" {
  name                    = "${var.prefix}-${var.environment}-vpc"
  auto_create_subnetworks = false
  routing_mode            = "GLOBAL"
  depends_on              = [google_project_service.platform]
}
resource "google_compute_subnetwork" "gke" {
  name                     = "${var.prefix}-${var.environment}-gke"
  ip_cidr_range            = "10.80.0.0/20"
  region                   = var.region
  network                  = google_compute_network.platform.id
  private_ip_google_access = true
  secondary_ip_range {
    range_name    = "pods"
    ip_cidr_range = "10.84.0.0/14"
  }
  secondary_ip_range {
    range_name    = "services"
    ip_cidr_range = "10.88.0.0/20"
  }
  log_config {
    aggregation_interval = "INTERVAL_5_SEC"
    flow_sampling        = 0.5
    metadata             = "INCLUDE_ALL_METADATA"
  }
}
resource "google_compute_router" "platform" {
  name    = "${var.prefix}-${var.environment}-router"
  region  = var.region
  network = google_compute_network.platform.id
}
resource "google_compute_router_nat" "platform" {
  name                               = "${var.prefix}-${var.environment}-nat"
  router                             = google_compute_router.platform.name
  region                             = var.region
  nat_ip_allocate_option             = "AUTO_ONLY"
  source_subnetwork_ip_ranges_to_nat = "LIST_OF_SUBNETWORKS"
  subnetwork {
    name                    = google_compute_subnetwork.gke.id
    source_ip_ranges_to_nat = ["ALL_IP_RANGES"]
  }
  log_config {
    enable = true
    filter = "ERRORS_ONLY"
  }
}

resource "google_kms_key_ring" "platform" {
  name       = "${var.prefix}-${var.environment}"
  location   = var.region
  depends_on = [google_project_service.platform]
}
resource "google_kms_crypto_key" "gke" {
  name            = "gke-secrets"
  key_ring        = google_kms_key_ring.platform.id
  rotation_period = "7776000s"
  lifecycle { prevent_destroy = true }
}
resource "google_artifact_registry_repository" "platform" {
  location               = var.region
  repository_id          = "${var.prefix}-${var.environment}"
  format                 = "DOCKER"
  description            = "Promoted signed workload images"
  cleanup_policy_dry_run = true
  depends_on             = [google_project_service.platform]
}
resource "google_pubsub_topic" "events" {
  name                       = "platform-events"
  message_retention_duration = "604800s"
  depends_on                 = [google_project_service.platform]
}
resource "google_secret_manager_secret" "sample" {
  secret_id = "sample-api-config"
  replication {
    auto {}
  }
  depends_on = [google_project_service.platform]
}

resource "google_container_cluster" "platform" {
  name                     = "${var.prefix}-${var.environment}-gke"
  location                 = var.region
  network                  = google_compute_network.platform.id
  subnetwork               = google_compute_subnetwork.gke.id
  networking_mode          = "VPC_NATIVE"
  datapath_provider        = "ADVANCED_DATAPATH"
  remove_default_node_pool = true
  initial_node_count       = 1
  deletion_protection      = true
  release_channel { channel = "REGULAR" }
  workload_identity_config { workload_pool = "${var.project_id}.svc.id.goog" }
  binary_authorization { evaluation_mode = "PROJECT_SINGLETON_POLICY_ENFORCE" }
  private_cluster_config {
    enable_private_nodes    = true
    enable_private_endpoint = var.private_endpoint
    master_ipv4_cidr_block  = "172.20.0.0/28"
  }
  ip_allocation_policy {
    cluster_secondary_range_name  = "pods"
    services_secondary_range_name = "services"
  }
  master_authorized_networks_config {
    cidr_blocks {
      cidr_block   = var.admin_cidr
      display_name = "platform-admin"
    }
  }
  logging_config { enable_components = ["SYSTEM_COMPONENTS", "WORKLOADS", "APISERVER", "SCHEDULER", "CONTROLLER_MANAGER"] }
  monitoring_config {
    enable_components = ["SYSTEM_COMPONENTS", "APISERVER", "SCHEDULER", "CONTROLLER_MANAGER", "STORAGE", "POD", "DEPLOYMENT", "STATEFULSET", "DAEMONSET", "HPA"]
    managed_prometheus { enabled = true }
  }
  database_encryption {
    state    = "ENCRYPTED"
    key_name = google_kms_crypto_key.gke.id
  }
  resource_labels = var.labels
  depends_on      = [google_project_service.platform]
}
resource "google_container_node_pool" "system" {
  name       = "system"
  location   = var.region
  cluster    = google_container_cluster.platform.name
  node_count = 1
  autoscaling {
    min_node_count  = 1
    max_node_count  = 3
    location_policy = "BALANCED"
  }
  management {
    auto_repair  = true
    auto_upgrade = true
  }
  node_config {
    machine_type    = "e2-standard-4"
    disk_type       = "pd-balanced"
    disk_size_gb    = 100
    image_type      = "COS_CONTAINERD"
    service_account = google_service_account.nodes.email
    oauth_scopes    = ["https://www.googleapis.com/auth/cloud-platform"]
    shielded_instance_config {
      enable_secure_boot          = true
      enable_integrity_monitoring = true
    }
    labels = { pool = "system" }
    workload_metadata_config { mode = "GKE_METADATA" }
  }
}
resource "google_service_account" "nodes" {
  account_id   = "gke-node"
  display_name = "Least privilege GKE node identity"
}
resource "google_project_iam_member" "node_roles" {
  for_each = toset(["roles/logging.logWriter", "roles/monitoring.metricWriter", "roles/monitoring.viewer", "roles/artifactregistry.reader"])
  project  = var.project_id
  role     = each.value
  member   = "serviceAccount:${google_service_account.nodes.email}"
}
resource "google_service_account" "workload" {
  account_id   = "sample-api"
  display_name = "Sample workload identity"
}
resource "google_service_account_iam_member" "workload_identity" {
  service_account_id = google_service_account.workload.name
  role               = "roles/iam.workloadIdentityUser"
  member             = "serviceAccount:${var.project_id}.svc.id.goog[sample/sample-api]"
}
resource "google_secret_manager_secret_iam_member" "sample" {
  project   = var.project_id
  secret_id = google_secret_manager_secret.sample.secret_id
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${google_service_account.workload.email}"
}
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'terraform/workload/variables.tf' @'
variable "project_id" { type = string }
variable "prefix" {
  type    = string
  default = "masterclass"
}
variable "environment" {
  type    = string
  default = "dev"
}
variable "region" {
  type    = string
  default = "asia-south1"
}
variable "private_endpoint" {
  type    = bool
  default = true
}
variable "admin_cidr" {
  type    = string
  default = "10.0.0.0/8"
}
variable "labels" {
  type    = map(string)
  default = { managed_by = "terraform", owner = "replace-with-owner", cost_center = "replace" }
}
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'terraform/workload/outputs.tf' @'
output "cluster_name" { value = google_container_cluster.platform.name }
output "registry" { value = google_artifact_registry_repository.platform.name }
output "workload_service_account" { value = google_service_account.workload.email }
output "configure_kubectl" { value = "gcloud container clusters get-credentials ${google_container_cluster.platform.name} --region ${var.region} --project ${var.project_id}" }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'terraform/workload/terraform.tfvars.example' @'
project_id       = "masterclass-dev-app-replace"
region           = "asia-south1"
private_endpoint = true
admin_cidr       = "10.0.0.0/8"
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'k8s/namespace.yaml' @'
apiVersion: v1
kind: Namespace
metadata: { name: sample, labels: { pod-security.kubernetes.io/enforce: restricted } }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'k8s/workload.yaml' @'
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sample-api
  namespace: sample
  annotations: { iam.gke.io/gcp-service-account: sample-api@replace.iam.gserviceaccount.com }
---
apiVersion: apps/v1
kind: Deployment
metadata: { name: sample-api, namespace: sample }
spec:
  replicas: 2
  selector: { matchLabels: { app: sample-api } }
  template:
    metadata: { labels: { app: sample-api } }
    spec:
      serviceAccountName: sample-api
      securityContext: { runAsNonRoot: true, seccompProfile: { type: RuntimeDefault } }
      containers:
        - name: app
          image: asia-south1-docker.pkg.dev/replace/platform/sample-api@sha256:replace
          ports: [{ name: http, containerPort: 8080 }]
          resources: { requests: { cpu: 50m, memory: 64Mi }, limits: { cpu: 500m, memory: 256Mi } }
          securityContext: { allowPrivilegeEscalation: false, readOnlyRootFilesystem: true, capabilities: { drop: [ALL] } }
---
apiVersion: v1
kind: Service
metadata: { name: sample-api, namespace: sample }
spec: { selector: { app: sample-api }, ports: [{ name: http, port: 80, targetPort: http }] }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'k8s/networkpolicy.yaml' @'
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata: { name: default-deny, namespace: sample }
spec: { podSelector: {}, policyTypes: [Ingress, Egress] }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'k8s/kustomization.yaml' @'
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [namespace.yaml, workload.yaml, networkpolicy.yaml]
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'app/__init__.py' '' -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'app/main.py' @'
import json
import os
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer


def response_for(path: str) -> tuple[int, dict[str, str]]:
    if path == "/healthz":
        return 200, {"status": "ok"}
    return 404, {"error": "not_found"}


class Handler(BaseHTTPRequestHandler):
    def do_GET(self) -> None:
        status, body = response_for(self.path)
        payload = json.dumps(body).encode()
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(payload)))
        self.end_headers()
        self.wfile.write(payload)

    def log_message(self, format: str, *args: object) -> None:
        return


if __name__ == "__main__":
    port = int(os.getenv("PORT", "8080"))
    ThreadingHTTPServer(("0.0.0.0", port), Handler).serve_forever()
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'app/Dockerfile' @'
FROM python:3.14.1-slim
RUN groupadd --gid 10001 app && useradd --uid 10001 --gid app --no-create-home app
WORKDIR /app
COPY --chown=10001:10001 main.py .
USER 10001:10001
EXPOSE 8080
HEALTHCHECK --interval=30s --timeout=3s CMD ["python", "-c", "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8080/healthz', timeout=2)"]
CMD ["python", "main.py"]
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'tests/test_contract.py' @'
import unittest

from app.main import response_for


class ApiContractTests(unittest.TestCase):
    def test_health_contract(self):
        self.assertEqual(response_for("/healthz"), (200, {"status": "ok"}))

    def test_unknown_route_is_not_found(self):
        self.assertEqual(response_for("/missing")[0], 404)


if __name__ == "__main__":
    unittest.main()
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'cloudbuild.yaml' @'
options: { logging: CLOUD_LOGGING_ONLY, requestedVerifyOption: VERIFIED }
steps:
  - name: python:3.14.1-slim
    entrypoint: python
    args: [-m, unittest, discover, -s, tests, -v]
  - name: gcr.io/cloud-builders/docker
    args: [build, -f, app/Dockerfile, -t, "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/sample-api:$COMMIT_SHA", app]
  - name: gcr.io/cloud-builders/docker
    args: [push, "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/sample-api:$COMMIT_SHA"]
images: ["${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/sample-api:$COMMIT_SHA"]
substitutions: { _REGION: asia-south1, _REPOSITORY: masterclass-dev }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'scripts/validate.ps1' @'
$ErrorActionPreference='Stop'
foreach($directory in @('terraform/bootstrap','terraform/workload')){terraform -chdir=$directory fmt -check -recursive;if($LASTEXITCODE){throw "Terraform format failed: $directory"}}
kubectl kustomize k8s | Out-Null
Write-Host 'GCP platform contracts validated.'
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root '.github/workflows/ci.yml' @'
name: gcp-platform-ci
on: { pull_request: {}, push: { branches: [main] } }
permissions: { contents: read }
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
        with: { terraform_version: 1.13.5 }
      - run: python -m unittest discover -s tests -v
      - run: terraform -chdir=terraform/bootstrap fmt -check -recursive
      - run: terraform -chdir=terraform/bootstrap init -backend=false && terraform -chdir=terraform/bootstrap validate
      - run: terraform -chdir=terraform/workload fmt -check -recursive
      - run: terraform -chdir=terraform/workload init -backend=false && terraform -chdir=terraform/workload validate
      - run: kubectl kustomize k8s >/tmp/gcp-workload.yaml
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/HLD.md' @'
# High-level design

The organization hierarchy separates network, security and workload ownership. Projects inherit organization policy and centralized audit controls. Private regional GKE consumes Shared VPC patterns, Artifact Registry and KMS. Terraform controls cloud resources, while GitOps controls cluster workloads.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/LLD.md' @'
# Low-level design

Bootstrap state creates the folder/projects and is administered separately from workload state. Workload state enables APIs, VPC-native ranges, Cloud NAT, regional private GKE, CMEK, Binary Authorization, managed Prometheus, Pub/Sub and secretless workload identity. Production should use remote state, Shared VPC host/service projects, private service access and explicit organization policies.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/RUNBOOK.md' @'
# GCP platform runbook

For access failures separate organization IAM, project IAM, Workload Identity, private DNS/network and Kubernetes RBAC. Investigate denied deployments through Binary Authorization attestations and digest identity. Recreate GKE from Terraform and GitOps instead of restoring the control plane. Restore stateful services through service-specific backups and record regional recovery evidence.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/THREAT-MODEL.md' @'
# Threat model

Threats include organization-policy bypass, service-account keys, Shared VPC lateral movement, public control-plane access, image substitution, excessive node scopes, log-sink tampering and billing abuse. Controls include hierarchy inheritance, Workload Identity, private clusters, least-privilege service accounts, Binary Authorization, CMEK, VPC flow logs, centralized immutable audit exports and budgets.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/COST-AND-DR.md' @'
# Cost and disaster recovery

Allocate costs using project, label, namespace and team. Budget for regional GKE, logging volume, NAT, cross-region egress, Artifact Registry retention, KMS and backups. Choose regional recovery tiers explicitly. Rehearse project/bootstrap restoration, cluster recreation, registry replication, secret recovery, Pub/Sub replay and application data restoration.
'@ -WhatIfMode:$WhatIfMode
[pscustomobject]@{Project='25-gcp-enterprise-platform';Root=$root;Files=$script:Generated.Count}
