param([switch]$WhatIfMode)
. (Join-Path $PSScriptRoot 'Common.ps1')
$root=Join-Path $script:ProjectsRoot '26-reliability-disaster-recovery-lab'
Write-TemplateFile $root '.template-owned' 'Generated by tools/module20-projects. Additional user files are never deleted.' -WhatIfMode:$WhatIfMode
Write-TemplateFile $root '.gitignore' @'
.env
__pycache__/
.terraform/
*.tfstate*
evidence/*.actual.json
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root '.env.example' @'
APP_PORT=8106
POSTGRES_USER=app
POSTGRES_PASSWORD=local-development-only
POSTGRES_DB=orders
DATABASE_URL=postgresql://app:local-development-only@toxiproxy:5433/orders
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'README.md' @'
# Reliability and Disaster-Recovery Engineering Lab

A measurable SRE capstone combining a fault-aware FastAPI/PostgreSQL workload, Toxiproxy dependency injection, k6 load tests, Chaos Mesh experiments, PodDisruptionBudgets, Velero backup schedules, restore jobs, multi-region DNS Terraform, error budgets and scored game-day evidence.

```mermaid
flowchart LR
    Load[k6 load] --> API[Order API]
    API --> Proxy[Toxiproxy]
    Proxy --> DB[(PostgreSQL)]
    Chaos[Chaos Mesh] --> API
    Chaos --> DB
    Metrics --> SLO[SLI and error budget]
    Backup[Velero and pg_dump] --> Restore[Restore drill]
    Primary[Primary region] --> DNS[Failover DNS]
    DNS --> Secondary[Recovery region]
```

## Required game days

1. Inject 500 ms database latency, then a 20-second outage; measure detection, mitigation and recovery.
2. Delete pods and drain a node while k6 holds steady load; verify the PDB and readiness behavior.
3. Restore a database backup into an isolated namespace and verify data checksums, not just Job success.
4. Simulate regional loss and perform a controlled DNS failover; record measured RTO, RPO and stale-write risk.
5. Exhaust the monthly error budget and prove release policy changes automatically.

## Local start

```bash
cp .env.example .env
docker compose up --build -d
python -m unittest discover -s tests -v
k6 run load/order-api.js
powershell -File scripts/set-db-latency.ps1 -LatencyMs 500
python scripts/score_game_day.py evidence/example.json
```

Chaos and recovery resources are deliberately not auto-applied. Establish blast radius, steady-state hypothesis, abort conditions, owner approval and backup proof before every experiment.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'app/requirements.txt' @'
fastapi==0.141.1
uvicorn==0.52.3
asyncpg==0.31.0
prometheus-client==0.26.0
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'app/main.py' @'
import asyncio
import os
import time
import uuid
import asyncpg
from fastapi import FastAPI,HTTPException
from pydantic import BaseModel,Field
from prometheus_client import Counter,Histogram,make_asgi_app

app=FastAPI(title="Reliability Lab Order API",version="1.0.0")
pool=None
requests=Counter("order_requests_total","Order requests",["result"])
latency=Histogram("order_request_seconds","Order request latency")

class Order(BaseModel):
 sku:str=Field(pattern=r"^[A-Z0-9-]{3,32}$")
 quantity:int=Field(gt=0,le=100)

@app.on_event("startup")
async def startup():
 global pool
 for attempt in range(30):
  try:
   pool=await asyncpg.create_pool(os.environ["DATABASE_URL"],min_size=1,max_size=10,command_timeout=2)
   async with pool.acquire() as connection:
    await connection.execute("CREATE TABLE IF NOT EXISTS orders(id uuid PRIMARY KEY,sku varchar(32) NOT NULL,quantity integer NOT NULL,created_at timestamptz NOT NULL DEFAULT now())")
   return
  except Exception:
   if attempt==29:raise
   await asyncio.sleep(1)

@app.on_event("shutdown")
async def shutdown():
 if pool:await pool.close()

@app.get("/health")
async def health():return {"status":"ok"}

@app.get("/ready")
async def ready():
 try:
  async with pool.acquire() as connection:await connection.fetchval("SELECT 1")
  return {"status":"ready"}
 except Exception as error:raise HTTPException(503,"database unavailable") from error

@app.post("/api/orders",status_code=201)
async def create(order:Order):
 started=time.perf_counter()
 try:
  identifier=uuid.uuid4()
  async with pool.acquire() as connection:await connection.execute("INSERT INTO orders(id,sku,quantity) VALUES($1,$2,$3)",identifier,order.sku,order.quantity)
  requests.labels("success").inc()
  return {"id":str(identifier),**order.model_dump()}
 except Exception as error:
  requests.labels("failure").inc()
  raise HTTPException(503,"dependency unavailable") from error
 finally:latency.observe(time.perf_counter()-started)

app.mount("/metrics",make_asgi_app())
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'app/Dockerfile' @'
FROM python:3.14.1-slim
RUN groupadd -g 10001 app && useradd -u 10001 -g app --no-create-home app
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY --chown=app:app main.py .
USER 10001:10001
EXPOSE 8080
CMD ["uvicorn","main:app","--host","0.0.0.0","--port","8080"]
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docker-compose.yml' @'
services:
  postgres:
    image: postgres:16-alpine
    environment: { POSTGRES_USER: "${POSTGRES_USER:-app}", POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-local-development-only}", POSTGRES_DB: "${POSTGRES_DB:-orders}" }
    volumes: [postgres-data:/var/lib/postgresql/data]
    healthcheck: { test: [CMD-SHELL, "pg_isready -U ${POSTGRES_USER:-app} -d ${POSTGRES_DB:-orders}"], interval: 3s, timeout: 2s, retries: 30 }
    networks: [data]
  toxiproxy:
    image: ghcr.io/shopify/toxiproxy:2.12.0
    ports: ["8474:8474"]
    depends_on: { postgres: { condition: service_healthy } }
    networks: [edge,data]
  proxy-init:
    image: curlimages/curl:8.16.0
    command: ["-fsS","-X","POST","http://toxiproxy:8474/proxies","-H","Content-Type: application/json","-d","{\"name\":\"postgres\",\"listen\":\"0.0.0.0:5433\",\"upstream\":\"postgres:5432\"}"]
    depends_on: { toxiproxy: { condition: service_started } }
    restart: on-failure
    networks: [edge]
  api:
    build: app
    environment: { DATABASE_URL: "${DATABASE_URL:-postgresql://app:local-development-only@toxiproxy:5433/orders}" }
    ports: ["${APP_PORT:-8106}:8080"]
    depends_on: { proxy-init: { condition: service_completed_successfully } }
    read_only: true
    tmpfs: [/tmp]
    cap_drop: [ALL]
    security_opt: [no-new-privileges:true]
    networks: [edge]
networks: { edge: {}, data: { internal: true } }
volumes: { postgres-data: {} }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'reliability/budgets.py' @'
from dataclasses import dataclass
@dataclass(frozen=True)
class Objectives:rto_seconds:int;rpo_seconds:int;availability_percent:float
def score(evidence,objectives):
 required={"detection_seconds","recovery_seconds","data_loss_seconds","successful_requests","total_requests"}
 missing=required-evidence.keys()
 if missing:raise ValueError("missing evidence: "+",".join(sorted(missing)))
 total=int(evidence["total_requests"]);successful=int(evidence["successful_requests"])
 if total<=0 or not 0<=successful<=total:raise ValueError("invalid request counts")
 availability=100*successful/total
 checks={"detected":evidence["detection_seconds"]<=60,"rto_met":evidence["recovery_seconds"]<=objectives.rto_seconds,"rpo_met":evidence["data_loss_seconds"]<=objectives.rpo_seconds,"availability_met":availability>=objectives.availability_percent}
 return {"availability_percent":round(availability,4),"checks":checks,"passed":all(checks.values())}
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'scripts/score_game_day.py' @'
import json,pathlib,sys
sys.path.insert(0,str(pathlib.Path(__file__).parents[1]));from reliability.budgets import Objectives,score
if len(sys.argv)!=2:raise SystemExit("usage: score_game_day.py evidence.json")
evidence=json.loads(pathlib.Path(sys.argv[1]).read_text());result=score(evidence,Objectives(rto_seconds=300,rpo_seconds=60,availability_percent=99.0));print(json.dumps(result,indent=2));raise SystemExit(0 if result["passed"] else 2)
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'scripts/set-db-latency.ps1' @'
param([ValidateRange(0,10000)][int]$LatencyMs=500)
$ErrorActionPreference='Stop'
$body=@{type='latency';attributes=@{latency=$LatencyMs;jitter=50}}|ConvertTo-Json -Compress
Invoke-RestMethod -Method Post -Uri http://localhost:8474/proxies/postgres/toxics -ContentType application/json -Body $body
Write-Host "Injected ${LatencyMs}ms PostgreSQL latency. Remove with: Invoke-RestMethod -Method Delete http://localhost:8474/proxies/postgres/toxics/latency_downstream"
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'tests/test_budgets.py' @'
import unittest
from reliability.budgets import Objectives,score
OBJECTIVES=Objectives(300,60,99.0)
class BudgetTests(unittest.TestCase):
 def test_passes_measured_objectives(self):self.assertTrue(score({"detection_seconds":30,"recovery_seconds":180,"data_loss_seconds":10,"successful_requests":999,"total_requests":1000},OBJECTIVES)["passed"])
 def test_fails_rto(self):self.assertFalse(score({"detection_seconds":30,"recovery_seconds":301,"data_loss_seconds":10,"successful_requests":999,"total_requests":1000},OBJECTIVES)["passed"])
 def test_rejects_invalid_counts(self):
  with self.assertRaises(ValueError):score({"detection_seconds":1,"recovery_seconds":1,"data_loss_seconds":1,"successful_requests":2,"total_requests":1},OBJECTIVES)
if __name__=="__main__":unittest.main()
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'evidence/example.json' @'
{"experiment":"database-latency","started_at":"2026-01-01T00:00:00Z","detection_seconds":25,"recovery_seconds":180,"data_loss_seconds":0,"successful_requests":9950,"total_requests":10000,"backup_id":"replace","restore_checksum":"replace","incident_owner":"replace"}
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'load/order-api.js' @'
import http from 'k6/http';import {check,sleep} from 'k6';export const options={scenarios:{steady:{executor:'constant-arrival-rate',rate:20,timeUnit:'1s',duration:'5m',preAllocatedVUs:20,maxVUs:100}},thresholds:{http_req_failed:['rate<0.01'],http_req_duration:['p(95)<500']}};export default function(){const response=http.post(`${__ENV.BASE_URL||'http://localhost:8106'}/api/orders`,JSON.stringify({sku:'SKU-1',quantity:1}),{headers:{'Content-Type':'application/json'}});check(response,{'accepted or controlled failure':r=>r.status===201||r.status===503});sleep(0.1)}
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'k8s/base.yaml' @'
apiVersion: v1
kind: Namespace
metadata: { name: reliability-lab, labels: { pod-security.kubernetes.io/enforce: restricted } }
---
apiVersion: apps/v1
kind: Deployment
metadata: { name: order-api, namespace: reliability-lab }
spec:
  replicas: 3
  selector: { matchLabels: { app: order-api } }
  template:
    metadata: { labels: { app: order-api } }
    spec:
      securityContext: { runAsNonRoot: true, seccompProfile: { type: RuntimeDefault } }
      containers:
        - name: api
          image: ghcr.io/replace/order-api@sha256:replace
          env: [{ name: DATABASE_URL, valueFrom: { secretKeyRef: { name: database, key: url } } }]
          ports: [{ name: http, containerPort: 8080 }]
          resources: { requests: { cpu: 100m, memory: 128Mi }, limits: { cpu: "1", memory: 512Mi } }
          readinessProbe: { httpGet: { path: /ready, port: http }, periodSeconds: 3, timeoutSeconds: 2, failureThreshold: 2 }
          livenessProbe: { httpGet: { path: /health, port: http }, initialDelaySeconds: 10 }
          securityContext: { allowPrivilegeEscalation: false, readOnlyRootFilesystem: true, capabilities: { drop: [ALL] } }
---
apiVersion: v1
kind: Service
metadata: { name: order-api, namespace: reliability-lab }
spec: { selector: { app: order-api }, ports: [{ name: http, port: 80, targetPort: http }] }
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata: { name: order-api, namespace: reliability-lab }
spec: { minAvailable: 2, selector: { matchLabels: { app: order-api } } }
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: { name: order-api, namespace: reliability-lab }
spec: { scaleTargetRef: { apiVersion: apps/v1, kind: Deployment, name: order-api }, minReplicas: 3, maxReplicas: 12, metrics: [{ type: Resource, resource: { name: cpu, target: { type: Utilization, averageUtilization: 65 } } }] }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'k8s/chaos.yaml' @'
apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata: { name: order-api-single-pod, namespace: reliability-lab }
spec: { action: pod-kill, mode: one, selector: { namespaces: [reliability-lab], labelSelectors: { app: order-api } }, duration: 30s }
---
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata: { name: database-latency, namespace: reliability-lab }
spec:
  action: delay
  mode: all
  selector: { namespaces: [reliability-lab], labelSelectors: { app: order-api } }
  delay: { latency: 500ms, correlation: "100", jitter: 50ms }
  direction: to
  target: { mode: all, selector: { namespaces: [database], labelSelectors: { app: postgres } } }
  duration: 5m
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'k8s/recovery.yaml' @'
apiVersion: velero.io/v1
kind: Schedule
metadata: { name: reliability-lab-daily, namespace: velero }
spec: { schedule: "0 2 * * *", template: { includedNamespaces: [reliability-lab], snapshotVolumes: true, storageLocation: default, ttl: 720h0m0s } }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: { name: postgres-backups, namespace: reliability-lab }
spec:
  accessModes: [ReadWriteOnce]
  resources: { requests: { storage: 20Gi } }
---
apiVersion: batch/v1
kind: CronJob
metadata: { name: postgres-logical-backup, namespace: reliability-lab }
spec:
  schedule: "15 2 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: backup
              image: postgres:16-alpine
              command: [sh, -ec, "pg_dump --format=custom --file=/backup/orders-$(date +%s).dump $DATABASE_URL"]
              env: [{ name: DATABASE_URL, valueFrom: { secretKeyRef: { name: database, key: url } } }]
              volumeMounts: [{ name: backup, mountPath: /backup }]
              resources: { requests: { cpu: 100m, memory: 128Mi }, limits: { cpu: "1", memory: 512Mi } }
              securityContext: { allowPrivilegeEscalation: false, capabilities: { drop: [ALL] } }
          volumes: [{ name: backup, persistentVolumeClaim: { claimName: postgres-backups } }]
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'k8s/kustomization.yaml' @'
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [base.yaml, chaos.yaml, recovery.yaml]
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'terraform/versions.tf' @'
terraform {
  required_version = ">= 1.8.0"
  required_providers {
    aws    = { source = "hashicorp/aws", version = "~> 6.0" }
    random = { source = "hashicorp/random", version = "~> 3.7" }
  }
}
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'terraform/main.tf' @'
provider "aws" { region = var.primary_region }
provider "aws" {
  alias  = "secondary"
  region = var.secondary_region
}
resource "random_id" "suffix" { byte_length = 4 }
locals { bucket_name = "${var.project_name}-${var.environment}-dr-${random_id.suffix.hex}" }
resource "aws_s3_bucket" "primary" {
  bucket        = "${local.bucket_name}-primary"
  force_destroy = false
  tags          = var.tags
}
resource "aws_s3_bucket" "secondary" {
  provider      = aws.secondary
  bucket        = "${local.bucket_name}-secondary"
  force_destroy = false
  tags          = var.tags
}
resource "aws_s3_bucket_versioning" "primary" {
  bucket = aws_s3_bucket.primary.id
  versioning_configuration { status = "Enabled" }
}
resource "aws_s3_bucket_versioning" "secondary" {
  provider = aws.secondary
  bucket   = aws_s3_bucket.secondary.id
  versioning_configuration { status = "Enabled" }
}
resource "aws_s3_bucket_server_side_encryption_configuration" "primary" {
  bucket = aws_s3_bucket.primary.id
  rule {
    apply_server_side_encryption_by_default { sse_algorithm = "AES256" }
  }
}
resource "aws_s3_bucket_server_side_encryption_configuration" "secondary" {
  provider = aws.secondary
  bucket   = aws_s3_bucket.secondary.id
  rule {
    apply_server_side_encryption_by_default { sse_algorithm = "AES256" }
  }
}
resource "aws_s3_bucket_public_access_block" "primary" {
  bucket                  = aws_s3_bucket.primary.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}
resource "aws_s3_bucket_public_access_block" "secondary" {
  provider                = aws.secondary
  bucket                  = aws_s3_bucket.secondary.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'terraform/variables.tf' @'
variable "project_name" {
  type    = string
  default = "reliability-lab"
}
variable "environment" {
  type    = string
  default = "dev"
}
variable "primary_region" {
  type    = string
  default = "us-east-1"
}
variable "secondary_region" {
  type    = string
  default = "us-west-2"
}
variable "tags" {
  type    = map(string)
  default = { Owner = "replace-with-owner", CostCenter = "replace", ManagedBy = "Terraform" }
}
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'terraform/outputs.tf' @'
output "primary_backup_bucket" { value = aws_s3_bucket.primary.id }
output "secondary_backup_bucket" { value = aws_s3_bucket.secondary.id }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root '.github/workflows/ci.yml' @'
name: reliability-ci
on: { pull_request: {}, push: { branches: [main] } }
permissions: { contents: read }
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: python -m unittest discover -s tests -v
      - run: python -m py_compile app/main.py reliability/*.py scripts/*.py
      - run: docker compose config --quiet
      - run: kubectl kustomize k8s >/tmp/reliability.yaml
      - uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
        with: { terraform_version: 1.13.5 }
      - run: terraform -chdir=terraform fmt -check -recursive
      - run: terraform -chdir=terraform init -backend=false && terraform -chdir=terraform validate
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/HLD.md' @'
# High-level design

The lab separates availability, durability and recoverability. Load establishes steady state; Toxiproxy and Chaos Mesh introduce controlled faults; SLIs quantify user impact; backup/restore and regional infrastructure prove recovery. Evidence is machine-scored against explicit objectives rather than declared successful by observation alone.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/GAME-DAY.md' @'
# Game-day method

Record hypothesis, blast radius, owner, abort signal, baseline, exact fault, timestamps, alerts, actions, customer impact, data loss, recovery checksum and follow-up owner. Start in an isolated environment. Stop immediately if blast radius escapes, observability is lost, backups are unverified or an on-call owner withdraws approval.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/RUNBOOK.md' @'
# Reliability runbook

Declare an incident from user-facing symptoms, not infrastructure noise. Stabilize writes before failover when split-brain is possible. Preserve evidence, identify last durable transaction, restore into isolation, validate checksums and business invariants, then promote. DNS failover is not database failover. After recovery, calculate budget consumed and block risky releases when policy requires it.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/THREAT-MODEL.md' @'
# Threat model

Chaos tools and backup credentials are privileged. Threats include production-wide fault injection, forged evidence, backup deletion, restore-time malware, cross-region credential reuse and failover hijacking. Controls include dedicated service accounts, namespace/label allowlists, time-bound approvals, immutable backup copies, separate restore accounts, signed evidence, audit logs and tested kill switches.
'@ -WhatIfMode:$WhatIfMode
[pscustomobject]@{Project='26-reliability-disaster-recovery-lab';Root=$root;Files=$script:Generated.Count}
