param([switch]$WhatIfMode)
. (Join-Path $PSScriptRoot 'Common.ps1')
$root=Join-Path $script:ProjectsRoot '28-istio-zero-trust-multicluster-mesh'
Write-TemplateFile $root '.template-owned' 'Generated by tools/module20-projects. Additional user files are never deleted.' -WhatIfMode:$WhatIfMode
Write-TemplateFile $root '.gitignore' @'
__pycache__/
.env
rendered/
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'README.md' @'
# Istio Ambient Zero-Trust and Multi-Cluster Service Mesh

A platform-networking capstone for Istio 1.30 ambient mode, Gateway API, waypoint proxies, workload identity, strict mTLS, authorization, traffic management, multi-cluster topology and mesh observability.

```mermaid
flowchart LR
  U[Client] --> G[Gateway API]
  G --> C[Catalog service]
  C -->|mTLS + L7 policy| I[Inventory service]
  Z[ztunnel] --- C
  Z --- I
  W[Waypoint] --- C
  CP[Istiod] --> Z
  CP --> W
  E[Cluster east] <-->|east-west gateway| F[Cluster west]
```

## Outcomes

- Build a sidecarless ambient mesh and explain ztunnel versus waypoint responsibilities.
- Enforce default-deny L4/L7 policy with SPIFFE-style service identity and strict mTLS.
- Route with Kubernetes Gateway API, retries, timeouts and controlled egress.
- Model primary-primary multi-cluster failure, certificate trust and locality-aware recovery.
- Validate mesh policy as code before applying it to a cluster.

## Start

```powershell
python -m unittest discover -s tests -v
kubectl kustomize k8s
./scripts/validate.ps1
```

Install Gateway API CRDs and Istio 1.30 with `helm/istio-values.yaml` before applying the rendered resources. The two kind configurations are deliberately separate so you can practice trust-domain and east-west-gateway setup without touching a shared cluster.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'meshguard/__init__.py' '' -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'meshguard/rules.py' @'
REQUIRED_CONTROLS={"strict_mtls","default_deny","explicit_allow","bounded_timeout","telemetry"}

def evaluate(control_sets:dict[str,set[str]])->dict[str,list[str]]:
    if not control_sets:
        raise ValueError("at least one namespace is required")
    return {namespace:sorted(REQUIRED_CONTROLS-controls) for namespace,controls in control_sets.items()}

def promotion_allowed(control_sets:dict[str,set[str]])->bool:
    return all(not missing for missing in evaluate(control_sets).values())

def trust_domains_compatible(primary:str,remote:str,aliases:set[str])->bool:
    return primary==remote or remote in aliases
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'tests/test_rules.py' @'
import unittest
from meshguard.rules import evaluate,promotion_allowed,trust_domains_compatible

class MeshPolicyTests(unittest.TestCase):
 def test_complete_namespace_passes(self):
  controls={"strict_mtls","default_deny","explicit_allow","bounded_timeout","telemetry"}
  self.assertTrue(promotion_allowed({"shop":controls}))
 def test_missing_default_deny_fails(self):
  missing=evaluate({"shop":{"strict_mtls","explicit_allow","bounded_timeout","telemetry"}})
  self.assertEqual(missing["shop"],["default_deny"])
 def test_remote_trust_requires_alias(self):
  self.assertFalse(trust_domains_compatible("east.local","west.local",set()))
  self.assertTrue(trust_domains_compatible("east.local","west.local",{"west.local"}))
 def test_empty_inventory_is_rejected(self):
  with self.assertRaises(ValueError):evaluate({})

if __name__=="__main__":unittest.main()
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'helm/istio-values.yaml' @'
profile: ambient
global:
  meshID: production-mesh
  multiCluster: { clusterName: replace-cluster }
  network: replace-network
meshConfig:
  trustDomain: corp.internal
  trustDomainAliases: [east.corp.internal, west.corp.internal]
  accessLogFile: /dev/stdout
  defaultConfig: { holdApplicationUntilProxyStarts: true }
pilot:
  autoscaleEnabled: true
  autoscaleMin: 2
  env: { PILOT_ENABLE_AMBIENT: "true" }
cni: { ambient: { enabled: true } }
ztunnel: { resourceName: ztunnel, terminationGracePeriodSeconds: 30 }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'kind/east.yaml' @'
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: mesh-east
networking: { podSubnet: 10.10.0.0/16, serviceSubnet: 10.110.0.0/16 }
nodes: [{ role: control-plane }, { role: worker }]
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'kind/west.yaml' @'
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: mesh-west
networking: { podSubnet: 10.20.0.0/16, serviceSubnet: 10.120.0.0/16 }
nodes: [{ role: control-plane }, { role: worker }]
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'k8s/namespace.yaml' @'
apiVersion: v1
kind: Namespace
metadata:
  name: mesh-shop
  labels:
    istio.io/dataplane-mode: ambient
    istio.io/use-waypoint: shared-waypoint
    pod-security.kubernetes.io/enforce: restricted
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'k8s/apps.yaml' @'
apiVersion: apps/v1
kind: Deployment
metadata: { name: catalog, namespace: mesh-shop }
spec:
  replicas: 3
  selector: { matchLabels: { app: catalog } }
  template:
    metadata: { labels: { app: catalog, version: v1 } }
    spec:
      serviceAccountName: catalog
      securityContext: { runAsNonRoot: true, seccompProfile: { type: RuntimeDefault } }
      containers:
        - name: api
          image: ghcr.io/replace/catalog@sha256:replace
          ports: [{ name: http, containerPort: 8080 }]
          resources: { requests: { cpu: 50m, memory: 64Mi }, limits: { cpu: 500m, memory: 256Mi } }
          readinessProbe: { httpGet: { path: /ready, port: http } }
          securityContext: { allowPrivilegeEscalation: false, readOnlyRootFilesystem: true, capabilities: { drop: [ALL] } }
---
apiVersion: v1
kind: ServiceAccount
metadata: { name: catalog, namespace: mesh-shop }
---
apiVersion: v1
kind: Service
metadata: { name: catalog, namespace: mesh-shop }
spec: { selector: { app: catalog }, ports: [{ name: http, port: 80, targetPort: http }] }
---
apiVersion: apps/v1
kind: Deployment
metadata: { name: inventory, namespace: mesh-shop }
spec:
  replicas: 3
  selector: { matchLabels: { app: inventory } }
  template:
    metadata: { labels: { app: inventory, version: v1 } }
    spec:
      serviceAccountName: inventory
      securityContext: { runAsNonRoot: true, seccompProfile: { type: RuntimeDefault } }
      containers:
        - name: api
          image: ghcr.io/replace/inventory@sha256:replace
          ports: [{ name: http, containerPort: 8080 }]
          resources: { requests: { cpu: 50m, memory: 64Mi }, limits: { cpu: 500m, memory: 256Mi } }
          readinessProbe: { httpGet: { path: /ready, port: http } }
          securityContext: { allowPrivilegeEscalation: false, readOnlyRootFilesystem: true, capabilities: { drop: [ALL] } }
---
apiVersion: v1
kind: ServiceAccount
metadata: { name: inventory, namespace: mesh-shop }
---
apiVersion: v1
kind: Service
metadata: { name: inventory, namespace: mesh-shop }
spec: { selector: { app: inventory }, ports: [{ name: http, port: 80, targetPort: http }] }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'k8s/mesh/waypoint.yaml' @'
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata: { name: shared-waypoint, namespace: mesh-shop }
spec:
  gatewayClassName: istio-waypoint
  listeners: [{ name: mesh, port: 15008, protocol: HBONE }]
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata: { name: public, namespace: mesh-shop }
spec:
  gatewayClassName: istio
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes: { namespaces: { from: Same } }
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata: { name: catalog, namespace: mesh-shop }
spec:
  parentRefs: [{ name: public }]
  rules:
    - matches: [{ path: { type: PathPrefix, value: /catalog } }]
      timeouts: { request: 3s, backendRequest: 2s }
      backendRefs: [{ name: catalog, port: 80 }]
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'k8s/mesh/security.yaml' @'
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata: { name: strict, namespace: mesh-shop }
spec: { mtls: { mode: STRICT } }
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata: { name: default-deny, namespace: mesh-shop }
spec: {}
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata: { name: catalog-from-gateway, namespace: mesh-shop }
spec:
  selector: { matchLabels: { app: catalog } }
  action: ALLOW
  rules:
    - from: [{ source: { principals: [cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account] } }]
      to: [{ operation: { methods: [GET], paths: [/catalog, /catalog/*] } }]
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata: { name: inventory-from-catalog, namespace: mesh-shop }
spec:
  selector: { matchLabels: { app: inventory } }
  action: ALLOW
  rules:
    - from: [{ source: { principals: [cluster.local/ns/mesh-shop/sa/catalog] } }]
      to: [{ operation: { methods: [GET], paths: [/inventory/*] } }]
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'k8s/mesh/traffic.yaml' @'
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata: { name: inventory, namespace: mesh-shop }
spec:
  host: inventory.mesh-shop.svc.cluster.local
  trafficPolicy:
    connectionPool: { http: { http1MaxPendingRequests: 50, maxRequestsPerConnection: 100 } }
    outlierDetection: { consecutive5xxErrors: 5, interval: 5s, baseEjectionTime: 30s, maxEjectionPercent: 50 }
---
apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata: { name: mesh-default, namespace: mesh-shop }
spec:
  accessLogging: [{}]
  metrics: [{ providers: [{ name: prometheus }] }]
  tracing: [{ randomSamplingPercentage: 5.0 }]
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'k8s/networkpolicy.yaml' @'
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata: { name: default-deny, namespace: mesh-shop }
spec: { podSelector: {}, policyTypes: [Ingress, Egress] }
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata: { name: allow-mesh-system, namespace: mesh-shop }
spec:
  podSelector: {}
  policyTypes: [Ingress, Egress]
  ingress: [{ from: [{ namespaceSelector: { matchLabels: { kubernetes.io/metadata.name: istio-system } } }] }]
  egress:
    - to: [{ namespaceSelector: { matchLabels: { kubernetes.io/metadata.name: istio-system } } }]
    - to: [{ podSelector: {} }]
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'k8s/kustomization.yaml' @'
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [namespace.yaml, apps.yaml, networkpolicy.yaml, mesh/waypoint.yaml, mesh/security.yaml, mesh/traffic.yaml]
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'scripts/validate.ps1' @'
$ErrorActionPreference='Stop'
python -m unittest discover -s tests -v
if($LASTEXITCODE){throw 'Mesh policy tests failed.'}
kubectl kustomize k8s | Out-Null
if($LASTEXITCODE){throw 'Kustomize rendering failed.'}
Write-Host 'Mesh contracts validated. Live mTLS and failover still require two disposable clusters.'
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root '.github/workflows/ci.yml' @'
name: mesh-ci
on: { pull_request: {}, push: { branches: [main] } }
permissions: { contents: read }
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: python -m unittest discover -s tests -v
      - run: python -m py_compile meshguard/*.py tests/*.py
      - run: kubectl kustomize k8s >/tmp/mesh.yaml
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/HLD.md' @'
# High-level design

Each cluster runs Istiod, CNI and ztunnel. Ambient L4 identity is the baseline; shared or dedicated waypoints add L7 authorization only where required. Gateway API exposes north-south routes. A common root of trust, explicit trust-domain aliases and east-west gateways connect clusters without turning the mesh into an unrestricted flat network.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/LLD.md' @'
# Low-level design

Namespaces opt in with `istio.io/dataplane-mode=ambient`. Service accounts form workload identity. Strict PeerAuthentication and an empty AuthorizationPolicy establish deny-by-default behavior. Explicit principals and operations reopen required paths. NetworkPolicy remains a separate defense layer. DestinationRule handles bounded connection pools and outlier ejection; Gateway API owns public routing.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/RUNBOOK.md' @'
# Mesh runbook

For an outage, separate DNS, CNI capture, ztunnel, waypoint, policy and application failures. Inspect Gateway/HTTPRoute conditions, ztunnel logs, authorization denials and certificate expiry. Prove failover using a controlled regional drain, then verify error rate, locality and recovery time. Never disable mTLS or default-deny globally as a troubleshooting shortcut.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/THREAT-MODEL.md' @'
# Threat model

Threats include workload-identity theft, permissive trust aliases, namespace-label tampering, L7 bypass, compromised gateways, uncontrolled egress and cross-cluster lateral movement. Controls include short-lived certificates, admission-protected labels, explicit principals, restricted gateway attachment, egress allowlists, audit telemetry and independent Kubernetes NetworkPolicy.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/EXERCISES.md' @'
# Required exercises

1. Prove plaintext is rejected and capture the evidence.
2. Remove the catalog allow policy and explain the denial telemetry.
3. Move inventory behind a dedicated waypoint.
4. Rotate a root/intermediate certificate in a disposable mesh.
5. Drain one cluster and measure multi-cluster recovery.
6. Compare ambient resource cost with a sidecar baseline.
'@ -WhatIfMode:$WhatIfMode
[pscustomobject]@{Project='28-istio-zero-trust-multicluster-mesh';Root=$root;Files=$script:Generated.Count}
