param([switch]$WhatIfMode)
. (Join-Path $PSScriptRoot 'Common.ps1')
$root=Join-Path $script:ProjectsRoot '29-finops-opencost-focus-governance'
Write-TemplateFile $root '.template-owned' 'Generated by tools/module20-projects. Additional user files are never deleted.' -WhatIfMode:$WhatIfMode
Write-TemplateFile $root '.gitignore' @'
__pycache__/
reports/*.actual.json
.env
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'README.md' @'
# FinOps, OpenCost and FOCUS Governance Platform

A cost-engineering capstone using OpenCost, Prometheus, FOCUS-shaped billing data, showback/chargeback, unit economics, budget policy, anomaly detection, rightsizing evidence and accountable optimization.

```mermaid
flowchart LR
  C[Cloud bills / FOCUS] --> N[Normalizer]
  O[OpenCost allocations] --> N
  N --> M[Cost model]
  M --> S[Showback]
  M --> B[Budget controls]
  M --> U[Unit economics]
  B --> A[Alerts and action register]
```

## Outcomes

- Reconcile Kubernetes allocation cost with provider billing instead of treating estimates as invoices.
- Attribute cost using owner, product, environment and cost-center dimensions.
- Calculate cost per request/order/model token and distinguish useful growth from waste.
- Implement budget thresholds, anomaly evidence and safe rightsizing recommendations.
- Run a FinOps operating cadence across engineering, finance and product stakeholders.

## Start

```powershell
python -m unittest discover -s tests -v
python scripts/report.py data/opencost-allocations.json policies/budgets.json
kubectl kustomize k8s
```

The sample values are intentionally synthetic. Never use a recommendation as an automated production resize until seasonality, headroom, disruption budgets and service objectives have been reviewed.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'finops/__init__.py' '' -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'finops/model.py' @'
from dataclasses import dataclass

REQUIRED_LABELS={"owner","product","environment","cost_center"}

@dataclass(frozen=True)
class Allocation:
 name:str
 monthly_cost:float
 requests:int
 labels:dict[str,str]
 cpu_requested:float
 cpu_used:float

def from_dict(item:dict)->Allocation:
 cost=float(item["monthly_cost"]);requests=int(item["requests"])
 if cost<0 or requests<0:raise ValueError("cost and requests must be non-negative")
 return Allocation(str(item["name"]),cost,requests,dict(item.get("labels",{})),float(item["cpu_requested"]),float(item["cpu_used"]))

def unit_cost(allocation:Allocation)->float|None:
 return None if allocation.requests==0 else round(allocation.monthly_cost/allocation.requests,6)

def utilization(allocation:Allocation)->float:
 if allocation.cpu_requested<=0:raise ValueError("cpu request must be positive")
 return allocation.cpu_used/allocation.cpu_requested

def recommendation(allocation:Allocation)->str:
 ratio=utilization(allocation)
 if ratio<0.2:return "review_downsize"
 if ratio>0.8:return "review_headroom"
 return "hold"

def missing_labels(allocation:Allocation)->list[str]:
 return sorted(label for label in REQUIRED_LABELS if not allocation.labels.get(label))

def budget_status(actual:float,budget:float)->str:
 if budget<=0:raise ValueError("budget must be positive")
 ratio=actual/budget
 return "breach" if ratio>=1 else "warning" if ratio>=0.8 else "healthy"
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'scripts/report.py' @'
import json,sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from finops.model import budget_status,from_dict,missing_labels,recommendation,unit_cost

if len(sys.argv)!=3:raise SystemExit("usage: report.py ALLOCATIONS.json BUDGETS.json")
allocations=[from_dict(item) for item in json.loads(Path(sys.argv[1]).read_text())]
budgets=json.loads(Path(sys.argv[2]).read_text())
rows=[]
for item in allocations:
 product=item.labels.get("product");budget=budgets.get(product) if product else None
 status="unallocated" if not product else "unbudgeted" if budget is None else budget_status(item.monthly_cost,float(budget))
 rows.append({"name":item.name,"monthly_cost":item.monthly_cost,"unit_cost":unit_cost(item),"budget_status":status,"recommendation":recommendation(item),"missing_labels":missing_labels(item)})
print(json.dumps({"allocations":rows,"total":round(sum(item.monthly_cost for item in allocations),2)},indent=2))
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'tests/test_model.py' @'
import unittest
from finops.model import budget_status,from_dict,missing_labels,recommendation,unit_cost

def sample(**changes):
 data={"name":"checkout","monthly_cost":100,"requests":1000,"labels":{"owner":"payments","product":"shop","environment":"prod","cost_center":"cc-1"},"cpu_requested":4,"cpu_used":1.5};data.update(changes);return from_dict(data)

class FinOpsTests(unittest.TestCase):
 def test_unit_cost(self):self.assertEqual(unit_cost(sample()),0.1)
 def test_zero_volume_is_not_divided(self):self.assertIsNone(unit_cost(sample(requests=0)))
 def test_rightsizing_is_review_not_automatic(self):self.assertEqual(recommendation(sample(cpu_used=.4)),"review_downsize")
 def test_missing_attribution_is_visible(self):self.assertEqual(missing_labels(sample(labels={"owner":"payments"})),["cost_center","environment","product"])
 def test_budget_thresholds(self):
  self.assertEqual(budget_status(79,100),"healthy");self.assertEqual(budget_status(80,100),"warning");self.assertEqual(budget_status(100,100),"breach")
 def test_invalid_budget_rejected(self):
  with self.assertRaises(ValueError):budget_status(1,0)

if __name__=="__main__":unittest.main()
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'data/opencost-allocations.json' @'
[
  {"name":"checkout","monthly_cost":4200,"requests":1800000,"labels":{"owner":"payments","product":"shop","environment":"prod","cost_center":"cc-101"},"cpu_requested":24,"cpu_used":13},
  {"name":"catalog","monthly_cost":2100,"requests":5100000,"labels":{"owner":"catalog","product":"shop","environment":"prod","cost_center":"cc-101"},"cpu_requested":32,"cpu_used":5},
  {"name":"recommendations","monthly_cost":7800,"requests":900000,"labels":{"owner":"ml","product":"personalization","environment":"prod","cost_center":"cc-205"},"cpu_requested":64,"cpu_used":54}
]
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'data/focus-sample.csv' @'
BillingAccountId,BillingPeriodStart,ChargeCategory,ChargeDescription,ChargePeriodStart,ChargePeriodEnd,EffectiveCost,ProviderName,RegionId,ResourceId,ServiceName,Tags
replace,2026-07-01,Usage,Compute,2026-07-01,2026-08-01,4200.00,ExampleCloud,india-central,cluster-prod,Managed Kubernetes,"owner=platform;product=shop"
replace,2026-07-01,Usage,Object storage,2026-07-01,2026-08-01,380.00,ExampleCloud,india-central,bucket-backups,Object Storage,"owner=database;product=shared"
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'policies/budgets.json' @'
{"shop":7000,"personalization":7500,"shared":1000}
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'policies/cost-attribution.rego' @'
package finops.attribution
required := {"owner", "product", "environment", "cost_center"}
deny contains message if {
  input.kind == "Deployment"
  missing := required - {key | input.metadata.labels[key]}
  count(missing) > 0
  message := sprintf("workload is missing cost labels: %v", [missing])
}
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'helm/opencost-values.yaml' @'
opencost:
  exporter:
    defaultClusterId: production
    extraEnv:
      EMIT_KSM_V1_METRICS: "false"
  ui: { enabled: true }
  prometheus:
    internal: { enabled: false }
    external: { enabled: true, url: http://prometheus.monitoring.svc:9090 }
  customPricing:
    enabled: true
    provider: custom
    costModel: { CPU: "0.031", RAM: "0.004", storage: "0.00014" }
  metrics: { serviceMonitor: { enabled: true } }
  securityContext: { runAsNonRoot: true, readOnlyRootFilesystem: true }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'k8s/platform.yaml' @'
apiVersion: v1
kind: Namespace
metadata: { name: finops, labels: { pod-security.kubernetes.io/enforce: restricted } }
---
apiVersion: v1
kind: ResourceQuota
metadata: { name: finops-quota, namespace: finops }
spec: { hard: { requests.cpu: "4", requests.memory: 8Gi, limits.cpu: "8", limits.memory: 16Gi } }
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata: { name: finops-alerts, namespace: finops }
spec:
  groups:
    - name: finops
      rules:
        - alert: NamespaceCostAnomaly
          expr: sum by (namespace) (increase(node_total_hourly_cost[1d])) > 1.5 * avg_over_time(sum by (namespace) (increase(node_total_hourly_cost[1d]))[14d:1d])
          for: 30m
          labels: { severity: warning, owner: finops }
          annotations: { summary: Namespace daily cost is over its historical baseline }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'k8s/kustomization.yaml' @'
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [platform.yaml]
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'dashboards/finops.json' @'
{"title":"FinOps Unit Economics","schemaVersion":41,"panels":[{"type":"stat","title":"Monthly allocated cost","targets":[{"expr":"sum(container_cpu_allocation)+sum(container_memory_allocation_bytes)"}]},{"type":"timeseries","title":"Cost by namespace","targets":[{"expr":"sum by (namespace) (node_total_hourly_cost)"}]}]}
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'reports/example.md' @'
# Monthly FinOps review

- Total allocated cost: 14,100 currency units.
- Personalization exceeded budget by 4%; owner must decide whether unit-economics improvement justifies the increase.
- Catalog CPU utilization is below 20%; run a load-shaped rightsizing experiment before changing requests.
- Unallocated cost and invoice reconciliation variance must be reported separately, never hidden inside product totals.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'scripts/validate.ps1' @'
$ErrorActionPreference='Stop'
python -m unittest discover -s tests -v
if($LASTEXITCODE){throw 'FinOps tests failed.'}
python scripts/report.py data/opencost-allocations.json policies/budgets.json | Out-Null
if($LASTEXITCODE){throw 'FinOps report failed.'}
kubectl kustomize k8s | Out-Null
Write-Host 'FinOps contracts validated.'
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root '.github/workflows/ci.yml' @'
name: finops-ci
on: { pull_request: {}, push: { branches: [main] } }
permissions: { contents: read }
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: python -m unittest discover -s tests -v
      - run: python scripts/report.py data/opencost-allocations.json policies/budgets.json >/tmp/report.json
      - run: kubectl kustomize k8s >/tmp/finops.yaml
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/HLD.md' @'
# High-level design

OpenCost provides near-real-time Kubernetes allocations while provider billing exports provide invoice truth. A normalization layer maps both to FOCUS-shaped dimensions. The model produces showback, budgets and unit economics; an action register records whether the business accepts, optimizes or investigates each variance.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/GOVERNANCE.md' @'
# Governance

Engineering owns resource metadata and technical action. Finance owns invoice reconciliation and accounting policy. Product owns value and demand decisions. The FinOps team owns allocation rules, shared-cost methodology and cadence. Track forecast error, unallocated percentage, commitment coverage, idle cost, optimization realized and cost per business unit.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/RUNBOOK.md' @'
# Cost anomaly runbook

Confirm data freshness and currency first. Compare allocation, invoice and usage signals. Identify whether the change is demand, price, architecture, leak or attribution drift. Apply a temporary budget guard only when it will not violate reliability. Record owner, expected benefit, customer risk, rollback and verified savings.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/EXERCISES.md' @'
# Required exercises

1. Reconcile the sample allocations to a synthetic FOCUS invoice.
2. Define shared-cluster allocation rules and measure unallocated cost.
3. Add GPU token-level unit economics.
4. Design commitment coverage without hiding workload lock-in.
5. Run a rightsizing experiment with an SLO rollback condition.
6. Present the same variance to engineering, finance and product audiences.
'@ -WhatIfMode:$WhatIfMode
[pscustomobject]@{Project='29-finops-opencost-focus-governance';Root=$root;Files=$script:Generated.Count}
