param([switch]$WhatIfMode)
. (Join-Path $PSScriptRoot 'Common.ps1')
$root=Join-Path $script:ProjectsRoot '30-cloudnative-postgresql-database-platform'
Write-TemplateFile $root '.template-owned' 'Generated by tools/module20-projects. Additional user files are never deleted.' -WhatIfMode:$WhatIfMode
Write-TemplateFile $root '.gitignore' @'
.env
__pycache__/
backups/
recovery-evidence/*.actual.json
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root '.env.example' @'
POSTGRES_DB=orders
POSTGRES_USER=app
POSTGRES_PASSWORD=local-development-only
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'README.md' @'
# CloudNativePG PostgreSQL Database Platform

A database-platform capstone using PostgreSQL 18, CloudNativePG 1.30, PgBouncer, online migrations, WAL archiving, scheduled backups, point-in-time recovery, observability, disruption controls and evidence-driven restore drills.

```mermaid
flowchart LR
  A[Applications] --> P[PgBouncer Pooler]
  P --> R[Read-write service]
  R --> C[(Primary)]
  C --> S1[(Replica)]
  C --> S2[(Replica)]
  C --> W[WAL archive]
  B[Scheduled backup] --> O[Object storage]
  O --> D[Recovery cluster]
```

## Outcomes

- Operate a declarative HA database without pretending Kubernetes alone solves database reliability.
- Design transaction pooling, connection budgets, synchronous replication and topology spread.
- Apply expand/migrate/contract schema changes with explicit rollback and backup gates.
- Prove backup integrity through isolated PITR drills and checksum evidence.
- Define database SLOs for availability, latency, replication lag, transaction age and recovery.

## Start

```powershell
Copy-Item .env.example .env
docker compose up -d postgres migrate
python -m unittest discover -s tests -v
kubectl kustomize k8s
```

The Kubernetes manifests assume the CloudNativePG and Barman Cloud Plugin CRDs are installed. Replace object-store and identity placeholders before any cluster application.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'dbguard/__init__.py' '' -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'dbguard/plan.py' @'
from datetime import datetime,timezone

DESTRUCTIVE={"drop_table","drop_column","rewrite_table"}

def validate_manifest(entries:list[dict])->list[str]:
 errors=[];expected=1
 for entry in entries:
  if int(entry.get("sequence",-1))!=expected:errors.append(f"expected migration sequence {expected}")
  if entry.get("risk") in DESTRUCTIVE and not entry.get("backup_verified"):errors.append(f"migration {expected} requires verified backup")
  if not entry.get("rollback"):errors.append(f"migration {expected} requires rollback")
  expected+=1
 return errors

def recovery_point_allowed(target:str,oldest_restorable:str,now:str)->bool:
 def parse(value:str):return datetime.fromisoformat(value.replace("Z","+00:00")).astimezone(timezone.utc)
 target_time,oldest,now_time=parse(target),parse(oldest_restorable),parse(now)
 return oldest<=target_time<=now_time

def connection_budget(max_connections:int,reserved:int,pool_replicas:int)->int:
 if min(max_connections,pool_replicas)<=0 or reserved<0 or reserved>=max_connections:raise ValueError("invalid connection budget")
 return (max_connections-reserved)//pool_replicas
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'tests/test_plan.py' @'
import unittest
from dbguard.plan import connection_budget,recovery_point_allowed,validate_manifest

class DatabaseGuardTests(unittest.TestCase):
 def test_safe_manifest(self):
  entries=[{"sequence":1,"risk":"additive","backup_verified":False,"rollback":"drop new table"},{"sequence":2,"risk":"drop_column","backup_verified":True,"rollback":"restore old column"}]
  self.assertEqual(validate_manifest(entries),[])
 def test_destructive_change_needs_backup(self):
  errors=validate_manifest([{"sequence":1,"risk":"drop_table","rollback":"restore"}]);self.assertIn("migration 1 requires verified backup",errors)
 def test_sequence_gap_is_rejected(self):self.assertIn("expected migration sequence 1",validate_manifest([{"sequence":2,"risk":"additive","rollback":"drop"}]))
 def test_pitr_window(self):
  self.assertTrue(recovery_point_allowed("2026-08-10T10:00:00Z","2026-08-01T00:00:00Z","2026-08-16T00:00:00Z"))
  self.assertFalse(recovery_point_allowed("2026-07-10T10:00:00Z","2026-08-01T00:00:00Z","2026-08-16T00:00:00Z"))
 def test_connection_budget(self):self.assertEqual(connection_budget(300,30,3),90)

if __name__=="__main__":unittest.main()
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'migrations/001_init.sql' @'
BEGIN;
CREATE TABLE IF NOT EXISTS orders (
  id uuid PRIMARY KEY,
  customer_id uuid NOT NULL,
  status text NOT NULL CHECK (status IN ('pending','confirmed','cancelled')),
  total_cents bigint NOT NULL CHECK (total_cents >= 0),
  created_at timestamptz NOT NULL DEFAULT now()
);
COMMIT;
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'migrations/002_outbox.sql' @'
BEGIN;
CREATE TABLE IF NOT EXISTS outbox_events (
  id uuid PRIMARY KEY,
  aggregate_id uuid NOT NULL,
  event_type text NOT NULL,
  payload jsonb NOT NULL,
  occurred_at timestamptz NOT NULL DEFAULT now(),
  published_at timestamptz
);
COMMIT;
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'migrations/003_indexes.sql' @'
CREATE INDEX CONCURRENTLY IF NOT EXISTS orders_customer_created_idx ON orders(customer_id, created_at DESC);
CREATE INDEX CONCURRENTLY IF NOT EXISTS outbox_unpublished_idx ON outbox_events(occurred_at) WHERE published_at IS NULL;
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'migrations/manifest.json' @'
[
  {"sequence":1,"file":"001_init.sql","risk":"additive","backup_verified":false,"rollback":"drop orders after proving no consumers"},
  {"sequence":2,"file":"002_outbox.sql","risk":"additive","backup_verified":false,"rollback":"drop outbox_events after publisher rollback"},
  {"sequence":3,"file":"003_indexes.sql","risk":"additive","backup_verified":false,"rollback":"drop the two indexes concurrently"}
]
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docker-compose.yml' @'
services:
  postgres:
    image: postgres:18.0-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-orders}
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-local-development-only}
    ports: ["5432:5432"]
    volumes: [postgres-data:/var/lib/postgresql/data]
    healthcheck: { test: [CMD-SHELL, "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"], interval: 5s, timeout: 3s, retries: 20 }
  migrate:
    image: postgres:18.0-alpine
    depends_on: { postgres: { condition: service_healthy } }
    environment:
      PGPASSWORD: ${POSTGRES_PASSWORD:-local-development-only}
    volumes: [./migrations:/migrations:ro]
    command: [sh, -ec, 'for file in /migrations/*.sql; do psql -v ON_ERROR_STOP=1 -h postgres -U "$${POSTGRES_USER:-app}" -d "$${POSTGRES_DB:-orders}" -f "$$file"; done']
volumes: { postgres-data: {} }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'k8s/namespace.yaml' @'
apiVersion: v1
kind: Namespace
metadata: { name: database, labels: { pod-security.kubernetes.io/enforce: restricted } }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'k8s/object-store.yaml' @'
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata: { name: orders-store, namespace: database }
spec:
  configuration:
    destinationPath: s3://replace-cnpg-backups/orders
    s3Credentials: { inheritFromIAMRole: true }
    wal: { compression: gzip, maxParallel: 4 }
    data: { compression: gzip, jobs: 2 }
  retentionPolicy: 30d
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'k8s/cluster.yaml' @'
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata: { name: orders, namespace: database }
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:18.4-system-trixie
  primaryUpdateStrategy: unsupervised
  primaryUpdateMethod: switchover
  enableSuperuserAccess: false
  minSyncReplicas: 1
  maxSyncReplicas: 1
  postgresql:
    parameters:
      max_connections: "300"
      shared_buffers: 512MB
      log_min_duration_statement: "500"
      idle_in_transaction_session_timeout: 60s
  storage: { size: 50Gi, storageClass: replace-encrypted-rwo }
  walStorage: { size: 20Gi, storageClass: replace-encrypted-rwo }
  resources: { requests: { cpu: "1", memory: 2Gi }, limits: { cpu: "4", memory: 8Gi } }
  affinity:
    enablePodAntiAffinity: true
    topologyKey: topology.kubernetes.io/zone
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters: { barmanObjectName: orders-store }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'k8s/pooler.yaml' @'
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata: { name: orders-rw, namespace: database }
spec:
  cluster: { name: orders }
  instances: 3
  type: rw
  pgbouncer:
    poolMode: transaction
    parameters: { max_client_conn: "1000", default_pool_size: "90", reserve_pool_size: "10", server_lifetime: "3600" }
  template:
    spec:
      containers:
        - name: pgbouncer
          resources: { requests: { cpu: 100m, memory: 128Mi }, limits: { cpu: "1", memory: 512Mi } }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'k8s/backups.yaml' @'
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata: { name: orders-daily, namespace: database }
spec:
  schedule: "0 0 2 * * *"
  backupOwnerReference: self
  cluster: { name: orders }
  method: plugin
  pluginConfiguration: { name: barman-cloud.cloudnative-pg.io }
  immediate: true
---
apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata: { name: orders-release-gate, namespace: database }
spec:
  cluster: { name: orders }
  method: plugin
  pluginConfiguration: { name: barman-cloud.cloudnative-pg.io }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'k8s/monitoring.yaml' @'
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata: { name: orders, namespace: database }
spec:
  selector: { matchLabels: { cnpg.io/cluster: orders } }
  podMetricsEndpoints: [{ port: metrics, interval: 30s }]
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata: { name: orders-database, namespace: database }
spec:
  groups:
    - name: postgresql
      rules:
        - alert: PostgreSQLReplicationLag
          expr: cnpg_pg_replication_lag > 30
          for: 5m
          labels: { severity: warning }
          annotations: { summary: PostgreSQL replica lag exceeds the RPO guardrail }
        - alert: PostgreSQLLastBackupStale
          expr: time() - cnpg_collector_last_available_backup_timestamp > 90000
          for: 15m
          labels: { severity: critical }
          annotations: { summary: No usable database backup completed in the last 25 hours }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'k8s/networkpolicy.yaml' @'
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata: { name: database-default-deny, namespace: database }
spec: { podSelector: {}, policyTypes: [Ingress, Egress] }
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata: { name: orders-pooler, namespace: database }
spec: { minAvailable: 2, selector: { matchLabels: { cnpg.io/poolerName: orders-rw } } }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'k8s/kustomization.yaml' @'
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [namespace.yaml, object-store.yaml, cluster.yaml, pooler.yaml, backups.yaml, monitoring.yaml, networkpolicy.yaml]
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'recovery/cluster.yaml' @'
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata: { name: orders-recovery, namespace: database-recovery }
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:18.4-system-trixie
  bootstrap:
    recovery:
      source: orders-backup
      recoveryTarget: { targetTime: "2026-08-10 10:00:00+00" }
  externalClusters:
    - name: orders-backup
      plugin: { name: barman-cloud.cloudnative-pg.io, parameters: { barmanObjectName: orders-store, serverName: orders } }
  storage: { size: 50Gi, storageClass: replace-encrypted-rwo }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'recovery-evidence/example.json' @'
{"backup_id":"replace","target_time":"2026-08-10T10:00:00Z","restore_started":"2026-08-16T01:00:00Z","restore_completed":"2026-08-16T01:18:00Z","rto_seconds":1080,"rpo_seconds":120,"row_count":100000,"logical_checksum":"replace","owner":"database-platform","passed":true}
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'scripts/validate.ps1' @'
$ErrorActionPreference='Stop'
python -m unittest discover -s tests -v
if($LASTEXITCODE){throw 'Database guard tests failed.'}
docker compose config --quiet
if($LASTEXITCODE){throw 'Compose validation failed.'}
kubectl kustomize k8s | Out-Null
Write-Host 'Database platform contracts validated.'
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root '.github/workflows/ci.yml' @'
name: database-platform-ci
on: { pull_request: {}, push: { branches: [main] } }
permissions: { contents: read }
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: python -m unittest discover -s tests -v
      - run: python -m py_compile dbguard/*.py tests/*.py
      - run: docker compose config --quiet
      - run: kubectl kustomize k8s >/tmp/database.yaml
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/HLD.md' @'
# High-level design

CloudNativePG reconciles PostgreSQL instances, roles and services. PgBouncer isolates applications from connection churn. WAL and base backups leave the cluster through the Barman plugin. Monitoring, migrations and restore evidence are separate control planes so a green operator status never substitutes for proven recoverability.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/MIGRATIONS.md' @'
# Migration standard

Prefer expand, migrate and contract. Every change needs owner, lock estimate, compatibility window, rollback and observability. Create large indexes concurrently. Avoid a single transaction for operations PostgreSQL forbids inside one. Destructive changes require a verified backup and proof that old application versions no longer depend on the schema.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/RUNBOOK.md' @'
# Database runbook

Triage client saturation, pool saturation, lock waits, long transactions, storage latency, replication lag and operator health separately. A failover is not complete until writers reconnect and invariants pass. A backup is not trusted until an isolated restore proves WAL continuity, application queries, row counts and logical checksums.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/THREAT-MODEL.md' @'
# Threat model

Threats include credential leakage, superuser access, SQL injection, malicious migrations, object-store deletion, backup tampering, cross-namespace connectivity and unencrypted volumes. Controls include workload identity, external secrets, least-privilege roles, reviewed migrations, object lock, separate backup credentials, network policy, CMEK and restore evidence.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/EXERCISES.md' @'
# Required exercises

1. Measure planned switchover and unplanned failover recovery.
2. Exhaust the connection pool without exhausting PostgreSQL.
3. Run a blocking-migration rehearsal and abort safely.
4. Restore to a timestamp between two transactions.
5. Corrupt a backup reference and demonstrate detection.
6. Perform a major-version upgrade rehearsal with rollback criteria.
'@ -WhatIfMode:$WhatIfMode
[pscustomobject]@{Project='30-cloudnative-postgresql-database-platform';Root=$root;Files=$script:Generated.Count}
