param([switch]$WhatIfMode)
. (Join-Path $PSScriptRoot 'Common.ps1')
$root=Join-Path $script:ProjectsRoot '31-progressive-delivery-openfeature-platform'
Write-TemplateFile $root '.template-owned' 'Generated by tools/module20-projects. Additional user files are never deleted.' -WhatIfMode:$WhatIfMode
Write-TemplateFile $root '.gitignore' @'
__pycache__/
.env
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'README.md' @'
# Progressive Delivery and OpenFeature Platform

A release-engineering capstone using Argo Rollouts 1.9.1, Prometheus analysis, OpenFeature, flagd, automated rollback, canary/blue-green strategies, feature-flag governance and separation of deployment from release.

```mermaid
flowchart LR
  G[Git commit] --> A[Argo CD]
  A --> R[Argo Rollout]
  R --> S[Stable]
  R --> C[Canary]
  P[Prometheus] --> X[AnalysisRun]
  X -->|promote / abort| R
  F[flagd / OpenFeature] --> S
  F --> C
```

## Outcomes

- Distinguish deployment, traffic exposure and feature release.
- Build canary steps with measurable success, latency and business guardrails.
- Automate rollback while preserving GitOps reconciliation semantics.
- Govern flag ownership, expiry, safe defaults, targeting and emergency kills.
- Rehearse roll-forward, rollback and flag-disable incident decisions.

## Start

```powershell
docker compose config
python -m unittest discover -s tests -v
python scripts/simulate.py
kubectl kustomize k8s
```

Install Argo Rollouts and the OpenFeature Operator before applying the Kubernetes resources. Use real metric names and tested Prometheus queries before enabling automated production promotion.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'delivery/__init__.py' '' -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'delivery/flags.py' @'
import hashlib
from datetime import date

def bucket(key:str)->int:
 return int(hashlib.sha256(key.encode()).hexdigest()[:8],16)%100

def enabled(flag:dict,targeting_key:str,groups:set[str]|None=None)->bool:
 groups=groups or set()
 if flag.get("state")!="ENABLED":return False
 if groups.intersection(flag.get("includeGroups",[])):return True
 return bucket(targeting_key)<int(flag.get("percentage",0))

def validate_flag(flag:dict,today:date)->list[str]:
 errors=[]
 for field in ("owner","ticket","expires","safeDefault"):
  if not flag.get(field):errors.append(f"missing {field}")
 try:
  if date.fromisoformat(flag.get("expires","1900-01-01"))<today:errors.append("flag expired")
 except ValueError:errors.append("invalid expiry")
 if not 0<=int(flag.get("percentage",-1))<=100:errors.append("invalid percentage")
 return errors

def validate_steps(weights:list[int])->list[str]:
 errors=[]
 if not weights or weights[-1]!=100:errors.append("rollout must finish at 100")
 if any(weight<=0 or weight>100 for weight in weights):errors.append("weights must be within 1..100")
 if any(current>=following for current,following in zip(weights,weights[1:])):errors.append("weights must increase")
 return errors
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'app/__init__.py' '' -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'app/main.py' @'
import json,os
from http.server import BaseHTTPRequestHandler,ThreadingHTTPServer
from pathlib import Path
from delivery.flags import enabled

FLAGS=Path(os.getenv("FLAGS_FILE","/flags/governance.json"))

def checkout(targeting_key:str)->dict:
 flags=json.loads(FLAGS.read_text())
 use_v2=enabled(flags["checkout-v2"],targeting_key)
 return {"checkout":"v2" if use_v2 else "v1","targetingKey":targeting_key}

class Handler(BaseHTTPRequestHandler):
 def do_GET(self):
  if self.path=="/healthz":status,body=200,{"status":"ok"}
  elif self.path.startswith("/checkout"):
   status,body=200,checkout(self.headers.get("X-Targeting-Key","anonymous"))
  else:status,body=404,{"error":"not_found"}
  payload=json.dumps(body).encode();self.send_response(status);self.send_header("Content-Type","application/json");self.send_header("Content-Length",str(len(payload)));self.end_headers();self.wfile.write(payload)
 def log_message(self,format,*args):return

if __name__=="__main__":ThreadingHTTPServer(("0.0.0.0",int(os.getenv("PORT","8080"))),Handler).serve_forever()
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'app/Dockerfile' @'
FROM python:3.14.1-slim
RUN groupadd -g 10001 app && useradd -u 10001 -g app --no-create-home app
WORKDIR /app
COPY --chown=10001:10001 app app
COPY --chown=10001:10001 delivery delivery
COPY --chown=10001:10001 flags /flags
USER 10001:10001
EXPOSE 8080
CMD ["python", "-m", "app.main"]
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'flags/governance.json' @'
{
  "checkout-v2": {
    "state":"ENABLED",
    "percentage":10,
    "includeGroups":["employees","qa"],
    "owner":"checkout-team",
    "ticket":"REL-3101",
    "expires":"2027-01-31",
    "safeDefault":"off"
  }
}
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'flags/flags.flagd.json' @'
{
  "$schema":"https://flagd.dev/schema/v0/flags.json",
  "flags":{
    "checkout-v2":{
      "state":"ENABLED",
      "variants":{"on":true,"off":false},
      "defaultVariant":"off",
      "targeting":{"fractional":[{"var":"targetingKey"},["on",10],["off",90]]}
    }
  }
}
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'tests/test_delivery.py' @'
import unittest
from datetime import date
from delivery.flags import bucket,enabled,validate_flag,validate_steps

class DeliveryTests(unittest.TestCase):
 def test_bucketing_is_deterministic(self):self.assertEqual(bucket("customer-1"),bucket("customer-1"))
 def test_group_override(self):self.assertTrue(enabled({"state":"ENABLED","percentage":0,"includeGroups":["qa"]},"user",{"qa"}))
 def test_disabled_flag_is_safe(self):self.assertFalse(enabled({"state":"DISABLED","percentage":100},"user"))
 def test_governed_flag(self):
  flag={"owner":"team","ticket":"REL-1","expires":"2027-01-01","safeDefault":"off","percentage":10}
  self.assertEqual(validate_flag(flag,date(2026,8,16)),[])
 def test_expired_flag_fails(self):
  flag={"owner":"team","ticket":"REL-1","expires":"2025-01-01","safeDefault":"off","percentage":10}
  self.assertIn("flag expired",validate_flag(flag,date(2026,8,16)))
 def test_rollout_steps(self):self.assertEqual(validate_steps([5,20,50,100]),[])
 def test_non_monotonic_rollout_fails(self):self.assertIn("weights must increase",validate_steps([10,5,100]))

if __name__=="__main__":unittest.main()
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'scripts/simulate.py' @'
import json
from pathlib import Path
import sys
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from delivery.flags import enabled
flag=json.loads(Path("flags/governance.json").read_text())["checkout-v2"]
population=[f"customer-{index}" for index in range(1000)]
exposed=sum(enabled(flag,key) for key in population)
print(json.dumps({"population":len(population),"exposed":exposed,"observedPercent":round(exposed/len(population)*100,1)},indent=2))
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docker-compose.yml' @'
services:
  flagd:
    image: ghcr.io/open-feature/flagd:v0.16.0
    command: [start, --uri, file:/etc/flagd/flags.flagd.json]
    volumes: [./flags:/etc/flagd:ro]
    ports: ["8013:8013"]
    read_only: true
  checkout:
    build: { context: ., dockerfile: app/Dockerfile }
    environment: { FLAGS_FILE: /flags/governance.json }
    volumes: [./flags:/flags:ro]
    ports: ["8131:8080"]
    read_only: true
    tmpfs: [/tmp]
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'k8s/namespace.yaml' @'
apiVersion: v1
kind: Namespace
metadata: { name: progressive, labels: { pod-security.kubernetes.io/enforce: restricted } }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'k8s/services.yaml' @'
apiVersion: v1
kind: Service
metadata: { name: checkout-stable, namespace: progressive }
spec: { selector: { app: checkout }, ports: [{ name: http, port: 80, targetPort: http }] }
---
apiVersion: v1
kind: Service
metadata: { name: checkout-canary, namespace: progressive }
spec: { selector: { app: checkout }, ports: [{ name: http, port: 80, targetPort: http }] }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'k8s/analysis.yaml' @'
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata: { name: checkout-health, namespace: progressive }
spec:
  args: [{ name: service-name }]
  metrics:
    - name: success-rate
      interval: 1m
      count: 5
      successCondition: result[0] >= 0.995
      failureLimit: 2
      provider:
        prometheus:
          address: http://prometheus.monitoring.svc:9090
          query: sum(rate(http_requests_total{service="{{args.service-name}}",status!~"5.."}[2m])) / sum(rate(http_requests_total{service="{{args.service-name}}"}[2m]))
    - name: p95-latency
      interval: 1m
      count: 5
      successCondition: result[0] < 0.4
      failureLimit: 2
      provider:
        prometheus:
          address: http://prometheus.monitoring.svc:9090
          query: histogram_quantile(0.95,sum by (le) (rate(http_request_duration_seconds_bucket{service="{{args.service-name}}"}[2m])))
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'k8s/rollout.yaml' @'
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata: { name: checkout, namespace: progressive }
spec:
  replicas: 5
  revisionHistoryLimit: 3
  selector: { matchLabels: { app: checkout } }
  strategy:
    canary:
      stableService: checkout-stable
      canaryService: checkout-canary
      maxUnavailable: 0
      maxSurge: 1
      analysis:
        templates: [{ templateName: checkout-health }]
        args: [{ name: service-name, value: checkout-canary }]
        startingStep: 1
      steps:
        - setWeight: 5
        - pause: { duration: 2m }
        - setWeight: 20
        - pause: { duration: 5m }
        - setWeight: 50
        - pause: { duration: 10m }
        - setWeight: 100
  template:
    metadata:
      labels: { app: checkout }
      annotations:
        openfeature.dev/enabled: "true"
        openfeature.dev/featureflagsource: checkout-flags
    spec:
      serviceAccountName: checkout
      securityContext: { runAsNonRoot: true, seccompProfile: { type: RuntimeDefault } }
      containers:
        - name: checkout
          image: ghcr.io/replace/checkout@sha256:replace
          ports: [{ name: http, containerPort: 8080 }]
          resources: { requests: { cpu: 100m, memory: 128Mi }, limits: { cpu: "1", memory: 512Mi } }
          readinessProbe: { httpGet: { path: /healthz, port: http } }
          securityContext: { allowPrivilegeEscalation: false, readOnlyRootFilesystem: true, capabilities: { drop: [ALL] } }
---
apiVersion: v1
kind: ServiceAccount
metadata: { name: checkout, namespace: progressive }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'k8s/openfeature.yaml' @'
apiVersion: core.openfeature.dev/v1beta1
kind: FeatureFlag
metadata: { name: checkout, namespace: progressive }
spec:
  flagSpec:
    flags:
      checkout-v2:
        state: ENABLED
        variants: { "on": true, "off": false }
        defaultVariant: "off"
        targeting: { fractional: [{ var: targetingKey }, ["on", 10], ["off", 90]] }
---
apiVersion: core.openfeature.dev/v1beta1
kind: FeatureFlagSource
metadata: { name: checkout-flags, namespace: progressive }
spec: { sources: [{ source: checkout, provider: kubernetes }] }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'k8s/networkpolicy.yaml' @'
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata: { name: default-deny, namespace: progressive }
spec: { podSelector: {}, policyTypes: [Ingress, Egress] }
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata: { name: checkout, namespace: progressive }
spec: { minAvailable: 4, selector: { matchLabels: { app: checkout } } }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'k8s/kustomization.yaml' @'
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [namespace.yaml, services.yaml, analysis.yaml, rollout.yaml, openfeature.yaml, networkpolicy.yaml]
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'scripts/validate.ps1' @'
$ErrorActionPreference='Stop'
python -m unittest discover -s tests -v
if($LASTEXITCODE){throw 'Delivery tests failed.'}
python scripts/simulate.py | Out-Null
docker compose config --quiet
if($LASTEXITCODE){throw 'Compose validation failed.'}
kubectl kustomize k8s | Out-Null
Write-Host 'Progressive-delivery contracts validated.'
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root '.github/workflows/ci.yml' @'
name: progressive-delivery-ci
on: { pull_request: {}, push: { branches: [main] } }
permissions: { contents: read }
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: python -m unittest discover -s tests -v
      - run: python scripts/simulate.py
      - run: docker compose config --quiet
      - run: kubectl kustomize k8s >/tmp/progressive.yaml
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/HLD.md' @'
# High-level design

GitOps deploys desired artifacts. Argo Rollouts controls replica and traffic progression. Prometheus analysis decides automated promotion or abort. OpenFeature decouples feature exposure from artifact rollout. Audit records connect commit, image digest, rollout revision, flag revision, metric evidence and operator decision.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/FLAG-GOVERNANCE.md' @'
# Feature-flag governance

Every flag needs owner, purpose, ticket, creation date, expiry, safe default, targeting data classification and removal plan. Authorization for a kill switch is different from authorization for percentage expansion. Never place secrets or sensitive personal attributes in evaluation context. Stale flags are operational debt and must fail governance checks.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/RUNBOOK.md' @'
# Release runbook

When a canary degrades, establish whether the cause is artifact, configuration, traffic, dependency or metric failure. Abort artifact rollout for code/config regressions; disable a flag for isolated feature behavior. Record which control restored service. Reconcile Git after emergency action so the controller does not reintroduce the fault.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/EXERCISES.md' @'
# Required exercises

1. Trigger automatic rollback with a controlled 5xx increase.
2. Demonstrate a metric outage becoming inconclusive rather than successful.
3. Release a feature to employees, then 5%, 20% and 100%.
4. Remove an expired flag from code and configuration.
5. Compare blue-green and canary recovery behavior.
6. Document an emergency GitOps reconciliation after manual abort.
'@ -WhatIfMode:$WhatIfMode
[pscustomobject]@{Project='31-progressive-delivery-openfeature-platform';Root=$root;Files=$script:Generated.Count}
