param([switch]$WhatIfMode)
. (Join-Path $PSScriptRoot 'Common.ps1')
$root=Join-Path $script:ProjectsRoot '32-cloud-native-detection-response-platform'
Write-TemplateFile $root '.template-owned' 'Generated by tools/module20-projects. Additional user files are never deleted.' -WhatIfMode:$WhatIfMode
Write-TemplateFile $root '.gitignore' @'
__pycache__/
.env
evidence/*.actual.json
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'README.md' @'
# Cloud-Native Detection and Incident Response Platform

A security-operations capstone using Falco 0.44.1, eBPF/runtime signals, Tetragon policies, Kubernetes audit events, Sigma-style analytics, detection-as-code tests, evidence preservation and containment runbooks.

```mermaid
flowchart LR
  K[Kernel / eBPF] --> F[Falco]
  A[Kubernetes audit] --> N[Normalizer]
  C[Cloud audit] --> N
  F --> N
  N --> D[Detection rules]
  D --> Q[Alert queue]
  Q --> T[Triage]
  T --> E[Evidence]
  T --> R[Containment / recovery]
```

## Outcomes

- Treat detections like production code with fixtures, expected matches and false-positive review.
- Correlate runtime, Kubernetes and cloud-control-plane identities.
- Separate high-confidence prevention from detection-only learning rules.
- Preserve timelines, hashes, commands and ownership for incident evidence.
- Rehearse containment without destroying evidence or expanding blast radius.

## Start

```powershell
python -m unittest discover -s tests -v
python scripts/hunt.py evidence/events.jsonl detections/rules.json
docker compose config
kubectl kustomize k8s
```

Falco needs privileged host access and a compatible Linux kernel. Run it only in a disposable Linux lab or an approved security environment; Compose validation does not grant permission to monitor a developer workstation.

`k8s/audit-policy.yaml` is kube-apiserver configuration, not an object applied through the Kubernetes API, so it is intentionally excluded from the Kustomization.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'detections/__init__.py' '' -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'detections/engine.py' @'
from datetime import datetime,timezone

ALLOWED_SEVERITIES={"low","medium","high","critical"}

def matches(rule:dict,event:dict)->bool:
 return all(event.get(field)==value for field,value in rule.get("equals",{}).items()) and all(value in str(event.get(field,"")) for field,value in rule.get("contains",{}).items())

def detect(rules:list[dict],events:list[dict])->list[dict]:
 findings=[]
 for event in events:
  for rule in rules:
   if rule.get("enabled",True) and matches(rule,event):findings.append({"rule":rule["id"],"severity":rule["severity"],"event_id":event["id"],"owner":rule["owner"]})
 return findings

def validate_rule(rule:dict,today:datetime|None=None)->list[str]:
 today=today or datetime.now(timezone.utc);errors=[]
 for field in ("id","title","owner","severity","runbook","test_fixture","review_after"):
  if not rule.get(field):errors.append(f"missing {field}")
 if rule.get("severity") not in ALLOWED_SEVERITIES:errors.append("invalid severity")
 try:
  review=datetime.fromisoformat(str(rule.get("review_after","")).replace("Z","+00:00"))
  if review<today:errors.append("review overdue")
 except ValueError:errors.append("invalid review date")
 return errors
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'detections/rules.json' @'
[
  {"id":"CNDR-001","title":"Interactive shell in production container","owner":"security-platform","severity":"high","equals":{"environment":"prod","event_type":"process_start"},"contains":{"command":"/bin/sh"},"runbook":"docs/RUNBOOK.md#interactive-shell","test_fixture":"evt-1","review_after":"2027-01-31T00:00:00Z","enabled":true},
  {"id":"CNDR-002","title":"Kubernetes secret read by unexpected identity","owner":"identity-security","severity":"critical","equals":{"event_type":"k8s_audit","verb":"get","resource":"secrets","authorized":true},"contains":{"principal":"system:serviceaccount:default:"},"runbook":"docs/RUNBOOK.md#secret-access","test_fixture":"evt-2","review_after":"2027-01-31T00:00:00Z","enabled":true},
  {"id":"CNDR-003","title":"Package manager executed in immutable workload","owner":"security-platform","severity":"medium","equals":{"event_type":"process_start","immutable":true},"contains":{"command":"apt-get"},"runbook":"docs/RUNBOOK.md#runtime-drift","test_fixture":"evt-3","review_after":"2027-01-31T00:00:00Z","enabled":true}
]
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'evidence/events.jsonl' @'
{"id":"evt-1","timestamp":"2026-08-16T01:00:00Z","event_type":"process_start","environment":"prod","namespace":"payments","pod":"checkout-1","principal":"system:serviceaccount:payments:checkout","command":"/bin/sh -c whoami","immutable":true}
{"id":"evt-2","timestamp":"2026-08-16T01:01:00Z","event_type":"k8s_audit","verb":"get","resource":"secrets","namespace":"payments","principal":"system:serviceaccount:default:debug","authorized":true}
{"id":"evt-3","timestamp":"2026-08-16T01:02:00Z","event_type":"process_start","environment":"prod","namespace":"catalog","pod":"catalog-2","principal":"system:serviceaccount:catalog:api","command":"apt-get install curl","immutable":true}
{"id":"evt-4","timestamp":"2026-08-16T01:03:00Z","event_type":"process_start","environment":"dev","namespace":"sandbox","pod":"toolbox","principal":"developer","command":"/bin/bash","immutable":false}
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'evidence/incident-example.json' @'
{"incident_id":"INC-2026-001","classification":"credential-misuse","opened_at":"2026-08-16T01:04:00Z","commander":"replace","affected_assets":["payments/checkout-1"],"evidence_hashes":{"events.jsonl":"replace"},"containment":["revoke workload identity","isolate namespace"],"customer_impact":"under investigation","closed_at":null}
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'scripts/hunt.py' @'
import json,sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from detections.engine import detect,validate_rule

if len(sys.argv)!=3:raise SystemExit("usage: hunt.py EVENTS.jsonl RULES.json")
events=[json.loads(line) for line in Path(sys.argv[1]).read_text().splitlines() if line.strip()]
rules=json.loads(Path(sys.argv[2]).read_text())
errors={rule["id"]:validate_rule(rule) for rule in rules if validate_rule(rule)}
if errors:raise SystemExit(f"invalid rules: {errors}")
print(json.dumps({"events":len(events),"findings":detect(rules,events)},indent=2))
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'tests/test_engine.py' @'
import unittest
from datetime import datetime,timezone
from detections.engine import detect,validate_rule

RULE={"id":"R1","title":"shell","owner":"security","severity":"high","equals":{"event_type":"process_start","environment":"prod"},"contains":{"command":"/bin/sh"},"runbook":"runbook","test_fixture":"e1","review_after":"2027-01-01T00:00:00Z"}

class DetectionTests(unittest.TestCase):
 def test_expected_match(self):self.assertEqual(len(detect([RULE],[{"id":"e1","event_type":"process_start","environment":"prod","command":"/bin/sh"}])),1)
 def test_dev_event_is_suppressed_by_scope(self):self.assertEqual(detect([RULE],[{"id":"e2","event_type":"process_start","environment":"dev","command":"/bin/sh"}]),[])
 def test_disabled_rule_does_not_fire(self):
  rule={**RULE,"enabled":False};self.assertEqual(detect([rule],[{"id":"e1","event_type":"process_start","environment":"prod","command":"/bin/sh"}]),[])
 def test_rule_contract(self):self.assertEqual(validate_rule(RULE,datetime(2026,8,16,tzinfo=timezone.utc)),[])
 def test_overdue_review_fails(self):self.assertIn("review overdue",validate_rule({**RULE,"review_after":"2025-01-01T00:00:00Z"},datetime(2026,8,16,tzinfo=timezone.utc)))

if __name__=="__main__":unittest.main()
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'falco/custom-rules.yaml' @'
- rule: Interactive shell in production container
  desc: Detect shells launched in production application containers
  condition: container and spawned_process and k8s.ns.name in (prod, production, payments) and proc.name in (sh, bash, dash, zsh)
  output: "Interactive shell (user=%user.name command=%proc.cmdline container=%container.id pod=%k8s.pod.name ns=%k8s.ns.name)"
  priority: WARNING
  tags: [container, process, mitre_execution]
- rule: Package manager in immutable workload
  desc: Detect package installation that indicates runtime drift
  condition: container and spawned_process and proc.name in (apt, apt-get, apk, yum, dnf) and not k8s.ns.name in (dev, sandbox)
  output: "Package manager executed (command=%proc.cmdline pod=%k8s.pod.name ns=%k8s.ns.name)"
  priority: NOTICE
  tags: [container, drift]
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'falco/values.yaml' @'
driver: { kind: modern_ebpf }
falco:
  json_output: true
  json_include_output_property: true
  http_output: { enabled: true, url: http://alert-router.security-ops.svc:8080/events }
  metrics: { enabled: true, interval: 30m }
customRules:
  masterclass_rules.yaml: |-
    # Copy the reviewed rules from falco/custom-rules.yaml during the exercise.
serviceMonitor: { create: true }
tolerations: [{ operator: Exists }]
resources: { requests: { cpu: 100m, memory: 256Mi }, limits: { cpu: "1", memory: 1Gi } }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'tetragon/process-policy.yaml' @'
apiVersion: cilium.io/v1alpha1
kind: TracingPolicyNamespaced
metadata: { name: sensitive-process-execution, namespace: payments }
spec:
  kprobes:
    - call: security_file_open
      syscall: false
      args: [{ index: 0, type: file }]
      selectors:
        - matchArgs: [{ index: 0, operator: Prefix, values: [/etc/shadow, /var/run/secrets] }]
          matchActions: [{ action: Post }]
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'sigma/kubernetes-secret-access.yml' @'
title: Kubernetes Secret Read by Default Namespace Identity
id: 64dd349c-74db-4fc6-9da3-bde9a340fdaa
status: test
logsource: { product: kubernetes, service: audit }
detection:
  selection:
    verb: get
    objectRef.resource: secrets
    user.username|startswith: "system:serviceaccount:default:"
  condition: selection
level: high
falsepositives: [Approved secret synchronization controllers]
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docker-compose.yml' @'
services:
  falco:
    image: falcosecurity/falco:0.44.1
    privileged: true
    pid: host
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock:ro
      - /proc:/host/proc:ro
      - /boot:/host/boot:ro
      - /lib/modules:/host/lib/modules:ro
      - /usr:/host/usr:ro
      - ./falco/custom-rules.yaml:/etc/falco/rules.d/masterclass.yaml:ro
    command: [falco, -o, json_output=true]
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'k8s/platform.yaml' @'
apiVersion: v1
kind: Namespace
metadata: { name: security-ops, labels: { pod-security.kubernetes.io/enforce: restricted } }
---
apiVersion: v1
kind: ConfigMap
metadata: { name: alert-routing, namespace: security-ops }
data:
  routing.json: '{"critical":"pager","high":"security-queue","medium":"hunt-queue","low":"archive"}'
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata: { name: default-deny, namespace: security-ops }
spec: { podSelector: {}, policyTypes: [Ingress, Egress] }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'k8s/audit-policy.yaml' @'
apiVersion: audit.k8s.io/v1
kind: Policy
omitStages: [RequestReceived]
rules:
  - level: RequestResponse
    resources: [{ group: "", resources: [secrets, serviceaccounts/token] }]
  - level: Request
    resources: [{ group: rbac.authorization.k8s.io, resources: [roles, rolebindings, clusterroles, clusterrolebindings] }]
  - level: Metadata
    verbs: [create, update, patch, delete]
  - level: None
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'k8s/kustomization.yaml' @'
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [platform.yaml]
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'scripts/validate.ps1' @'
$ErrorActionPreference='Stop'
python -m unittest discover -s tests -v
if($LASTEXITCODE){throw 'Detection tests failed.'}
python scripts/hunt.py evidence/events.jsonl detections/rules.json | Out-Null
if($LASTEXITCODE){throw 'Detection replay failed.'}
docker compose config --quiet
kubectl kustomize k8s | Out-Null
Write-Host 'Detection and response contracts validated.'
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root '.github/workflows/ci.yml' @'
name: detection-response-ci
on: { pull_request: {}, push: { branches: [main] } }
permissions: { contents: read }
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: python -m unittest discover -s tests -v
      - run: python scripts/hunt.py evidence/events.jsonl detections/rules.json >/tmp/findings.json
      - run: docker compose config --quiet
      - run: kubectl kustomize k8s >/tmp/security-ops.yaml
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/HLD.md' @'
# High-level design

Sensors remain replaceable. Events are normalized into a stable detection contract, enriched with workload and cloud identity, evaluated by versioned rules and routed by severity. Evidence storage is access-controlled and immutable. Response automation is gated by confidence, scope and rollback rather than alert severity alone.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/RUNBOOK.md' @'
# Incident runbook

## Interactive shell

Validate identity, change ticket and workload namespace. Preserve the event and surrounding process/network timeline. If unauthorized, isolate the workload, revoke its identity and replace the pod from a trusted image; do not investigate by modifying the suspect container.

## Secret access

Confirm the audit decision and credential target. Revoke/rotate exposed material, preserve audit logs, scope all uses of the identity and review RBAC ancestry.

## Runtime drift

Compare the running image digest and filesystem changes with deployment evidence. Replace rather than repair immutable workloads.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/DETECTION-STANDARD.md' @'
# Detection standard

Every rule needs hypothesis, data source, severity rationale, owner, fixture, expected match, negative test, false-positive guidance, runbook and review date. Measure precision, recall on replay data, alert volume, triage latency and response outcome. A detection that nobody owns is disabled debt, not coverage.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/EXERCISES.md' @'
# Required exercises

1. Generate a controlled shell event in a disposable cluster.
2. Replay the fixtures and add a negative test before tuning a rule.
3. Correlate a service account from runtime to Kubernetes and cloud audit logs.
4. Preserve and hash evidence before containment.
5. Compare detect-only and enforce modes for a Tetragon policy.
6. Run a tabletop credential-theft incident with communications and recovery gates.
'@ -WhatIfMode:$WhatIfMode
[pscustomobject]@{Project='32-cloud-native-detection-response-platform';Root=$root;Files=$script:Generated.Count}
