param([switch]$WhatIfMode)
. (Join-Path $PSScriptRoot 'Common.ps1')
$root=Join-Path $script:ProjectsRoot '33-temporal-durable-workflow-platform'
Write-TemplateFile $root '.template-owned' 'Generated by tools/module20-projects. Additional user files are never deleted.' -WhatIfMode:$WhatIfMode
Write-TemplateFile $root '.gitignore' @'
.env
__pycache__/
.venv/
history/*.actual.json
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'README.md' @'
# Temporal Durable Workflow Platform

A distributed-systems capstone using Temporal 1.31, Python SDK workflows, activities, signals, queries, retries, timeouts, idempotency, saga compensation, history replay, worker versioning and production persistence operations.

```mermaid
sequenceDiagram
  participant API as Starter API
  participant T as Temporal Service
  participant W as Worker
  participant P as Payment
  participant I as Inventory
  API->>T: Start Fulfillment(orderId)
  T->>W: Schedule activity
  W->>P: Authorize payment (idempotency key)
  W->>I: Reserve inventory
  alt reservation fails
    W->>P: Compensate authorization
  end
  W-->>T: Durable result/history
```

## Outcomes

- Explain durable execution, event history and deterministic workflow code.
- Design activity retry, timeout, heartbeat and idempotency boundaries.
- Implement signals, queries, cancellation and saga compensation.
- Replay histories before deploying workflow-code changes.
- Operate Temporal persistence, visibility, worker queues and safe upgrades.

## Start

```powershell
docker compose config
python -m unittest discover -s tests -v
python scripts/replay.py history/fulfillment.json
kubectl kustomize k8s
```

For a live lab, copy `.env.example` to `.env`, start Compose, install the Python dependencies and run the worker/starter. The unit and replay exercises remain dependency-free so workflow design can be validated before infrastructure is available.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root '.env.example' @'
TEMPORAL_ADDRESS=temporal:7233
TEMPORAL_NAMESPACE=default
TASK_QUEUE=fulfillment
POSTGRES_USER=temporal
POSTGRES_PASSWORD=local-development-only
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'requirements.txt' @'
temporalio==1.27.2
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'workflow/__init__.py' '' -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'workflow/model.py' @'
from dataclasses import dataclass,field,replace

TRANSITIONS={
 "created":{"payment_authorized"},
 "payment_authorized":{"inventory_reserved","payment_released"},
 "inventory_reserved":{"shipped","inventory_released"},
 "inventory_released":{"payment_released"},
 "payment_released":{"cancelled"},
 "cancelled":set(),
 "shipped":set(),
}

@dataclass(frozen=True)
class OrderState:
 order_id:str
 status:str="created"
 processed_event_ids:frozenset[str]=field(default_factory=frozenset)

def apply(state:OrderState,event:dict)->OrderState:
 event_id=str(event["id"]);next_status=str(event["type"])
 if event_id in state.processed_event_ids:return state
 if next_status not in TRANSITIONS.get(state.status,set()):raise ValueError(f"invalid transition {state.status}->{next_status}")
 return replace(state,status=next_status,processed_event_ids=state.processed_event_ids|{event_id})

def retry_delay_seconds(attempt:int,base:int=2,cap:int=60)->int:
 if attempt<1:raise ValueError("attempt starts at one")
 return min(cap,base**(attempt-1))

def activity_key(workflow_id:str,activity_name:str)->str:
 if not workflow_id or not activity_name:raise ValueError("identity parts are required")
 return f"{workflow_id}:{activity_name}"
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'workflow/temporal_app.py' @'
from dataclasses import dataclass
from datetime import timedelta
from temporalio import activity,workflow
from temporalio.common import RetryPolicy

@dataclass
class Order:
 order_id:str
 sku:str
 quantity:int

@activity.defn
async def authorize_payment(order:Order)->str:
 activity.heartbeat({"order_id":order.order_id,"step":"authorize"})
 return f"auth-{order.order_id}"

@activity.defn
async def reserve_inventory(order:Order)->str:
 activity.heartbeat({"order_id":order.order_id,"step":"reserve"})
 return f"reservation-{order.order_id}"

@activity.defn
async def release_payment(authorization_id:str)->None:
 activity.heartbeat({"authorization_id":authorization_id,"step":"compensate"})

@activity.defn
async def release_inventory(reservation_id:str)->None:
 activity.heartbeat({"reservation_id":reservation_id,"step":"compensate"})

@workflow.defn
class FulfillmentWorkflow:
 def __init__(self)->None:
  self.cancel_requested=False
  self.status="created"

 @workflow.run
 async def run(self,order:Order)->dict:
  retry=RetryPolicy(initial_interval=timedelta(seconds=2),backoff_coefficient=2,maximum_interval=timedelta(minutes=1),maximum_attempts=5)
  authorization=await workflow.execute_activity(authorize_payment,order,start_to_close_timeout=timedelta(seconds=30),heartbeat_timeout=timedelta(seconds=10),retry_policy=retry)
  self.status="payment_authorized"
  try:
   reservation=await workflow.execute_activity(reserve_inventory,order,start_to_close_timeout=timedelta(seconds=30),heartbeat_timeout=timedelta(seconds=10),retry_policy=retry)
   self.status="inventory_reserved"
  except Exception:
   await workflow.execute_activity(release_payment,authorization,start_to_close_timeout=timedelta(seconds=30),retry_policy=retry)
   self.status="payment_released"
   raise
  await workflow.wait_condition(lambda:self.cancel_requested or self.status=="ship_approved")
  if self.cancel_requested:
   await workflow.execute_activity(release_inventory,reservation,start_to_close_timeout=timedelta(seconds=30),retry_policy=retry)
   await workflow.execute_activity(release_payment,authorization,start_to_close_timeout=timedelta(seconds=30),retry_policy=retry)
   self.status="cancelled"
  else:self.status="shipped"
  return {"order_id":order.order_id,"authorization":authorization,"reservation":reservation,"status":self.status}

 @workflow.signal
 def approve_shipping(self)->None:self.status="ship_approved"

 @workflow.signal
 def cancel(self)->None:self.cancel_requested=True

 @workflow.query
 def current_status(self)->str:return self.status
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'worker.py' @'
import asyncio,os
from temporalio.client import Client
from temporalio.worker import Worker
from workflow.temporal_app import FulfillmentWorkflow,authorize_payment,release_inventory,release_payment,reserve_inventory

async def main():
 client=await Client.connect(os.getenv("TEMPORAL_ADDRESS","localhost:7233"),namespace=os.getenv("TEMPORAL_NAMESPACE","default"))
 worker=Worker(client,task_queue=os.getenv("TASK_QUEUE","fulfillment"),workflows=[FulfillmentWorkflow],activities=[authorize_payment,reserve_inventory,release_inventory,release_payment])
 await worker.run()

if __name__=="__main__":asyncio.run(main())
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'starter.py' @'
import asyncio,os
from temporalio.client import Client
from workflow.temporal_app import FulfillmentWorkflow,Order

async def main():
 client=await Client.connect(os.getenv("TEMPORAL_ADDRESS","localhost:7233"))
 order=Order("order-1001","SKU-1",1)
 handle=await client.start_workflow(FulfillmentWorkflow.run,order,id=f"fulfillment-{order.order_id}",task_queue=os.getenv("TASK_QUEUE","fulfillment"))
 print(handle.id)

if __name__=="__main__":asyncio.run(main())
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'Dockerfile' @'
FROM python:3.14.1-slim
RUN groupadd -g 10001 app && useradd -u 10001 -g app --no-create-home app
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY --chown=10001:10001 workflow workflow
COPY --chown=10001:10001 worker.py starter.py ./
USER 10001:10001
CMD ["python", "worker.py"]
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docker-compose.yml' @'
services:
  postgres:
    image: postgres:16.6-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-temporal}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-local-development-only}
    volumes: [temporal-db:/var/lib/postgresql/data]
    healthcheck: { test: [CMD-SHELL, "pg_isready -U $${POSTGRES_USER}"], interval: 5s, timeout: 3s, retries: 30 }
  temporal:
    image: temporalio/auto-setup:1.31.2
    depends_on: { postgres: { condition: service_healthy } }
    environment:
      DB: postgres12
      DB_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER:-temporal}
      POSTGRES_PWD: ${POSTGRES_PASSWORD:-local-development-only}
      POSTGRES_SEEDS: postgres
      DYNAMIC_CONFIG_FILE_PATH: config/dynamicconfig/development-sql.yaml
    ports: ["7233:7233"]
  temporal-ui:
    image: temporalio/ui:2.41.0
    depends_on: [temporal]
    environment: { TEMPORAL_ADDRESS: temporal:7233, TEMPORAL_CORS_ORIGINS: "http://localhost:3000" }
    ports: ["8233:8080"]
  worker:
    build: .
    depends_on: [temporal]
    environment: { TEMPORAL_ADDRESS: temporal:7233, TEMPORAL_NAMESPACE: default, TASK_QUEUE: fulfillment }
    restart: unless-stopped
volumes: { temporal-db: {} }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'history/fulfillment.json' @'
{"workflow_id":"fulfillment-order-1001","events":[{"id":"1","type":"payment_authorized"},{"id":"2","type":"inventory_reserved"},{"id":"2","type":"inventory_reserved"},{"id":"3","type":"shipped"}],"expected_status":"shipped"}
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'scripts/replay.py' @'
import json,sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from workflow.model import OrderState,apply

if len(sys.argv)!=2:raise SystemExit("usage: replay.py HISTORY.json")
history=json.loads(Path(sys.argv[1]).read_text());state=OrderState(history["workflow_id"])
for event in history["events"]:state=apply(state,event)
if state.status!=history["expected_status"]:raise SystemExit(f"expected {history['expected_status']}, got {state.status}")
print(json.dumps({"workflow_id":state.order_id,"status":state.status,"unique_events":len(state.processed_event_ids)},indent=2))
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'tests/test_model.py' @'
import unittest
from workflow.model import OrderState,activity_key,apply,retry_delay_seconds

class WorkflowModelTests(unittest.TestCase):
 def test_happy_path(self):
  state=OrderState("order-1");state=apply(state,{"id":"1","type":"payment_authorized"});state=apply(state,{"id":"2","type":"inventory_reserved"});state=apply(state,{"id":"3","type":"shipped"});self.assertEqual(state.status,"shipped")
 def test_duplicate_event_is_idempotent(self):
  state=apply(OrderState("order-1"),{"id":"1","type":"payment_authorized"});self.assertEqual(apply(state,{"id":"1","type":"payment_authorized"}),state)
 def test_invalid_transition_fails(self):
  with self.assertRaises(ValueError):apply(OrderState("order-1"),{"id":"1","type":"shipped"})
 def test_compensation_path(self):
  state=apply(OrderState("order-1"),{"id":"1","type":"payment_authorized"});state=apply(state,{"id":"2","type":"payment_released"});self.assertEqual(state.status,"payment_released")
 def test_full_cancellation_path(self):
  state=apply(OrderState("order-1"),{"id":"1","type":"payment_authorized"});state=apply(state,{"id":"2","type":"inventory_reserved"});state=apply(state,{"id":"3","type":"inventory_released"});state=apply(state,{"id":"4","type":"payment_released"});state=apply(state,{"id":"5","type":"cancelled"});self.assertEqual(state.status,"cancelled")
 def test_bounded_backoff(self):self.assertEqual(retry_delay_seconds(10),60)
 def test_activity_idempotency_key(self):self.assertEqual(activity_key("wf-1","charge"),"wf-1:charge")

if __name__=="__main__":unittest.main()
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'helm/temporal-values.yaml' @'
server:
  replicaCount: 3
  config:
    numHistoryShards: 512
    persistence:
      default: { driver: sql, sql: { driver: postgres12, host: replace-rw.database.svc, port: 5432, database: temporal, user: temporal, existingSecret: temporal-db } }
      visibility: { driver: sql, sql: { driver: postgres12, host: replace-rw.database.svc, port: 5432, database: temporal_visibility, user: temporal, existingSecret: temporal-db } }
  resources: { requests: { cpu: 500m, memory: 1Gi }, limits: { cpu: "2", memory: 4Gi } }
  podDisruptionBudget: { enabled: true, minAvailable: 2 }
prometheus: { enabled: false }
grafana: { enabled: false }
elasticsearch: { enabled: false }
cassandra: { enabled: false }
mysql: { enabled: false }
postgresql: { enabled: false }
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'k8s/worker.yaml' @'
apiVersion: v1
kind: Namespace
metadata: { name: workflows, labels: { pod-security.kubernetes.io/enforce: restricted } }
---
apiVersion: v1
kind: ServiceAccount
metadata: { name: fulfillment-worker, namespace: workflows }
---
apiVersion: apps/v1
kind: Deployment
metadata: { name: fulfillment-worker, namespace: workflows }
spec:
  replicas: 3
  selector: { matchLabels: { app: fulfillment-worker } }
  template:
    metadata: { labels: { app: fulfillment-worker } }
    spec:
      serviceAccountName: fulfillment-worker
      terminationGracePeriodSeconds: 60
      securityContext: { runAsNonRoot: true, seccompProfile: { type: RuntimeDefault } }
      containers:
        - name: worker
          image: ghcr.io/replace/fulfillment-worker@sha256:replace
          env:
            - { name: TEMPORAL_ADDRESS, value: temporal-frontend.temporal.svc:7233 }
            - { name: TEMPORAL_NAMESPACE, value: production }
            - { name: TASK_QUEUE, value: fulfillment-v1 }
          resources: { requests: { cpu: 200m, memory: 256Mi }, limits: { cpu: "2", memory: 1Gi } }
          securityContext: { allowPrivilegeEscalation: false, readOnlyRootFilesystem: true, capabilities: { drop: [ALL] } }
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata: { name: fulfillment-worker, namespace: workflows }
spec: { minAvailable: 2, selector: { matchLabels: { app: fulfillment-worker } } }
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata: { name: worker-egress, namespace: workflows }
spec:
  podSelector: { matchLabels: { app: fulfillment-worker } }
  policyTypes: [Ingress, Egress]
  egress: [{ to: [{ namespaceSelector: { matchLabels: { kubernetes.io/metadata.name: temporal } } }], ports: [{ protocol: TCP, port: 7233 }] }]
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'k8s/kustomization.yaml' @'
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [worker.yaml]
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'scripts/validate.ps1' @'
$ErrorActionPreference='Stop'
python -m unittest discover -s tests -v
if($LASTEXITCODE){throw 'Workflow model tests failed.'}
python scripts/replay.py history/fulfillment.json | Out-Null
if($LASTEXITCODE){throw 'History replay failed.'}
python -m py_compile workflow/*.py worker.py starter.py
docker compose config --quiet
kubectl kustomize k8s | Out-Null
Write-Host 'Temporal workflow contracts validated.'
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root '.github/workflows/ci.yml' @'
name: temporal-workflow-ci
on: { pull_request: {}, push: { branches: [main] } }
permissions: { contents: read }
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: python -m unittest discover -s tests -v
      - run: python scripts/replay.py history/fulfillment.json
      - run: python -m py_compile workflow/*.py worker.py starter.py
      - run: docker compose config --quiet
      - run: kubectl kustomize k8s >/tmp/workers.yaml
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/HLD.md' @'
# High-level design

Temporal service owns durable history and task routing; workers own deterministic workflow and activity implementations. Activities call unreliable external systems through idempotency keys. Persistence and visibility databases are operated independently. Task queues isolate domains and versions, while metrics expose schedule-to-start latency, failures and backlog.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/DETERMINISM.md' @'
# Determinism and versioning

Workflow code must make the same decisions when replaying the same history. Do not read wall-clock time, random values, environment variables, network services or mutable global state directly in workflow code. Use Temporal APIs, activities and explicit versioning. Replay representative production histories before rollout and keep compatible workers until old executions complete or migrate.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/RUNBOOK.md' @'
# Temporal runbook

Separate service availability, persistence latency, task-queue backlog, worker capacity, workflow failure and activity dependency failures. Do not blindly reset workflows: first understand history and external side effects. During worker rollout, monitor nondeterminism errors and schedule-to-start latency. Schema upgrades precede server upgrades and require tested backups.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/THREAT-MODEL.md' @'
# Threat model

Threats include unauthorized workflow starts/signals, sensitive payloads in history, activity credential theft, replay-incompatible releases, task-queue impersonation and database tampering. Controls include mTLS/API authorization, payload encryption codecs, workload identity, namespace isolation, replay gates, least-privilege activity credentials and immutable audit retention.
'@ -WhatIfMode:$WhatIfMode
Write-TemplateFile $root 'docs/EXERCISES.md' @'
# Required exercises

1. Kill a worker during an activity and observe durable recovery.
2. Make an activity fail repeatedly and inspect bounded retry behavior.
3. Replay history against an intentionally nondeterministic change.
4. Execute a compensation path without double-releasing payment.
5. Introduce worker build IDs and migrate a long-running workflow safely.
6. Rehearse persistence schema and Temporal server upgrade rollback.
'@ -WhatIfMode:$WhatIfMode
[pscustomobject]@{Project='33-temporal-durable-workflow-platform';Root=$root;Files=$script:Generated.Count}
