Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$script:Utf8NoBom = [System.Text.UTF8Encoding]::new($false)
$script:WorkspaceRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$script:ProjectsRoot = Join-Path $script:WorkspaceRoot '20. Final Mega Capstone Project\projects'
$script:Generated = [System.Collections.Generic.List[string]]::new()

function Expand-ProjectTemplate {
    param([string]$Text, [hashtable]$Values)
    $result = $Text
    foreach ($key in $Values.Keys) { $result = $result.Replace("@@$key@@", [string]$Values[$key]) }
    return $result
}

function Write-TemplateFile {
    param([string]$Root, [string]$Path, [string]$Content, [switch]$WhatIfMode)
    $target = Join-Path $Root ($Path -replace '/', [IO.Path]::DirectorySeparatorChar)
    if (-not $WhatIfMode) {
        [IO.Directory]::CreateDirectory((Split-Path -Parent $target)) | Out-Null
        $text = $Content.Replace("`r`n", "`n").Replace("`r", "`n").TrimEnd() + "`n"
        [IO.File]::WriteAllText($target, $text, $script:Utf8NoBom)
    }
    $script:Generated.Add($target)
}

function Get-ProjectValues {
    param([hashtable]$Project)
    $table = [System.Collections.Generic.List[string]]::new()
    $table.Add('| Workload | Responsibility | Port | Health |')
    $table.Add('|---|---|---:|---|')
    foreach ($w in $Project.Workloads) { $table.Add("| ``$($w.Name)`` | $($w.Responsibility) | $($w.Port) | ``$($w.Health)`` |") }
    return @{
        ID=$Project.Id;TITLE=$Project.Title;TYPE=$Project.Type;BACKEND=$Project.Backend;FRONTEND=$Project.Frontend
        DOMAIN=$Project.Domain;NAMESPACE=$Project.Namespace;PORT=$Project.PublicPort;ENTRY=$Project.Entry;UI=$Project.Ui
        WORKLOAD_TABLE=($table -join "`n");DIAGRAM=$Project.Diagram
    }
}

function New-ProjectDocs {
    param([string]$Root,[hashtable]$Project,[switch]$WhatIfMode)
    $v=Get-ProjectValues $Project
    Write-TemplateFile $Root '.template-owned' 'Generated by tools/module20-projects. Additional user files are never deleted.' -WhatIfMode:$WhatIfMode
    Write-TemplateFile $Root '.gitignore' @'
.env
.terraform/
*.tfstate*
*.tfplan
node_modules/
target/
vendor/
build/
dist/
coverage/
__pycache__/
.pytest_cache/
*.db
*.sqlite*
*.log
'@ -WhatIfMode:$WhatIfMode
    Write-TemplateFile $Root '.dockerignore' @'
.git
.github
.env
**/.env
**/node_modules
**/dist
**/.next
**/target
**/vendor
**/build
**/__pycache__
.terraform
*.tfstate*
*.tfplan
docs
ansible
argocd
helm
k8s
observability
security
'@ -WhatIfMode:$WhatIfMode
    Write-TemplateFile $Root '.env.example' (Expand-ProjectTemplate @'
PROJECT_NAME=@@ID@@
ENVIRONMENT=local
LOG_LEVEL=info
REGISTRY=local
IMAGE_TAG=dev
PUBLIC_PORT=@@PORT@@
POSTGRES_USER=app
POSTGRES_PASSWORD=local-development-only
POSTGRES_DB=app
'@ $v) -WhatIfMode:$WhatIfMode
    Write-TemplateFile $Root 'README.md' (Expand-ProjectTemplate @'
# @@TITLE@@

Production-oriented **@@TYPE@@** capstone using **@@BACKEND@@** with **@@FRONTEND@@**.

```mermaid
@@DIAGRAM@@
```

## Workloads

@@WORKLOAD_TABLE@@

## Included DevOps assets

- Runnable application and frontend source.
- Non-root multi-stage Dockerfiles and `docker-compose.yml`.
- Kubernetes Deployments, Services, probes, resources, HPA, PDB, Ingress, NetworkPolicy, ConfigMap, Secret example, and Kustomize overlays.
- Helm, Argo CD, Prometheus resources, and Kyverno policy.
- GitHub Actions, Jenkins, Ansible, and Terraform for AWS VPC/EKS/ECR/optional RDS.
- HLD, LLD, dependency register, threat model, and operations runbook.

## Run locally

```bash
cp .env.example .env
docker compose config
docker compose build
docker compose up -d
curl http://localhost:@@PORT@@/health
```

Open `http://localhost:@@PORT@@`. Stop with `docker compose down`; add `--volumes` only for disposable local data.

## Validate

```bash
bash scripts/test.sh
docker compose build
docker compose up -d
bash scripts/smoke-test.sh http://localhost:@@PORT@@
docker compose down
```

Windows: `./scripts/validate.ps1`.

## Kubernetes, Helm, and GitOps

Replace image names and example secrets first.

```bash
kubectl apply -k k8s/overlays/dev
helm lint helm
helm template @@DOMAIN@@ helm --namespace @@NAMESPACE@@
kubectl apply -f argocd/application.yaml
```

## Terraform warning

Terraform creates billable AWS resources. Configure encrypted remote state, review account/region/cost and the exact plan, and apply only through an authorized workflow. Never commit credentials.

## Production gates

1. Replace domains, repository, registry, owners, secrets, and cloud placeholders.
2. Use intentionally operated stateful dependencies with backup, restore, RTO, and RPO evidence.
3. Pin/scan dependencies and images, generate SBOM/provenance, sign artifacts, and enforce admission policy.
4. Define SLIs/SLOs, capacity reserve, alerts, rollout abort conditions, and rollback limits.
5. Test authorization, malformed input, duplicate work, dependency timeout, overload, migration, restore, and reconciliation.

See `docs/HLD.md`, `docs/LLD.md`, `docs/DEPENDENCIES.md`, `docs/VERSION-POLICY.md`, `docs/THREAT-MODEL.md`, and `docs/RUNBOOK.md`.
'@ $v) -WhatIfMode:$WhatIfMode
    Write-TemplateFile $Root 'docs/HLD.md' (Expand-ProjectTemplate @'
# @@TITLE@@ - HLD

## Scope and architecture

The **@@TYPE@@** owns the @@DOMAIN@@ critical journey. It prioritizes correctness, secure boundaries, reversible delivery, observable outcomes, and a path from Compose to Kubernetes.

```mermaid
@@DIAGRAM@@
```

@@WORKLOAD_TABLE@@

## Quality attributes

| Attribute | Initial objective | HLD response |
|---|---|---|
| Availability | 99.9% monthly | Replicas, readiness, PDB, graceful termination |
| Latency | p95 below 500 ms under modeled load | Bounded chain, deadlines, capacity test, degradation |
| Durability | No acknowledged critical write silently lost | Idempotency, authoritative state, backup/restore, reconciliation |
| Security | Least privilege and no production secret in Git | Non-root, RBAC, NetworkPolicy, runtime secret, audit |
| Recovery | Initial RTO 60m / RPO 15m | IaC, GitOps, backup, restore order, exercise |
| Delivery | Reversible immutable release | Scan, digest, readiness, progressive gate, rollback criteria |

These objectives are hypotheses until load, failure, security, and restore evidence exists.

## Critical journey

```mermaid
sequenceDiagram
    actor User
    participant UI as Frontend
    participant Entry as Public entry
    participant Domain as Domain owner
    participant State as Authoritative state
    User->>UI: Begin journey
    UI->>Entry: Validated request and identity
    Entry->>Domain: Bounded contract and deadline
    Domain->>State: Enforce invariant and commit
    State-->>Domain: Durable result
    Domain-->>Entry: Stable outcome
    Entry-->>UI: Response and request ID
    UI-->>User: Confirm outcome
```

## Data, security, reliability, capacity

- Domain owners define identifiers, invariants, transactions, retention, deletion, backup, and reconciliation.
- Cross-boundary writes carry stable idempotency keys; migrations use expand-migrate-contract.
- Trust comes from verified identity and resource authorization, not network location.
- Remote calls have a deadline, bounded safe retry, jitter, isolation, stable error, and telemetry.
- Estimate peak requests/s, payload, service time, concurrency, storage growth, bandwidth, skew, headroom, and failure reserve.

## Delivery

```mermaid
flowchart LR
    Commit --> Test --> Scan --> Image["Immutable image"]
    Image --> Registry --> Desired["Versioned desired state"]
    Desired --> ArgoCD --> Rollout --> Evidence
    Evidence --> Promote
    Evidence --> Rollback
```

## Review checklist

- Actors, journeys, constraints, scale, SLOs, and data sensitivity are measurable.
- Every box has responsibility/owner; every arrow has protocol, identity, timeout, retry, data, and failure meaning.
- Data authority, migration, backup, restore, security, cost, rollout, and operations are explicit.
'@ $v) -WhatIfMode:$WhatIfMode
    Write-TemplateFile $Root 'docs/LLD.md' (Expand-ProjectTemplate @'
# @@TITLE@@ - LLD

## Rules and contracts

- Separate transport, domain, persistence, and provider adapters.
- Enforce invariants in the domain owner, never only in the UI.
- Make errors, timeouts, retries, idempotency, side effects, cancellation, and cleanup explicit.
- Bound request size, queues, connections, workers, memory, retries, logs, and metrics.

@@WORKLOAD_TABLE@@

| Concern | Contract |
|---|---|
| Correlation | Accept/create `X-Request-ID`, return it, log it safely |
| Idempotency | Retryable writes require `Idempotency-Key` and stable outcome |
| Deadline | Internal work finishes before caller deadline |
| Errors | Stable code, safe message, request ID, retryability, correct status |
| Validation | Type, required fields, bounds, size, normalization |
| Security | Authenticate, authorize action/resource, encode output, audit |
| Compatibility | Additive evolution and owned deprecation |

```mermaid
stateDiagram-v2
    [*] --> Received
    Received --> Rejected: invalid or forbidden
    Received --> Validated
    Validated --> Committing
    Committing --> Completed: durable outcome
    Committing --> Uncertain: dependency unknown
    Uncertain --> Completed: reconciliation proves success
    Uncertain --> Failed: reconciliation proves failure
    Rejected --> [*]
    Completed --> [*]
    Failed --> [*]
```

## Persistence, concurrency, and dependencies

- Stable keys, database constraints for uniqueness/idempotency, smallest complete transaction, query-derived indexes, resumable migrations.
- Shared state has an explicit lock, atomic, transaction, actor, queue, or owner.
- Files, sockets, transactions, threads/tasks, temporary data, and locks release on every exit path.
- No infinite retry: safe operation, attempt cap, backoff/jitter, concurrency isolation, caller deadline.

## Telemetry and tests

Emit request count/duration, in-flight work, stable errors, dependency latency, saturation, version, and readiness. Never put secrets or unbounded IDs in metric labels.

Unit tests prove invariants; contract tests prove schema/error/timeout compatibility; integration tests use real adapters; E2E protects the journey; load finds saturation; fault tests prove recovery; security tests reject unauthorized, malformed, oversized, and injected input.

Rollout sequence: expand -> mixed versions -> migrate -> verify -> contract -> cleanup.
'@ $v) -WhatIfMode:$WhatIfMode
    Write-TemplateFile $Root 'docs/DEPENDENCIES.md' (Expand-ProjectTemplate @'
# @@TITLE@@ - Dependencies

| Area | Template | Production requirement |
|---|---|---|
| Backend | @@BACKEND@@ | Patch pin, lockfile, license/provenance/vulnerability review |
| Frontend | @@FRONTEND@@ | Lockfile, CSP, browser policy, scanning |
| Containers | Docker/OCI | Non-root, SBOM, scan, signature, digest |
| Kubernetes | Kustomize/Helm | Supported APIs, policy, upgrade test |
| CI/CD | GitHub/Jenkins/Argo CD | One authority and protected identity |
| Infrastructure | Terraform/AWS | Remote encrypted locked state, reviewed plan |

Record owner, purpose, version strategy, source, license, provenance, transitive risk, failure behavior, observability, upgrade, and replacement for every dependency.
'@ $v) -WhatIfMode:$WhatIfMode
    Write-TemplateFile $Root 'docs/VERSION-POLICY.md' @'
# Runtime and dependency version policy

Defaults were reviewed on **2026-08-16** against upstream lifecycle and release documentation. They are a dated baseline, not a reason to skip a fresh review before deployment.

| Component | Template baseline | Why |
|---|---|---|
| Node.js build/runtime | 24 LTS | Supported LTS; Node 20 reached end-of-life on 2026-03-24 |
| React | 19.2.7 | Current patched React 19.2 release at review time |
| Next.js | 16.2.11 | Active-LTS security release named by the Next.js team in July 2026 |
| Vite | 8.1.x | Current regularly patched Vite line at review time |
| Spring Boot | 4.1.0 | Current stable line at review time; Java 21 is within its supported Java range |
| Amazon EKS | Kubernetes 1.36 | Standard support scheduled through 2027-08-02 |
| Terraform AWS/EKS modules | AWS provider 6.x, EKS module 21.x | Current compatible major contracts at review time |
| Helm | 4.x | Current stable major; Helm 3 is approaching end-of-life |

Authoritative lifecycle references:

- <https://nodejs.org/en/about/previous-releases>
- <https://nextjs.org/blog>
- <https://react.dev/versions>
- <https://vite.dev/releases>
- <https://spring.io/projects/spring-boot/>
- <https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html>
- <https://github.com/terraform-aws-modules/terraform-aws-eks>
- <https://helm.sh/blog/helm-v3-end-of-life/>

## Required maintenance workflow

1. Use Renovate or Dependabot to propose small, scheduled updates to lockfiles, actions, images, charts, providers, and modules.
2. Review upstream security and breaking-change notes; do not merge version-only changes blindly.
3. Rebuild, run unit/integration/contract tests, render manifests, scan artifacts, and execute smoke tests.
4. Promote one immutable image digest through environments; do not rebuild per environment.
5. Record exceptions with owner, risk, compensating controls, expiry date, and upgrade plan.
6. Pin container image digests and GitHub Actions commit SHAs in a real production repository after the learning template has been forked.
'@ -WhatIfMode:$WhatIfMode
    Write-TemplateFile $Root 'docs/THREAT-MODEL.md' (Expand-ProjectTemplate @'
# @@TITLE@@ - Threat Model

Assets: identities, authorization, domain records, audit, credentials, keys, artifacts, infrastructure state, backups, and availability.

| Threat | Prevent | Detect | Respond |
|---|---|---|---|
| Credential theft | Short-lived identity, least privilege | Identity/audit anomaly | Revoke, rotate, contain |
| Broken authorization | Deny default, resource policy | Forbidden/audit review | Disable path, assess exposure |
| Injection | Typed bounds, parameterized queries, encoding | Validation/WAF | Block, patch, assess data |
| Supply chain | Pin, provenance, SBOM, signature | Scan | Quarantine, rollback, rotate identity |
| DoS | Rate/concurrency bounds and degradation | SLO/saturation | Shed, isolate, scale |
| Data leakage | Minimize, encrypt, redact, retention | Audit/unusual reads | Contain, revoke, notify |

Test object authorization, duplicates, oversized/malformed input, path traversal, injection, brute force, stale identity, secret leakage, dependency impersonation, and audit tampering in isolation.
'@ $v) -WhatIfMode:$WhatIfMode
    Write-TemplateFile $Root 'docs/RUNBOOK.md' (Expand-ProjectTemplate @'
# @@TITLE@@ - Runbook

Namespace `@@NAMESPACE@@`; local URL `http://localhost:@@PORT@@`.

1. Capture user symptom, UTC start, environment, scope, and recent change.
2. Check `/health` and one real journey.
3. Inspect rollout, replicas, restarts, events, saturation, and dependencies.
4. Correlate metrics, logs, traces, audit, and change marker with one request ID.
5. Use the smallest reversible containment and record every action.

```bash
kubectl -n @@NAMESPACE@@ get deploy,pod,svc,ingress
kubectl -n @@NAMESPACE@@ get events --sort-by=.lastTimestamp
kubectl -n @@NAMESPACE@@ logs deployment/@@DOMAIN@@-@@ENTRY@@ --tail=200
kubectl -n @@NAMESPACE@@ rollout undo deployment/@@DOMAIN@@-@@ENTRY@@
```

Rollback does not reverse incompatible schemas or external effects. Restore into isolation, verify integrity/access/replay, reconcile uncertain work, then prove the critical journey before traffic.
'@ $v) -WhatIfMode:$WhatIfMode
}

function New-KubernetesFiles {
    param([string]$Root,[hashtable]$Project,[switch]$WhatIfMode)
    $v=Get-ProjectValues $Project
    Write-TemplateFile $Root 'k8s/base/namespace.yaml' (Expand-ProjectTemplate @'
apiVersion: v1
kind: Namespace
metadata:
  name: @@NAMESPACE@@
  labels:
    app.kubernetes.io/part-of: @@DOMAIN@@
    pod-security.kubernetes.io/enforce: restricted
---
apiVersion: v1
kind: ServiceAccount
metadata: { name: @@DOMAIN@@, namespace: @@NAMESPACE@@ }
automountServiceAccountToken: false
'@ $v) -WhatIfMode:$WhatIfMode
    $config=[System.Collections.Generic.List[string]]::new()
    $config.Add((Expand-ProjectTemplate @'
apiVersion: v1
kind: ConfigMap
metadata: { name: @@DOMAIN@@-config, namespace: @@NAMESPACE@@ }
data:
  APP_ENV: "kubernetes"
  LOG_LEVEL: "info"
'@ $v))
    foreach($w in $Project.Workloads){$config.Add(('  {0}_URL: "http://{1}-{2}"' -f $w.Name.ToUpperInvariant(),$Project.Domain,$w.Name))}
    Write-TemplateFile $Root 'k8s/base/configmap.yaml' ($config-join"`n") -WhatIfMode:$WhatIfMode
    $secret=(Expand-ProjectTemplate @'
apiVersion: v1
kind: Secret
metadata:
  name: @@DOMAIN@@-runtime
  namespace: @@NAMESPACE@@
  annotations: { template.devops.example/local-placeholders-only: "true" }
type: Opaque
stringData:
  POSTGRES_USER: app
  POSTGRES_PASSWORD: local-development-only
  POSTGRES_DB: app
  DATABASE_URL: postgresql://app:local-development-only@postgres:5432/app
  JWT_SIGNING_KEY: replace-through-approved-secret-manager
'@ $v)
    Write-TemplateFile $Root 'k8s/base/secret.example.yaml' $secret -WhatIfMode:$WhatIfMode
    Write-TemplateFile $Root 'k8s/overlays/dev/secret.local.yaml' $secret -WhatIfMode:$WhatIfMode
    $resources=[System.Collections.Generic.List[string]]::new()
    $scaling=[System.Collections.Generic.List[string]]::new()
    foreach($w in $Project.Workloads){
        $wv=$v+@{NAME="$($Project.Domain)-$($w.Name)";WORKLOAD=$w.Name;CONTAINER_PORT=$w.Port;HEALTH=$w.Health}
        $resources.Add((Expand-ProjectTemplate @'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: @@NAME@@
  namespace: @@NAMESPACE@@
  labels: { app.kubernetes.io/name: @@WORKLOAD@@, app.kubernetes.io/part-of: @@DOMAIN@@ }
spec:
  replicas: 2
  revisionHistoryLimit: 5
  strategy: { rollingUpdate: { maxUnavailable: 0, maxSurge: 1 } }
  selector:
    matchLabels: { app.kubernetes.io/name: @@WORKLOAD@@, app.kubernetes.io/part-of: @@DOMAIN@@ }
  template:
    metadata:
      labels: { app.kubernetes.io/name: @@WORKLOAD@@, app.kubernetes.io/part-of: @@DOMAIN@@ }
    spec:
      serviceAccountName: @@DOMAIN@@
      automountServiceAccountToken: false
      securityContext: { seccompProfile: { type: RuntimeDefault } }
      terminationGracePeriodSeconds: 30
      containers:
        - name: @@WORKLOAD@@
          image: ghcr.io/replace-me/@@ID@@-@@WORKLOAD@@:0.1.0
          imagePullPolicy: IfNotPresent
          ports: [{ name: http, containerPort: @@CONTAINER_PORT@@ }]
          env: [{ name: PORT, value: "@@CONTAINER_PORT@@" }]
          envFrom:
            - configMapRef: { name: @@DOMAIN@@-config }
            - secretRef: { name: @@DOMAIN@@-runtime }
          readinessProbe: { httpGet: { path: @@HEALTH@@, port: http }, initialDelaySeconds: 5, periodSeconds: 5, timeoutSeconds: 2, failureThreshold: 6 }
          livenessProbe: { httpGet: { path: @@HEALTH@@, port: http }, initialDelaySeconds: 20, periodSeconds: 10, timeoutSeconds: 2 }
          lifecycle: { preStop: { exec: { command: ["/bin/sh", "-c", "sleep 5"] } } }
          resources:
            requests: { cpu: 100m, memory: 128Mi }
            limits: { cpu: 500m, memory: 512Mi }
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: { drop: ["ALL"] }
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          volumeMounts: [{ name: tmp, mountPath: /tmp }]
      volumes: [{ name: tmp, emptyDir: { sizeLimit: 128Mi } }]
---
apiVersion: v1
kind: Service
metadata:
  name: @@NAME@@
  namespace: @@NAMESPACE@@
  labels: { app.kubernetes.io/name: @@WORKLOAD@@, app.kubernetes.io/part-of: @@DOMAIN@@ }
spec:
  selector: { app.kubernetes.io/name: @@WORKLOAD@@, app.kubernetes.io/part-of: @@DOMAIN@@ }
  ports: [{ name: http, port: 80, targetPort: http }]
'@ $wv))
        $scaling.Add((Expand-ProjectTemplate @'
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: { name: @@NAME@@, namespace: @@NAMESPACE@@ }
spec:
  scaleTargetRef: { apiVersion: apps/v1, kind: Deployment, name: @@NAME@@ }
  minReplicas: 2
  maxReplicas: 6
  behavior: { scaleDown: { stabilizationWindowSeconds: 300 } }
  metrics:
    - type: Resource
      resource: { name: cpu, target: { type: Utilization, averageUtilization: 70 } }
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata: { name: @@NAME@@, namespace: @@NAMESPACE@@ }
spec:
  minAvailable: 1
  selector:
    matchLabels: { app.kubernetes.io/name: @@WORKLOAD@@, app.kubernetes.io/part-of: @@DOMAIN@@ }
'@ $wv))
    }
    Write-TemplateFile $Root 'k8s/base/workloads.yaml' ($resources-join"`n") -WhatIfMode:$WhatIfMode
    Write-TemplateFile $Root 'k8s/base/scaling.yaml' ($scaling-join"`n") -WhatIfMode:$WhatIfMode
    $paths=if($Project.Type-eq'Microservices'){@'
          - path: /health
            pathType: Exact
            backend: { service: { name: @@DOMAIN@@-@@ENTRY@@, port: { number: 80 } } }
          - path: /api
            pathType: Prefix
            backend: { service: { name: @@DOMAIN@@-@@ENTRY@@, port: { number: 80 } } }
          - path: /
            pathType: Prefix
            backend: { service: { name: @@DOMAIN@@-@@UI@@, port: { number: 80 } } }
'@}else{@'
          - path: /
            pathType: Prefix
            backend: { service: { name: @@DOMAIN@@-@@ENTRY@@, port: { number: 80 } } }
'@}
    Write-TemplateFile $Root 'k8s/base/ingress.yaml' (Expand-ProjectTemplate @'
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: @@DOMAIN@@
  namespace: @@NAMESPACE@@
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 1m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "15"
spec:
  ingressClassName: nginx
  rules:
    - host: @@DOMAIN@@.local.example
      http:
        paths:
@@PATHS@@
'@ ($v+@{PATHS=(Expand-ProjectTemplate $paths $v)})) -WhatIfMode:$WhatIfMode
    Write-TemplateFile $Root 'k8s/base/networkpolicy.yaml' (Expand-ProjectTemplate @'
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata: { name: default-deny, namespace: @@NAMESPACE@@ }
spec: { podSelector: {}, policyTypes: [Ingress, Egress] }
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata: { name: allow-required, namespace: @@NAMESPACE@@ }
spec:
  podSelector: { matchLabels: { app.kubernetes.io/part-of: @@DOMAIN@@ } }
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        - podSelector: {}
        - namespaceSelector: { matchLabels: { kubernetes.io/metadata.name: ingress-nginx } }
  egress:
    - to: [{ namespaceSelector: { matchLabels: { kubernetes.io/metadata.name: kube-system } } }]
      ports: [{ protocol: UDP, port: 53 }, { protocol: TCP, port: 53 }]
    - to: [{ podSelector: {} }]
    - to: [{ ipBlock: { cidr: 10.40.0.0/16 } }]
      ports: [{ protocol: TCP, port: 5432 }]
    - to: [{ ipBlock: { cidr: 0.0.0.0/0, except: [10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16] } }]
'@ $v) -WhatIfMode:$WhatIfMode
    Write-TemplateFile $Root 'k8s/base/kustomization.yaml' @'
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [namespace.yaml, configmap.yaml, workloads.yaml, scaling.yaml, ingress.yaml, networkpolicy.yaml]
'@ -WhatIfMode:$WhatIfMode
    Write-TemplateFile $Root 'k8s/overlays/dev/kustomization.yaml' @'
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [../../base, secret.local.yaml]
labels:
  - pairs: { app.kubernetes.io/environment: dev }
patches:
  - target: { kind: Deployment }
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target: { kind: HorizontalPodAutoscaler }
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 3
'@ -WhatIfMode:$WhatIfMode
    Write-TemplateFile $Root 'k8s/overlays/prod/kustomization.yaml' @'
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [../../base]
labels:
  - pairs: { app.kubernetes.io/environment: prod }
patches:
  - target: { kind: Deployment }
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
  - target: { kind: HorizontalPodAutoscaler }
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 3
      - op: replace
        path: /spec/maxReplicas
        value: 10
'@ -WhatIfMode:$WhatIfMode
}

function New-HelmFiles {
    param([string]$Root,[hashtable]$Project,[switch]$WhatIfMode)
    $v=Get-ProjectValues $Project
    Write-TemplateFile $Root 'helm/Chart.yaml' (Expand-ProjectTemplate @'
apiVersion: v2
name: @@DOMAIN@@
description: Module 20 chart for @@ID@@
type: application
version: 0.1.0
appVersion: "0.1.0"
kubeVersion: ">=1.28.0-0"
'@ $v) -WhatIfMode:$WhatIfMode
    $values=[System.Collections.Generic.List[string]]::new()
    $values.Add((Expand-ProjectTemplate @'
image:
  registry: ghcr.io
  owner: replace-me
  prefix: @@ID@@
  tag: 0.1.0
  pullPolicy: IfNotPresent
existingSecret: ""
config: { APP_ENV: production, LOG_LEVEL: info }
workloads:
'@ $v))
    foreach($w in $Project.Workloads){$values.Add("  - { name: $($w.Name), port: $($w.Port), health: $($w.Health), replicas: 2 }")}
    $values.Add((Expand-ProjectTemplate @'
ingress: { enabled: true, className: nginx, host: @@DOMAIN@@.example.com }
autoscaling: { enabled: true, min: 2, max: 6, cpu: 70 }
'@ $v))
    Write-TemplateFile $Root 'helm/values.yaml' ($values-join"`n") -WhatIfMode:$WhatIfMode
    Write-TemplateFile $Root 'helm/templates/resources.yaml' (Expand-ProjectTemplate @'
apiVersion: v1
kind: ServiceAccount
metadata: { name: {{ .Release.Name }}-@@DOMAIN@@ }
automountServiceAccountToken: false
---
apiVersion: v1
kind: ConfigMap
metadata: { name: {{ .Release.Name }}-@@DOMAIN@@-config }
data:
{{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- range $w := .Values.workloads }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-@@DOMAIN@@-{{ $w.name }}
  labels: { app.kubernetes.io/instance: {{ $.Release.Name }}, app.kubernetes.io/component: {{ $w.name }}, app.kubernetes.io/part-of: @@DOMAIN@@ }
spec:
  replicas: {{ $w.replicas }}
  strategy: { rollingUpdate: { maxUnavailable: 0, maxSurge: 1 } }
  selector: { matchLabels: { app.kubernetes.io/instance: {{ $.Release.Name }}, app.kubernetes.io/component: {{ $w.name }} } }
  template:
    metadata: { labels: { app.kubernetes.io/instance: {{ $.Release.Name }}, app.kubernetes.io/component: {{ $w.name }}, app.kubernetes.io/part-of: @@DOMAIN@@ } }
    spec:
      serviceAccountName: {{ $.Release.Name }}-@@DOMAIN@@
      automountServiceAccountToken: false
      securityContext: { seccompProfile: { type: RuntimeDefault } }
      containers:
        - name: {{ $w.name }}
          image: "{{ $.Values.image.registry }}/{{ $.Values.image.owner }}/{{ $.Values.image.prefix }}-{{ $w.name }}:{{ $.Values.image.tag }}"
          ports: [{ name: http, containerPort: {{ $w.port }} }]
          env:
            - { name: PORT, value: {{ $w.port | quote }} }
          {{- range $dep := $.Values.workloads }}
            - { name: {{ $dep.name | upper }}_URL, value: "http://{{ $.Release.Name }}-@@DOMAIN@@-{{ $dep.name }}" }
          {{- end }}
          envFrom:
            - configMapRef: { name: {{ $.Release.Name }}-@@DOMAIN@@-config }
            {{- if $.Values.existingSecret }}
            - secretRef: { name: {{ $.Values.existingSecret }} }
            {{- end }}
          readinessProbe: { httpGet: { path: {{ $w.health }}, port: http }, initialDelaySeconds: 5, periodSeconds: 5 }
          livenessProbe: { httpGet: { path: {{ $w.health }}, port: http }, initialDelaySeconds: 20, periodSeconds: 10 }
          resources: { requests: { cpu: 100m, memory: 128Mi }, limits: { cpu: 500m, memory: 512Mi } }
          securityContext: { runAsNonRoot: true, readOnlyRootFilesystem: true, allowPrivilegeEscalation: false, capabilities: { drop: [ALL] } }
          volumeMounts: [{ name: tmp, mountPath: /tmp }]
      volumes: [{ name: tmp, emptyDir: { sizeLimit: 128Mi } }]
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-@@DOMAIN@@-{{ $w.name }}
  labels: { app.kubernetes.io/instance: {{ $.Release.Name }}, app.kubernetes.io/component: {{ $w.name }}, app.kubernetes.io/part-of: @@DOMAIN@@ }
spec:
  selector: { app.kubernetes.io/instance: {{ $.Release.Name }}, app.kubernetes.io/component: {{ $w.name }} }
  ports: [{ name: http, port: 80, targetPort: http }]
{{- if $.Values.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: { name: {{ $.Release.Name }}-@@DOMAIN@@-{{ $w.name }} }
spec:
  scaleTargetRef: { apiVersion: apps/v1, kind: Deployment, name: {{ $.Release.Name }}-@@DOMAIN@@-{{ $w.name }} }
  minReplicas: {{ $.Values.autoscaling.min }}
  maxReplicas: {{ $.Values.autoscaling.max }}
  metrics: [{ type: Resource, resource: { name: cpu, target: { type: Utilization, averageUtilization: {{ $.Values.autoscaling.cpu }} } } }]
{{- end }}
{{- end }}
'@ $v) -WhatIfMode:$WhatIfMode
    Write-TemplateFile $Root 'helm/templates/ingress.yaml' (Expand-ProjectTemplate @'
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: { name: {{ .Release.Name }}-@@DOMAIN@@ }
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /health
            pathType: Exact
            backend: { service: { name: {{ .Release.Name }}-@@DOMAIN@@-@@ENTRY@@, port: { number: 80 } } }
          - path: /api
            pathType: Prefix
            backend: { service: { name: {{ .Release.Name }}-@@DOMAIN@@-@@ENTRY@@, port: { number: 80 } } }
          - path: /
            pathType: Prefix
            backend: { service: { name: {{ .Release.Name }}-@@DOMAIN@@-@@UI@@, port: { number: 80 } } }
{{- end }}
'@ $v) -WhatIfMode:$WhatIfMode
}

function New-DeliveryFiles {
    param([string]$Root,[hashtable]$Project,[switch]$WhatIfMode)
    $v=Get-ProjectValues $Project
    Write-TemplateFile $Root 'scripts/smoke-test.sh' @'
#!/usr/bin/env sh
set -eu
url="${1:-http://localhost:8080}/health"
for attempt in $(seq 1 30); do
  if curl -fsS "$url"; then printf '\nSmoke test passed.\n'; exit 0; fi
  sleep 2
done
echo "Smoke test failed: $url" >&2
exit 1
'@ -WhatIfMode:$WhatIfMode
    Write-TemplateFile $Root 'scripts/validate.ps1' @'
$ErrorActionPreference='Stop'
$required=@('README.md','docker-compose.yml','Jenkinsfile','.github/workflows/ci.yml','docs/HLD.md','docs/LLD.md','k8s/base/kustomization.yaml','helm/Chart.yaml','terraform/main.tf','ansible/deploy.yml','argocd/application.yaml')
foreach($file in $required){if(-not(Test-Path -LiteralPath $file)){throw "Missing $file"}}
if(Get-Command docker -ErrorAction SilentlyContinue){docker compose config --quiet;if($LASTEXITCODE){throw 'Compose validation failed'}}
if(Get-Command kubectl -ErrorAction SilentlyContinue){kubectl kustomize k8s/overlays/dev|Out-Null;if($LASTEXITCODE){throw 'Kustomize validation failed'}}
Write-Host 'Static validation passed.'
'@ -WhatIfMode:$WhatIfMode
    Write-TemplateFile $Root '.github/workflows/ci.yml' (Expand-ProjectTemplate @'
name: ci
on:
  pull_request:
  push: { branches: [main] }
  workflow_dispatch:
permissions: { contents: read, packages: write, security-events: write }
concurrency: { group: "@@ID@@-${{ github.ref }}", cancel-in-progress: true }
env:
  REGISTRY: ghcr.io/${{ github.repository_owner }}
  IMAGE_TAG: ${{ github.sha }}
jobs:
  build-test-scan:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@v4
      - run: docker compose config --quiet
      - run: kubectl kustomize k8s/overlays/dev >/tmp/manifests.yaml
      - run: bash scripts/test.sh
      - run: docker compose build --pull
      - run: docker compose up -d
      - run: bash scripts/smoke-test.sh http://localhost:@@PORT@@
      - if: failure()
        run: docker compose logs --no-color --tail=300
      - if: always()
        run: docker compose down --volumes --remove-orphans
      - uses: aquasecurity/trivy-action@0.28.0
        with: { scan-type: fs, scan-ref: ., format: sarif, output: trivy.sarif, severity: "HIGH,CRITICAL", ignore-unfixed: true }
      - if: always()
        uses: github/codeql-action/upload-sarif@v3
        with: { sarif_file: trivy.sarif }
  publish:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build-test-scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with: { registry: ghcr.io, username: "${{ github.actor }}", password: "${{ secrets.GITHUB_TOKEN }}" }
      - run: docker compose build --pull && docker compose push
'@ $v) -WhatIfMode:$WhatIfMode
    Write-TemplateFile $Root 'Jenkinsfile' (Expand-ProjectTemplate @'
pipeline {
  agent any
  options { timestamps(); timeout(time: 45, unit: 'MINUTES'); disableConcurrentBuilds(abortPrevious: true) }
  parameters {
    string(name: 'REGISTRY', defaultValue: 'registry.example.com/team')
    string(name: 'IMAGE_TAG', defaultValue: '')
    choice(name: 'DEPLOY_ENV', choices: ['none','dev','prod'])
  }
  environment { REGISTRY_AUTH=credentials('oci-registry-credentials'); KUBE_NAMESPACE='@@NAMESPACE@@' }
  stages {
    stage('Checkout'){steps{checkout scm}}
    stage('Version'){steps{script{env.RESOLVED_TAG=params.IMAGE_TAG?.trim()?params.IMAGE_TAG.trim():sh(returnStdout:true,script:'git rev-parse --short=12 HEAD').trim()}}}
    stage('Validate'){parallel{
      stage('Source'){steps{sh 'bash scripts/test.sh'}}
      stage('Compose'){steps{sh 'docker compose config --quiet'}}
      stage('Kubernetes'){steps{sh 'kubectl kustomize k8s/overlays/dev >/tmp/rendered.yaml'}}
      stage('Terraform'){steps{sh 'terraform -chdir=terraform fmt -check -recursive'}}
    }}
    stage('Build'){steps{sh 'REGISTRY=$REGISTRY IMAGE_TAG=$RESOLVED_TAG docker compose build --pull'}}
    stage('Smoke'){steps{sh 'REGISTRY=$REGISTRY IMAGE_TAG=$RESOLVED_TAG docker compose up -d';sh 'bash scripts/smoke-test.sh http://localhost:@@PORT@@'}}
    stage('Scan'){steps{sh 'trivy fs --exit-code 1 --severity HIGH,CRITICAL --ignore-unfixed .'}}
    stage('Publish'){when{branch 'main'}steps{sh 'echo "$REGISTRY_AUTH_PSW"|docker login "${REGISTRY%%/*}" -u "$REGISTRY_AUTH_USR" --password-stdin';sh 'REGISTRY=$REGISTRY IMAGE_TAG=$RESOLVED_TAG docker compose push'}}
    stage('Deploy'){when{expression{params.DEPLOY_ENV!='none'}}input{message 'Deploy reviewed immutable images?'}steps{withCredentials([file(credentialsId:"kubeconfig-${params.DEPLOY_ENV}",variable:'KUBECONFIG')]){sh 'helm upgrade --install @@DOMAIN@@ helm -n "$KUBE_NAMESPACE" --create-namespace --set image.tag="$RESOLVED_TAG" --atomic --timeout 10m';sh 'kubectl -n "$KUBE_NAMESPACE" rollout status deployment --timeout=5m'}}}
  }
  post { always { sh 'docker compose logs --no-color --tail=300 >compose.log || true';archiveArtifacts artifacts:'compose.log',allowEmptyArchive:true;sh 'docker compose down --volumes --remove-orphans || true' } }
}
'@ $v) -WhatIfMode:$WhatIfMode
    Write-TemplateFile $Root 'ansible/ansible.cfg' @'
[defaults]
inventory=inventory.ini
host_key_checking=True
retry_files_enabled=False
interpreter_python=auto_silent
'@ -WhatIfMode:$WhatIfMode
    Write-TemplateFile $Root 'ansible/inventory.example.ini' @'
[app_hosts]
app01.example.internal ansible_user=ubuntu ansible_ssh_private_key_file=/approved/key/path
'@ -WhatIfMode:$WhatIfMode
    Write-TemplateFile $Root 'ansible/requirements.yml' @'
collections:
  - name: community.docker
    version: ">=3.10.0,<5.0.0"
'@ -WhatIfMode:$WhatIfMode
    Write-TemplateFile $Root 'ansible/deploy.yml' (Expand-ProjectTemplate @'
---
- name: Deploy @@TITLE@@
  hosts: app_hosts
  become: true
  serial: 1
  vars: { project_dir: /opt/@@ID@@ }
  pre_tasks:
    - ansible.builtin.assert: { that: ["registry is defined", "image_tag is defined"], fail_msg: "Provide approved registry and immutable image_tag." }
    - ansible.builtin.apt: { name: [docker.io, docker-compose-v2, ca-certificates, curl], state: present, update_cache: true }
    - ansible.builtin.service: { name: docker, state: started, enabled: true }
  tasks:
    - ansible.builtin.file: { path: "{{ project_dir }}", state: directory, owner: root, group: docker, mode: "0750" }
    - ansible.builtin.copy: { src: "{{ playbook_dir }}/../", dest: "{{ project_dir }}/", owner: root, group: docker, mode: preserve }
    - ansible.builtin.template: { src: env.j2, dest: "{{ project_dir }}/.env", owner: root, group: docker, mode: "0640" }
      no_log: true
    - ansible.builtin.command: { cmd: "docker compose config --quiet", chdir: "{{ project_dir }}" }
      changed_when: false
    - ansible.builtin.command: { cmd: "docker compose pull", chdir: "{{ project_dir }}" }
      changed_when: true
    - community.docker.docker_compose_v2: { project_src: "{{ project_dir }}", state: present, remove_orphans: true, wait: true, wait_timeout: 180 }
    - ansible.builtin.uri: { url: "http://127.0.0.1:@@PORT@@/health", status_code: 200 }
      register: health
      retries: 20
      delay: 3
      until: health.status == 200
'@ $v) -WhatIfMode:$WhatIfMode
    Write-TemplateFile $Root 'ansible/templates/env.j2' (Expand-ProjectTemplate @'
PROJECT_NAME=@@ID@@
ENVIRONMENT={{ deploy_environment | default('dev') }}
REGISTRY={{ registry }}
IMAGE_TAG={{ image_tag }}
POSTGRES_USER={{ vault_postgres_user | default('app') }}
POSTGRES_PASSWORD={{ vault_postgres_password }}
POSTGRES_DB={{ vault_postgres_db | default('app') }}
'@ $v) -WhatIfMode:$WhatIfMode
    Write-TemplateFile $Root 'argocd/application.yaml' (Expand-ProjectTemplate @'
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: { name: @@DOMAIN@@, namespace: argocd, finalizers: [resources-finalizer.argocd.argoproj.io] }
spec:
  project: default
  source:
    repoURL: https://github.com/replace-me/devops-masterclass.git
    targetRevision: main
    path: "20. Final Mega Capstone Project/projects/@@ID@@/k8s/overlays/prod"
  destination: { server: https://kubernetes.default.svc, namespace: @@NAMESPACE@@ }
  syncPolicy:
    automated: { prune: true, selfHeal: true, allowEmpty: false }
    syncOptions: [CreateNamespace=true, PruneLast=true]
    retry: { limit: 5, backoff: { duration: 10s, factor: 2, maxDuration: 3m } }
'@ $v) -WhatIfMode:$WhatIfMode
    Write-TemplateFile $Root 'observability/servicemonitor.yaml' (Expand-ProjectTemplate @'
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata: { name: @@DOMAIN@@, namespace: @@NAMESPACE@@ }
spec:
  selector: { matchLabels: { app.kubernetes.io/name: @@ENTRY@@, app.kubernetes.io/part-of: @@DOMAIN@@ } }
  endpoints: [{ port: http, path: /metrics, interval: 30s, scrapeTimeout: 10s }]
'@ $v) -WhatIfMode:$WhatIfMode
    Write-TemplateFile $Root 'observability/prometheusrule.yaml' (Expand-ProjectTemplate @'
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata: { name: @@DOMAIN@@, namespace: @@NAMESPACE@@ }
spec:
  groups:
    - name: @@DOMAIN@@.availability
      rules:
        - alert: PublicEndpointDown
          expr: up{namespace="@@NAMESPACE@@",service="@@DOMAIN@@-@@ENTRY@@"} == 0
          for: 5m
          labels: { severity: critical }
          annotations: { summary: "@@DOMAIN@@ entry workload is down", runbook_url: "docs/RUNBOOK.md" }
'@ $v) -WhatIfMode:$WhatIfMode
    Write-TemplateFile $Root 'security/kyverno-policy.yaml' (Expand-ProjectTemplate @'
apiVersion: kyverno.io/v1
kind: Policy
metadata: { name: @@DOMAIN@@-baseline, namespace: @@NAMESPACE@@ }
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: secure-context
      match: { any: [{ resources: { kinds: [Pod] } }] }
      validate:
        message: Containers must run non-root, deny privilege escalation, and drop capabilities.
        pattern: { spec: { containers: [{ securityContext: { runAsNonRoot: true, allowPrivilegeEscalation: false, capabilities: { drop: [ALL] } } }] } }
    - name: resources
      match: { any: [{ resources: { kinds: [Pod] } }] }
      validate:
        message: CPU and memory requests and limits are required.
        pattern: { spec: { containers: [{ resources: { requests: { cpu: "?*", memory: "?*" }, limits: { cpu: "?*", memory: "?*" } } }] } }
'@ $v) -WhatIfMode:$WhatIfMode
}

function New-TerraformFiles {
    param([string]$Root,[hashtable]$Project,[switch]$WhatIfMode)
    $v=Get-ProjectValues $Project
    $repos=($Project.Workloads|ForEach-Object{'    "'+$_.Name+'",'})-join"`n"
    $createPostgres=if($Project.ContainsKey('CreatePostgres')){([bool]$Project.CreatePostgres).ToString().ToLowerInvariant()}else{'true'}
    Write-TemplateFile $Root 'terraform/versions.tf' @'
terraform {
  required_version = ">= 1.7.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 6.0"
    }
  }
  # Configure an encrypted, versioned, locked S3 backend before team use.
}

provider "aws" {
  region = var.aws_region
  default_tags { tags = local.tags }
}
'@ -WhatIfMode:$WhatIfMode
    Write-TemplateFile $Root 'terraform/main.tf' (Expand-ProjectTemplate @'
locals {
  name = "${var.project_name}-${var.environment}"
  tags = merge(var.tags, {
    Project     = var.project_name
    Environment = var.environment
    ManagedBy   = "terraform"
    Template    = "@@ID@@"
  })
}

data "aws_availability_zones" "available" { state = "available" }

module "vpc" {
  source                 = "terraform-aws-modules/vpc/aws"
  version                = "~> 6.0"
  name                   = local.name
  cidr                   = var.vpc_cidr
  azs                    = slice(data.aws_availability_zones.available.names, 0, 3)
  private_subnets        = [for i in range(3) : cidrsubnet(var.vpc_cidr, 4, i)]
  public_subnets         = [for i in range(3) : cidrsubnet(var.vpc_cidr, 8, i + 48)]
  database_subnets       = [for i in range(3) : cidrsubnet(var.vpc_cidr, 8, i + 64)]
  enable_nat_gateway     = true
  single_nat_gateway     = var.environment != "prod"
  one_nat_gateway_per_az = var.environment == "prod"
  enable_dns_hostnames   = true
  public_subnet_tags     = { "kubernetes.io/role/elb" = "1" }
  private_subnet_tags    = { "kubernetes.io/role/internal-elb" = "1" }
}

module "eks" {
  source                                   = "terraform-aws-modules/eks/aws"
  version                                  = "~> 21.0"
  name                                     = local.name
  kubernetes_version                       = var.kubernetes_version
  endpoint_public_access                   = var.cluster_endpoint_public_access
  enable_cluster_creator_admin_permissions = true
  deletion_protection                      = var.environment == "prod"
  enabled_log_types                        = ["api", "audit", "authenticator", "controllerManager", "scheduler"]
  upgrade_policy                           = { support_type = "STANDARD" }
  vpc_id                                   = module.vpc.vpc_id
  subnet_ids                               = module.vpc.private_subnets
  addons = {
    coredns            = { most_recent = true }
    kube-proxy         = { most_recent = true }
    vpc-cni            = { most_recent = true }
    aws-ebs-csi-driver = { most_recent = true }
  }
  eks_managed_node_groups = {
    application = {
      instance_types = var.node_instance_types
      min_size       = 2
      max_size       = 6
      desired_size   = 3
      capacity_type  = "ON_DEMAND"
    }
  }
}

resource "aws_ecr_repository" "workload" {
  for_each             = toset(var.workloads)
  name                 = "${var.project_name}-${each.value}"
  image_tag_mutability = "IMMUTABLE"
  image_scanning_configuration { scan_on_push = true }
  encryption_configuration { encryption_type = "AES256" }
}

resource "aws_db_subnet_group" "app" {
  count      = var.create_postgres ? 1 : 0
  name       = local.name
  subnet_ids = module.vpc.database_subnets
}

resource "aws_security_group" "postgres" {
  count       = var.create_postgres ? 1 : 0
  name_prefix = "${local.name}-db-"
  vpc_id      = module.vpc.vpc_id
  ingress {
    protocol        = "tcp"
    from_port       = 5432
    to_port         = 5432
    security_groups = [module.eks.node_security_group_id]
  }
  egress {
    protocol    = "-1"
    from_port   = 0
    to_port     = 0
    cidr_blocks = ["0.0.0.0/0"]
  }
}

resource "aws_db_instance" "app" {
  count                       = var.create_postgres ? 1 : 0
  identifier                  = local.name
  engine                      = "postgres"
  instance_class              = var.postgres_instance_class
  allocated_storage           = 20
  max_allocated_storage       = 100
  storage_type                = "gp3"
  storage_encrypted           = true
  db_name                     = "app"
  username                    = "platform_admin"
  manage_master_user_password = true
  publicly_accessible         = false
  multi_az                    = var.environment == "prod"
  backup_retention_period     = var.environment == "prod" ? 14 : 3
  deletion_protection         = var.environment == "prod"
  skip_final_snapshot         = var.environment != "prod"
  final_snapshot_identifier   = var.environment == "prod" ? "${local.name}-final" : null
  db_subnet_group_name        = aws_db_subnet_group.app[0].name
  vpc_security_group_ids      = [aws_security_group.postgres[0].id]
}
'@ $v) -WhatIfMode:$WhatIfMode
    Write-TemplateFile $Root 'terraform/variables.tf' (Expand-ProjectTemplate @'
variable "project_name" {
  type    = string
  default = "@@DOMAIN@@"
}
variable "environment" {
  type    = string
  default = "dev"
  validation {
    condition     = contains(["dev", "qa", "prod"], var.environment)
    error_message = "Use dev, qa, or prod."
  }
}
variable "aws_region" {
  type    = string
  default = "us-east-1"
}
variable "vpc_cidr" {
  type    = string
  default = "10.40.0.0/16"
}
variable "kubernetes_version" {
  type        = string
  default     = "1.36"
  description = "Verify current regional EKS support before apply."
}
variable "cluster_endpoint_public_access" {
  type    = bool
  default = false
}
variable "node_instance_types" {
  type    = list(string)
  default = ["m6i.large"]
}
variable "workloads" {
  type = list(string)
  default = [
@@REPOS@@
  ]
}
variable "create_postgres" {
  type    = bool
  default = @@CREATE_POSTGRES@@
}
variable "postgres_instance_class" {
  type    = string
  default = "db.t4g.micro"
}
variable "tags" {
  type    = map(string)
  default = { Owner = "replace-with-owner", CostCenter = "replace-with-cost-center" }
}
'@ ($v+@{REPOS=$repos;CREATE_POSTGRES=$createPostgres})) -WhatIfMode:$WhatIfMode
    Write-TemplateFile $Root 'terraform/outputs.tf' @'
output "cluster_name" {
  value = module.eks.cluster_name
}
output "configure_kubectl" {
  value = "aws eks update-kubeconfig --region ${var.aws_region} --name ${module.eks.cluster_name}"
}
output "ecr_urls" {
  value = { for name, repo in aws_ecr_repository.workload : name => repo.repository_url }
}
output "postgres_endpoint" {
  value     = try(aws_db_instance.app[0].address, null)
  sensitive = true
}
output "postgres_secret_arn" {
  value     = try(aws_db_instance.app[0].master_user_secret[0].secret_arn, null)
  sensitive = true
}
'@ -WhatIfMode:$WhatIfMode
    Write-TemplateFile $Root 'terraform/terraform.tfvars.example' (Expand-ProjectTemplate @'
project_name = "@@DOMAIN@@"
environment  = "dev"
aws_region   = "us-east-1"
vpc_cidr     = "10.40.0.0/16"
kubernetes_version = "1.36" # verify current regional EKS support
cluster_endpoint_public_access = false
node_instance_types = ["m6i.large"]
create_postgres = true
postgres_instance_class = "db.t4g.micro"
tags = { Owner = "replace-with-owner", CostCenter = "replace-with-cost-center", DataClass = "internal" }
'@ $v) -WhatIfMode:$WhatIfMode
}

function New-CommonProject {
    param([hashtable]$Project,[switch]$WhatIfMode)
    $root=Join-Path $script:ProjectsRoot $Project.Id
    New-ProjectDocs $root $Project -WhatIfMode:$WhatIfMode
    New-KubernetesFiles $root $Project -WhatIfMode:$WhatIfMode
    New-HelmFiles $root $Project -WhatIfMode:$WhatIfMode
    New-DeliveryFiles $root $Project -WhatIfMode:$WhatIfMode
    New-TerraformFiles $root $Project -WhatIfMode:$WhatIfMode
    return $root
}
