apiVersion: v1
kind: Namespace
metadata:
  name: supplychain-java
  labels:
    app.kubernetes.io/part-of: supplychain
    pod-security.kubernetes.io/enforce: restricted
---
apiVersion: v1
kind: ServiceAccount
metadata: { name: supplychain, namespace: supplychain-java }
automountServiceAccountToken: false
