apiVersion: v1
kind: ServiceAccount
metadata: { name: "${{ values.name }}" }
---
apiVersion: v1
kind: Service
metadata: { name: "${{ values.name }}" }
spec: { selector: { app.kubernetes.io/name: "${{ values.name }}" }, ports: [{ name: http, port: 80, targetPort: http }] }
