const $=id=>document.getElementById(id);
const names={retail:'Retail',risk:'Risk',operations:'Operations',platform:'Platform'};
let state,busy=false,preview=null,importId=crypto.randomUUID(),reviewId=crypto.randomUUID();
function node(tag,text,css){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(css)e.className=css;return e;}
function notice(text='',error=false){$('notice').textContent=text;$('notice').className=error?'notice error':'notice';$('notice').hidden=!text;}
function cash(value,currency=state?.batch?.currency||'USD'){return value==null?'Not set':`${currency} ${(value/1e6).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:6})}`;}
function rows(id,data){$(id).replaceChildren();for(const values of data){const tr=node('tr');for(const value of values){const td=node('td');if(value instanceof Node)td.append(value);else td.textContent=value??'—';tr.append(td);}$(id).append(tr);}}
function micros(value){if(!/^[0-9]+(\.[0-9]{1,6})?$/.test(value))throw Error('Use a positive decimal amount with at most 6 digits after the decimal point.');const [a,b='']=value.split('.');const n=BigInt(a)*1000000n+BigInt(b.padEnd(6,'0'));if(n>1000000000000n)throw Error('Budget exceeds the lab limit.');return Number(n);}
async function api(path,body){let r;try{r=await fetch(path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});}catch{throw Error('Cannot reach Cost Desk. Check the local server and retry.');}const data=await r.json();if(!r.ok)throw Error(typeof data.detail==='string'?data.detail:'Invalid input. Check the form values.');return data;}
function lock(){document.querySelectorAll('button,input,select,textarea').forEach(e=>e.disabled=busy);if(!busy){for(const form of ['budget-form','review-form'])for(const e of $(form).elements)e.disabled=!state?.batch||(form==='review-form'&&!preview);for(const id of ['scenario-team','reduction','preview'])$(id).disabled=!state?.batch;}}
function clearPreview(){preview=null;reviewId=crypto.randomUUID();$('saving').textContent='—';$('scenario-assumption').textContent='Calculate before recording a review.';lock();}
function budgetFields(){const team=state?.teams.find(t=>t.team===$('budget-team').value);$('budget-amount').value=team?.budget_micro==null?'':String(team.budget_micro/1e6);$('budget-state').textContent=team?`${state.batch.period} · ${state.batch.currency} · revision ${team.budget_revision}`:'Import a snapshot first.';}
function chart(daily){const entries=Object.entries(daily).sort();const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 640 220');svg.setAttribute('role','img');svg.setAttribute('aria-label','Daily net costs. Exact values are in the table below.');const min=Math.min(0,...entries.map(([,v])=>v)),max=Math.max(1,...entries.map(([,v])=>v));const y=v=>180-(v-min)/(max-min)*150;const add=(tag,attrs,text)=>{const e=document.createElementNS(ns,tag);for(const[k,v]of Object.entries(attrs))e.setAttribute(k,v);if(text)e.textContent=text;svg.append(e);};add('line',{x1:30,x2:620,y1:y(0),y2:y(0),stroke:'#c5bcae'});entries.forEach(([day,value],i)=>{const x=35+i*575/entries.length;add('rect',{x,y:Math.min(y(value),y(0)),width:Math.max(2,450/entries.length),height:Math.max(1,Math.abs(y(value)-y(0))),fill:value<0?'#60759b':'#ba8747'});add('text',{x,y:202},day.slice(-2));});$('chart').replaceChildren(svg);}
function render(){const has=!!state.batch;$('empty').hidden=has;for(const id of ['stats','allocation-panel','trend-panel','units-panel'])$(id).hidden=!has;for(const[t,v]of Object.entries(state.policy.weights))$(`weight-${t}`).value=v;$('policy-revision').textContent=`Saved policy revision ${state.policy.revision}`;budgetFields();
  if(has){$('total').textContent=cash(state.total_micro);$('projected').textContent=cash(state.projected_micro);$('coverage').textContent=state.coverage_percent==null?'Undefined':`${state.coverage_percent.toFixed(2)}%`;$('unallocated').textContent=cash(state.unallocated_micro);$('period-label').textContent=`${state.batch.period} · days 1–${state.batch.through_day}`;$('currency-badge').textContent=`${state.batch.currency} · synthetic`;
    rows('teams',state.teams.map(t=>{const team=node('div',names[t.team]);team.append(node('small',t.service));return[team,cash(t.spend_micro),cash(t.projected_micro),cash(t.budget_micro),node('span',t.variance_micro==null?'No budget':cash(t.variance_micro),t.variance_micro>0?'over':'under')];}));
    rows('units',state.teams.map(t=>[t.service,t.successful_units.toLocaleString(),t.unit,t.cost_per_unit==null?'Undefined: zero success':`${state.batch.currency} ${t.cost_per_unit}`]));
    $('providers').replaceChildren(...Object.entries(state.providers).map(([p,v])=>{const line=node('p',`${p}: ${cash(v)}`,'small muted');return line;}));$('batch-id').textContent=state.batch.id;$('source-count').textContent=`${state.batch.cost_rows} cost rows · ${state.batch.usage_rows} daily usage rows · saved ${new Date(state.batch.created*1000).toLocaleString()}`;rows('daily',Object.entries(state.daily).sort().map(([d,v])=>[d,cash(v)]));chart(state.daily);
  }
  rows('reviews',state.reviews.map(r=>{const who=node('div',r.reviewer);who.append(node('small',r.reason));return[`${names[r.team]} · policy ${r.policy_revision}`,cash(r.scenario.estimated_monthly_savings_micro,r.scenario.currency),r.decision,who,new Date(r.created_at*1000).toLocaleString()];}));$('reviews-empty').hidden=state.reviews.length>0;
}
async function load(){state=await api('/v1/desk');render();clearPreview();$('workspace').hidden=false;}
async function work(fn,message){if(busy)return;busy=true;lock();notice();try{const result=await fn();if(message){await load();notice(typeof message==='function'?message(result):message);}}catch(error){notice(error.message,true);}finally{busy=false;$('loading').hidden=true;lock();}}
$('refresh').addEventListener('click',()=>work(load));
$('load-sample').addEventListener('click',()=>work(async()=>{const sample=await api('/v1/sample');$('period').value=sample.period;$('currency').value=sample.currency;$('through-day').value=sample.through_day;$('cost-csv').value=sample.cost_csv;$('usage-csv').value=sample.usage_csv;importId=crypto.randomUUID();notice('Sample CSVs loaded. Review the inputs, then publish the snapshot.');}));
for(const[name,target,max]of[['cost-file','cost-csv',500000],['usage-file','usage-csv',300000]])$(name).addEventListener('change',()=>work(async()=>{const file=$(name).files[0];if(file){if(file.size>max)throw Error('File exceeds the lab upload limit.');$(target).value=await file.text();importId=crypto.randomUUID();}}));
$('import-form').addEventListener('input',()=>importId=crypto.randomUUID());
$('import-form').addEventListener('submit',event=>{event.preventDefault();const body={request_id:importId,period:$('period').value,currency:$('currency').value,through_day:Number($('through-day').value),cost_csv:$('cost-csv').value,usage_csv:$('usage-csv').value};work(()=>api('/v1/imports',body),'Billing snapshot validated and published. Prior snapshots and reviews were retained.');});
$('policy-form').addEventListener('submit',event=>{event.preventDefault();const body={revision:state.policy.revision};for(const team of Object.keys(names))body[team]=Number($(`weight-${team}`).value);work(()=>api('/v1/policy',body),'Allocation policy saved. Costs were recalculated using the new revision.');});
$('budget-team').addEventListener('change',budgetFields);
$('budget-form').addEventListener('submit',event=>{event.preventDefault();work(()=>{const row=state.teams.find(t=>t.team===$('budget-team').value);return api('/v1/budgets',{batch_id:state.batch.id,team:row.team,revision:row.budget_revision,amount_micro:micros($('budget-amount').value)});},'Team budget saved for this month and currency.');});
for(const id of ['scenario-team','reduction'])$(id).addEventListener('input',clearPreview);
$('preview').addEventListener('click',()=>work(async()=>{const candidate=await api(`/v1/scenario?${new URLSearchParams({team:$('scenario-team').value,reduction_percent:$('reduction').value})}`);if(candidate.batch_id!==state.batch.id||candidate.policy_revision!==state.policy.revision){clearPreview();throw Error('Billing data or allocation changed. Refresh before calculating a scenario.');}preview=candidate;$('saving').textContent=cash(preview.estimated_monthly_savings_micro,preview.currency);$('scenario-assumption').textContent=preview.assumption;reviewId=crypto.randomUUID();}));
$('review-form').addEventListener('input',()=>reviewId=crypto.randomUUID());
$('review-form').addEventListener('submit',event=>{event.preventDefault();if(!preview)return;const body={request_id:reviewId,batch_id:preview.batch_id,policy_revision:preview.policy_revision,team:preview.team,reduction_percent:preview.reduction_percent,decision:$('decision').value,reviewer:$('reviewer').value,reason:$('reason').value};work(()=>api('/v1/reviews',body),'Scenario review saved. This records hypothetical savings; no infrastructure action occurred.');});
work(load);
