{
  "apiVersion": "kustomize.config.k8s.io/v1beta1",
  "kind": "Kustomization",
  "namespace": "standard-prod",
  "namePrefix": "dotnet-",
  "resources": [
    "../../../base",
    "pdb.yaml"
  ],
  "labels": [
    {
      "pairs": {
        "app.kubernetes.io/instance": "dotnet"
      },
      "includeSelectors": true,
      "includeTemplates": true
    }
  ],
  "configMapGenerator": [
    {
      "name": "deployment-config",
      "literals": [
        "APP_ENV=prod",
        "APP_VERSION=unreleased"
      ]
    }
  ],
  "images": [
    {
      "name": "deployment-demo",
      "newName": "ghcr.io/REPLACE_OWNER/standard-dotnet",
      "newTag": "unreleased"
    }
  ],
  "replicas": [
    {
      "name": "deployment-demo",
      "count": 3
    }
  ]
}
