import crypto from"node:crypto";import path from"node:path";import{fileURLToPath}from"node:url";import express from"express";import pg from"pg";import client from"prom-client";import{calculateDueAt,validateTicket}from"./domain.js";
const{Pool}=pg,app=express(),port=Number(process.env.PORT||3000),pool=new Pool({connectionString:process.env.DATABASE_URL,connectionTimeoutMillis:3000,max:10}),webRoot=process.env.WEB_ROOT||path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../../public");
client.collectDefaultMetrics({prefix:"helpdesk_"});const requests=new client.Counter({name:"helpdesk_http_requests_total",help:"Helpdesk HTTP requests",labelNames:["method","route","status"]});
app.use(express.json({limit:"64kb"}));app.use((req,res,next)=>{req.requestId=req.header("X-Request-ID")||crypto.randomUUID();res.setHeader("X-Request-ID",req.requestId);res.on("finish",()=>requests.inc({method:req.method,route:req.route?.path||req.path,status:String(res.statusCode)}));next()});
async function migrate(){await pool.query(`CREATE TABLE IF NOT EXISTS tickets(id uuid PRIMARY KEY,title varchar(160) NOT NULL,customer_email varchar(254) NOT NULL,priority varchar(16) NOT NULL,status varchar(24) NOT NULL,due_at timestamptz NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),idempotency_key varchar(128) UNIQUE NOT NULL);CREATE TABLE IF NOT EXISTS ticket_audit(id bigserial PRIMARY KEY,ticket_id uuid NOT NULL REFERENCES tickets(id),action varchar(64) NOT NULL,created_at timestamptz NOT NULL DEFAULT now())`)}
app.get("/health",async(_q,r)=>{try{await pool.query("SELECT 1");r.json({status:"ok",service:"helpdesk-app"})}catch{r.status(503).json({status:"not_ready"})}});app.get("/metrics",async(_q,r)=>r.type(client.register.contentType).send(await client.register.metrics()));
app.get("/api/tickets",async(_q,r,next)=>{try{const result=await pool.query("SELECT id,title,customer_email AS \"customerEmail\",priority,status,due_at AS \"dueAt\",created_at AS \"createdAt\" FROM tickets ORDER BY created_at DESC LIMIT 200");r.json(result.rows)}catch(e){next(e)}});
app.post("/api/tickets",async(q,r,next)=>{const key=q.header("Idempotency-Key");if(!key||key.length>128)return r.status(400).json({code:"IDEMPOTENCY_KEY_REQUIRED"});const validated=validateTicket(q.body);if(!validated.ok)return r.status(422).json({code:validated.code});const db=await pool.connect();try{await db.query("BEGIN");const existing=await db.query("SELECT id,title,customer_email AS \"customerEmail\",priority,status,due_at AS \"dueAt\",created_at AS \"createdAt\" FROM tickets WHERE idempotency_key=$1",[key]);if(existing.rowCount){await db.query("COMMIT");return r.json(existing.rows[0])}const value=validated.value,id=crypto.randomUUID(),created=await db.query("INSERT INTO tickets(id,title,customer_email,priority,status,due_at,idempotency_key) VALUES($1,$2,$3,$4,'open',$5,$6) ON CONFLICT(idempotency_key) DO NOTHING RETURNING id,title,customer_email AS \"customerEmail\",priority,status,due_at AS \"dueAt\",created_at AS \"createdAt\"",[id,value.title,value.customerEmail,value.priority,calculateDueAt(value.priority),key]);if(!created.rowCount){const raced=await db.query("SELECT id,title,customer_email AS \"customerEmail\",priority,status,due_at AS \"dueAt\",created_at AS \"createdAt\" FROM tickets WHERE idempotency_key=$1",[key]);await db.query("COMMIT");return r.json(raced.rows[0])}await db.query("INSERT INTO ticket_audit(ticket_id,action) VALUES($1,'created')",[id]);await db.query("COMMIT");return r.status(201).json(created.rows[0])}catch(e){await db.query("ROLLBACK");next(e)}finally{db.release()}});
app.patch("/api/tickets/:id/status",async(q,r,next)=>{const status=String(q.body?.status||"");if(!["open","in_progress","resolved"].includes(status))return r.status(422).json({code:"INVALID_STATUS"});try{const result=await pool.query("UPDATE tickets SET status=$1 WHERE id=$2 RETURNING id,title,customer_email AS \"customerEmail\",priority,status,due_at AS \"dueAt\",created_at AS \"createdAt\"",[status,q.params.id]);if(!result.rowCount)return r.status(404).json({code:"TICKET_NOT_FOUND"});await pool.query("INSERT INTO ticket_audit(ticket_id,action) VALUES($1,$2)",[q.params.id,`status:${status}`]);r.json(result.rows[0])}catch(e){next(e)}});
app.use(express.static(webRoot,{index:false,maxAge:"1h"}));app.get("/{*path}",(q,r,next)=>q.path.startsWith("/api/")?next():r.sendFile(path.join(webRoot,"index.html")));app.use((e,q,r,_n)=>{console.error(JSON.stringify({level:"error",requestId:q.requestId,message:e.message}));r.status(500).json({code:"INTERNAL_ERROR",requestId:q.requestId})});
await migrate();app.listen(port,"0.0.0.0",()=>console.log(JSON.stringify({level:"info",service:"helpdesk-app",port})));
